// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package models

import (
	"time"
)

const TableNameAction = "actions"

// Action mapped from table <actions>
type Action struct {
	ID          *int64    `gorm:"column:id;type:INTEGER;primaryKey" json:"id"`
	Name        string    `gorm:"column:name;type:TEXT;not null;index:idx_actions_type_name,priority:2" json:"name"`
	Dialect     string    `gorm:"column:dialect;type:TEXT;not null" json:"dialect"`
	Description *string   `gorm:"column:description;type:TEXT" json:"description"`
	Notes       *string   `gorm:"column:notes;type:TEXT" json:"notes"`
	ActionType  string    `gorm:"column:action_type;type:TEXT;not null;index:idx_actions_type_name,priority:1;index:idx_actions_type,priority:1" json:"actionType"`
	Enabled     bool      `gorm:"column:enabled;type:BOOL;not null" json:"enabled"`
	Suspended   bool      `gorm:"column:suspended;type:BOOL;not null" json:"suspended"`
	CreatedAt   time.Time `gorm:"column:created_at;type:TIMESTAMP;not null" json:"createdAt"`
	UpdatedAt   time.Time `gorm:"column:updated_at;type:TIMESTAMP;not null" json:"updatedAt"`
}

// TableName Action's table name
func (*Action) TableName() string {
	return TableNameAction
}
