// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package models

import (
	"gorm.io/datatypes"
)

const TableNameActionStep = "action_steps"

// ActionStep mapped from table <action_steps>
type ActionStep struct {
	ID             *int64             `gorm:"column:id;type:INTEGER;primaryKey" json:"id"`
	ActionID       int64              `gorm:"column:action_id;type:INTEGER;not null;index:idx_action_steps_action_order,priority:1" json:"actionId"`
	StepOrder      int64              `gorm:"column:step_order;type:INTEGER;not null;index:idx_action_steps_action_order,priority:2" json:"stepOrder"`
	Name           string             `gorm:"column:name;type:TEXT;not null" json:"name"`
	SqlText        string             `gorm:"column:sql_text;type:TEXT;not null" json:"sqlText"`
	TimeoutSeconds *int64             `gorm:"column:timeout_seconds;type:INTEGER" json:"timeoutSeconds"`
	Expectation    *datatypes.JSONMap `gorm:"column:expectation;type:JSONB" json:"expectation"`
	OutputCapture  *datatypes.JSONMap `gorm:"column:output_capture;type:JSONB" json:"outputCapture"`
	OnFailure      *string            `gorm:"column:on_failure;type:TEXT" json:"onFailure"`
}

// TableName ActionStep's table name
func (*ActionStep) TableName() string {
	return TableNameActionStep
}
