// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package models

import (
	"time"

	"gorm.io/datatypes"
)

const TableNameAgentRegistrationRequest = "agent_registration_requests"

// AgentRegistrationRequest mapped from table <agent_registration_requests>
type AgentRegistrationRequest struct {
	RequestID        string             `gorm:"column:request_id;type:TEXT;primaryKey" json:"requestId"`
	UUID             string             `gorm:"column:uuid;type:TEXT;not null;index:idx_agent_reg_requests_uuid_status,priority:1" json:"uuid"`
	Name             string             `gorm:"column:name;type:TEXT;not null" json:"name"`
	PublicKey        string             `gorm:"column:public_key;type:TEXT;not null" json:"publicKey"`
	Version          *string            `gorm:"column:version;type:TEXT" json:"version"`
	Os               *string            `gorm:"column:os;type:TEXT" json:"os"`
	Arch             *string            `gorm:"column:arch;type:TEXT" json:"arch"`
	OsVersion        *string            `gorm:"column:os_version;type:TEXT" json:"osVersion"`
	OsType           *string            `gorm:"column:os_type;type:TEXT" json:"osType"`
	RunningUser      *string            `gorm:"column:running_user;type:TEXT" json:"runningUser"`
	IP               *string            `gorm:"column:ip;type:TEXT" json:"ip"`
	MetadataJSON     *datatypes.JSONMap `gorm:"column:metadata_json;type:JSONB" json:"metadataJson"`
	Status           string             `gorm:"column:status;type:TEXT;not null;index:idx_agent_reg_requests_uuid_status,priority:2;index:idx_agent_reg_requests_status_created,priority:1" json:"status"`
	CreatedAt        *time.Time         `gorm:"column:created_at;type:TIMESTAMP;index:idx_agent_reg_requests_status_created,priority:2" json:"createdAt"`
	ExpiresAt        time.Time          `gorm:"column:expires_at;type:TIMESTAMP;not null" json:"expiresAt"`
	ApprovedByUserID *int64             `gorm:"column:approved_by_user_id;type:INTEGER" json:"approvedByUserId"`
	ApprovedAt       *time.Time         `gorm:"column:approved_at;type:TIMESTAMP" json:"approvedAt"`
	ConsumedAt       *time.Time         `gorm:"column:consumed_at;type:TIMESTAMP" json:"consumedAt"`
}

// TableName AgentRegistrationRequest's table name
func (*AgentRegistrationRequest) TableName() string {
	return TableNameAgentRegistrationRequest
}
