// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package models

import (
	"time"

	"gorm.io/datatypes"
)

const TableNameAgent = "agents"

// Agent mapped from table <agents>
type Agent struct {
	UUID             string             `gorm:"column:uuid;type:TEXT;not null" json:"uuid"`
	Name             string             `gorm:"column:name;type:TEXT;not null" json:"name"`
	Status           string             `gorm:"column:status;type:TEXT;not null;index:idx_agents_status,priority:1" json:"status"`
	Suspended        *bool              `gorm:"column:suspended;type:BOOL" json:"suspended"`
	PublicKey        *string            `gorm:"column:public_key;type:TEXT" json:"publicKey"`
	ApprovedByUserID *int64             `gorm:"column:approved_by_user_id;type:INTEGER" json:"approvedByUserId"`
	ApprovedAt       *time.Time         `gorm:"column:approved_at;type:TIMESTAMP" json:"approvedAt"`
	LastSeenIP       *string            `gorm:"column:last_seen_ip;type:TEXT" json:"lastSeenIp"`
	LastSeenAt       *time.Time         `gorm:"column:last_seen_at;type:TIMESTAMP;index:idx_agents_last_seen,priority:1" json:"lastSeenAt"`
	Version          *string            `gorm:"column:version;type:TEXT" json:"version"`
	Os               *string            `gorm:"column:os;type:TEXT" json:"os"`
	Arch             *string            `gorm:"column:arch;type:TEXT" json:"arch"`
	OsVersion        *string            `gorm:"column:os_version;type:TEXT" json:"osVersion"`
	OsType           *string            `gorm:"column:os_type;type:TEXT" json:"osType"`
	RunningUser      *string            `gorm:"column:running_user;type:TEXT" json:"runningUser"`
	MetadataJSON     *datatypes.JSONMap `gorm:"column:metadata_json;type:JSONB" json:"metadataJson"`
}

// TableName Agent's table name
func (*Agent) TableName() string {
	return TableNameAgent
}
