// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package models

const TableNameAuthKey = "auth_keys"

// AuthKey mapped from table <auth_keys>
type AuthKey struct {
	AuthKey *string `gorm:"column:auth_key;type:TEXT" json:"authKey"`
}

// TableName AuthKey's table name
func (*AuthKey) TableName() string {
	return TableNameAuthKey
}
