// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package models

const TableNameCxSetting = "cx_settings"

// CxSetting mapped from table <cx_settings>
type CxSetting struct {
	ServerURL               *string `gorm:"column:server_url;type:TEXT" json:"serverUrl"`
	SMTPHost                *string `gorm:"column:smtp_host;type:TEXT" json:"smtpHost"`
	SMTPPort                *int64  `gorm:"column:smtp_port;type:INTEGER" json:"smtpPort"`
	SMTPSecure              *string `gorm:"column:smtp_secure;type:TEXT" json:"smtpSecure"`
	SMTPFromName            *string `gorm:"column:smtp_from_name;type:TEXT" json:"smtpFromName"`
	SMTPFromEmail           *string `gorm:"column:smtp_from_email;type:TEXT" json:"smtpFromEmail"`
	SMTPLogin               *string `gorm:"column:smtp_login;type:TEXT" json:"smtpLogin"`
	SMTPPassword            *string `gorm:"column:smtp_password;type:TEXT" json:"smtpPassword"`
	HTTPEnabled             *bool   `gorm:"column:http_enabled;type:BOOL" json:"httpEnabled"`
	HTTPPort                *int64  `gorm:"column:http_port;type:INTEGER" json:"httpPort"`
	HTTPSMode               *string `gorm:"column:https_mode;type:TEXT" json:"httpsMode"`
	HTTPSPort               *int64  `gorm:"column:https_port;type:INTEGER" json:"httpsPort"`
	HTTPSEnabled            *bool   `gorm:"column:https_enabled;type:BOOL" json:"httpsEnabled"`
	HTTPSCertPem            *string `gorm:"column:https_cert_pem;type:TEXT" json:"httpsCertPem"`
	HTTPSKeyPem             *string `gorm:"column:https_key_pem;type:TEXT" json:"httpsKeyPem"`
	SmsProvider             *string `gorm:"column:sms_provider;type:TEXT" json:"smsProvider"`
	SmsFromNumber           *string `gorm:"column:sms_from_number;type:TEXT" json:"smsFromNumber"`
	TwilioUsername          *string `gorm:"column:twilio_username;type:TEXT" json:"twilioUsername"`
	TwilioPassword          *string `gorm:"column:twilio_password;type:TEXT" json:"twilioPassword"`
	TwilioAccountSid        *string `gorm:"column:twilio_account_sid;type:TEXT" json:"twilioAccountSid"`
	TwilioAPIKey            *string `gorm:"column:twilio_api_key;type:TEXT" json:"twilioApiKey"`
	TwilioAPISecret         *string `gorm:"column:twilio_api_secret;type:TEXT" json:"twilioApiSecret"`
	AgentEnabled            *bool   `gorm:"column:agent_enabled;type:BOOL" json:"agentEnabled"`
	AgentPort               *int64  `gorm:"column:agent_port;type:INTEGER" json:"agentPort"`
	SystemAlertEmails       *string `gorm:"column:system_alert_emails;type:TEXT" json:"systemAlertEmails"`
	SystemAlertPhones       *string `gorm:"column:system_alert_phones;type:TEXT" json:"systemAlertPhones"`
	AlertOnAgentLost        *bool   `gorm:"column:alert_on_agent_lost;type:BOOL" json:"alertOnAgentLost"`
	UpdaterEnabled          *bool   `gorm:"column:updater_enabled;type:BOOL" json:"updaterEnabled"`
	UpdaterMode             *string `gorm:"column:updater_mode;type:TEXT" json:"updaterMode"`
	UpdaterWindowStart      *string `gorm:"column:updater_window_start;type:TEXT" json:"updaterWindowStart"`
	UpdaterAgentEnabled     *bool   `gorm:"column:updater_agent_enabled;type:BOOL" json:"updaterAgentEnabled"`
	UpdaterAgentMode        *string `gorm:"column:updater_agent_mode;type:TEXT" json:"updaterAgentMode"`
	UpdaterAgentWindowStart *string `gorm:"column:updater_agent_window_start;type:TEXT" json:"updaterAgentWindowStart"`
	BrandLogoURL            *string `gorm:"column:brand_logo_url;type:TEXT" json:"brandLogoUrl"`
	BrandName               *string `gorm:"column:brand_name;type:TEXT" json:"brandName"`
	ID                      *int64  `gorm:"column:id;type:INTEGER" json:"id"`
}

// TableName CxSetting's table name
func (*CxSetting) TableName() string {
	return TableNameCxSetting
}
