// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package models

const TableNameCxUser = "cx_users"

// CxUser mapped from table <cx_users>
type CxUser struct {
	ID                  int64   `gorm:"column:id;type:INTEGER;primaryKey" json:"id"`
	Email               string  `gorm:"column:email;type:TEXT;not null" json:"email"`
	Name                string  `gorm:"column:name;type:TEXT;not null" json:"name"`
	Phone               *string `gorm:"column:phone;type:TEXT" json:"phone"`
	Password            *string `gorm:"column:password;type:TEXT" json:",omitempty"`
	ForcePasswordChange bool    `gorm:"column:force_password_change;type:BOOL;not null" json:"forcePasswordChange"`
	Enabled             bool    `gorm:"column:enabled;type:BOOL;not null" json:"enabled"`
	Suspended           bool    `gorm:"column:suspended;type:BOOL;not null" json:"suspended"`
	Admin               bool    `gorm:"column:admin;type:BOOL;not null" json:"admin"`
	Sv                  int32   `gorm:"column:sv;type:integer;not null" json:"-"`
	TimeZone            *string `gorm:"column:time_zone;type:TEXT" json:"timeZone"`
	TimeFormat          *string `gorm:"column:time_format;type:TEXT" json:"timeFormat"`
}

// TableName CxUser's table name
func (*CxUser) TableName() string {
	return TableNameCxUser
}
