// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package models

import (
	"time"
)

const TableNameDbConnection = "db_connections"

// DbConnection mapped from table <db_connections>
type DbConnection struct {
	ID                       *int64     `gorm:"column:id;type:INTEGER" json:"id"`
	Name                     string     `gorm:"column:name;type:TEXT;not null" json:"name"`
	Driver                   string     `gorm:"column:driver;type:TEXT;not null;index:idx_db_connections_driver,priority:1" json:"driver"`
	Dsn                      *string    `gorm:"column:dsn;type:TEXT" json:"dsn"`
	Description              *string    `gorm:"column:description;type:TEXT" json:"description"`
	AutoCheckEnabled         *int64     `gorm:"column:auto_check_enabled;type:INTEGER" json:"autoCheckEnabled"`
	AutoCheckIntervalSeconds *int64     `gorm:"column:auto_check_interval_seconds;type:INTEGER" json:"autoCheckIntervalSeconds"`
	AgentUUID                *string    `gorm:"column:agent_uuid;type:TEXT;index:idx_db_connections_agent,priority:1" json:"agentUuid"`
	CreatedAt                *time.Time `gorm:"column:created_at;type:TIMESTAMP" json:"createdAt"`
	UpdatedAt                *time.Time `gorm:"column:updated_at;type:TIMESTAMP" json:"updatedAt"`
	LastStatus               *string    `gorm:"column:last_status;type:TEXT" json:"lastStatus"`
	LastError                *string    `gorm:"column:last_error;type:TEXT" json:"lastError"`
	LastCheckedAt            *time.Time `gorm:"column:last_checked_at;type:TIMESTAMP" json:"lastCheckedAt"`
	AlertEmails              *string    `gorm:"column:alert_emails;type:TEXT" json:"alertEmails"`
	AlertPhones              *string    `gorm:"column:alert_phones;type:TEXT" json:"alertPhones"`
	NotifyOnFailure          *bool      `gorm:"column:notify_on_failure;type:BOOL" json:"notifyOnFailure"`
	Enabled                  *bool      `gorm:"column:enabled;type:BOOL" json:"enabled"`
	Suspended                *bool      `gorm:"column:suspended;type:BOOL" json:"suspended"`
}

// TableName DbConnection's table name
func (*DbConnection) TableName() string {
	return TableNameDbConnection
}
