// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package models

import (
	"time"
)

const TableNameFeatureRequest = "feature_requests"

// FeatureRequest mapped from table <feature_requests>
type FeatureRequest struct {
	ID                  *int64                `gorm:"column:id;type:INTEGER;primaryKey" json:"id"`
	Summary             string                `gorm:"column:summary;type:TEXT;not null" json:"summary"`
	Description         string                `gorm:"column:description;type:TEXT;not null" json:"description"`
	UserID              int64                 `gorm:"column:user_id;type:INTEGER;not null" json:"userId"`
	CreatedAt           time.Time             `gorm:"column:created_at;type:TIMESTAMP;not null" json:"createdAt"`
	Status              string                `gorm:"column:status;type:TEXT;not null" json:"status"`
	FeedbackAttachments []*FeedbackAttachment `gorm:"foreignKey:FeatureRequestID;references:ID" json:"feedbackAttachments"`
}

// TableName FeatureRequest's table name
func (*FeatureRequest) TableName() string {
	return TableNameFeatureRequest
}
