// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package models

import (
	"time"
)

const TableNameFeedbackAttachment = "feedback_attachments"

// FeedbackAttachment mapped from table <feedback_attachments>
type FeedbackAttachment struct {
	ID               *int64    `gorm:"column:id;type:INTEGER;primaryKey" json:"id"`
	BugReportID      *int64    `gorm:"column:bug_report_id;type:INTEGER" json:"bugReportId"`
	FeatureRequestID *int64    `gorm:"column:feature_request_id;type:INTEGER" json:"featureRequestId"`
	FileName         string    `gorm:"column:file_name;type:TEXT;not null" json:"fileName"`
	FilePath         string    `gorm:"column:file_path;type:TEXT;not null" json:"filePath"`
	ContentType      string    `gorm:"column:content_type;type:TEXT;not null" json:"contentType"`
	FileSize         int64     `gorm:"column:file_size;type:INTEGER;not null" json:"fileSize"`
	CreatedAt        time.Time `gorm:"column:created_at;type:TIMESTAMP;not null" json:"createdAt"`
}

// TableName FeedbackAttachment's table name
func (*FeedbackAttachment) TableName() string {
	return TableNameFeedbackAttachment
}
