// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package models

const TableNameJobVariable = "job_variables"

// JobVariable mapped from table <job_variables>
type JobVariable struct {
	ID    *int64  `gorm:"column:id;type:INTEGER;primaryKey" json:"id"`
	JobID int64   `gorm:"column:job_id;type:INTEGER;not null;uniqueIndex:uq_job_variables_job_name,priority:1;index:idx_job_variables_job,priority:1" json:"jobId"`
	Name  string  `gorm:"column:name;type:TEXT;not null;uniqueIndex:uq_job_variables_job_name,priority:2" json:"name"`
	Value *string `gorm:"column:value;type:TEXT" json:"value"`
}

// TableName JobVariable's table name
func (*JobVariable) TableName() string {
	return TableNameJobVariable
}
