// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package models

import (
	"time"

	"gorm.io/datatypes"
)

const TableNameJobRun = "job_runs"

// JobRun mapped from table <job_runs>
type JobRun struct {
	ID                  *int64             `gorm:"column:id;type:INTEGER;primaryKey" json:"id"`
	RunUID              *string            `gorm:"column:run_uid;type:TEXT" json:"runUid"`
	JobID               *int64             `gorm:"column:job_id;type:INTEGER;index:idx_job_runs_job_time,priority:1" json:"jobId"`
	JobName             *string            `gorm:"column:job_name;type:TEXT" json:"jobName"`
	ConnectionID        *int64             `gorm:"column:connection_id;type:INTEGER" json:"connectionId"`
	ActionID            *int64             `gorm:"column:action_id;type:INTEGER" json:"actionId"`
	ConnectionKind      *string            `gorm:"column:connection_kind;type:TEXT" json:"connectionKind"`
	ShellConnectionID   *int64             `gorm:"column:shell_connection_id;type:INTEGER;index:idx_job_runs_shell_conn,priority:1" json:"shellConnectionId"`
	WebtaskConnectionID *int64             `gorm:"column:webtask_connection_id;type:INTEGER;index:idx_job_runs_webtask_conn,priority:1" json:"webtaskConnectionId"`
	QueuedAt            *time.Time         `gorm:"column:queued_at;type:TIMESTAMP;index:idx_job_runs_status_time,priority:2;index:idx_job_runs_job_time,priority:2" json:"queuedAt"`
	StartedAt           *time.Time         `gorm:"column:started_at;type:TIMESTAMP;index:idx_job_runs_started_time,priority:1" json:"startedAt"`
	FinishedAt          *time.Time         `gorm:"column:finished_at;type:TIMESTAMP" json:"finishedAt"`
	Status              *string            `gorm:"column:status;type:TEXT;index:idx_job_runs_status_time,priority:1" json:"status"`
	TriggeredBy         *int64             `gorm:"column:triggered_by;type:INTEGER" json:"triggeredBy"`
	TriggerSource       *string            `gorm:"column:trigger_source;type:TEXT" json:"triggerSource"`
	Message             *string            `gorm:"column:message;type:TEXT" json:"message"`
	RowsAffected        *int64             `gorm:"column:rows_affected;type:INTEGER" json:"rowsAffected"`
	ErrorCode           *string            `gorm:"column:error_code;type:TEXT" json:"errorCode"`
	ErrorDetails        *string            `gorm:"column:error_details;type:TEXT" json:"errorDetails"`
	Summary             *datatypes.JSONMap `gorm:"column:summary;type:JSONB" json:"summary"`
}

// TableName JobRun's table name
func (*JobRun) TableName() string {
	return TableNameJobRun
}
