// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package models

const TableNameJobRunShellIo = "job_run_shell_io"

// JobRunShellIo mapped from table <job_run_shell_io>
type JobRunShellIo struct {
	ID               *int64  `gorm:"column:id;type:INTEGER;primaryKey" json:"id"`
	StepID           int64   `gorm:"column:step_id;type:INTEGER;not null;index:idx_job_run_shell_io_step,priority:1" json:"stepId"`
	StdoutText       *string `gorm:"column:stdout_text;type:TEXT" json:"stdoutText"`
	StderrText       *string `gorm:"column:stderr_text;type:TEXT" json:"stderrText"`
	StdoutTruncated  bool    `gorm:"column:stdout_truncated;type:BOOL;not null" json:"stdoutTruncated"`
	StderrTruncated  bool    `gorm:"column:stderr_truncated;type:BOOL;not null" json:"stderrTruncated"`
	StdoutBytes      *int64  `gorm:"column:stdout_bytes;type:INTEGER" json:"stdoutBytes"`
	StderrBytes      *int64  `gorm:"column:stderr_bytes;type:INTEGER" json:"stderrBytes"`
	StdoutTotalBytes *int64  `gorm:"column:stdout_total_bytes;type:INTEGER" json:"stdoutTotalBytes"`
	StderrTotalBytes *int64  `gorm:"column:stderr_total_bytes;type:INTEGER" json:"stderrTotalBytes"`
}

// TableName JobRunShellIo's table name
func (*JobRunShellIo) TableName() string {
	return TableNameJobRunShellIo
}
