// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package models

import (
	"time"

	"gorm.io/datatypes"
)

const TableNameJobRunStep = "job_run_steps"

// JobRunStep mapped from table <job_run_steps>
type JobRunStep struct {
	ID             *int64             `gorm:"column:id;type:INTEGER;primaryKey" json:"id"`
	RunID          int64              `gorm:"column:run_id;type:INTEGER;not null;index:idx_job_run_steps_run_status,priority:1;index:idx_job_run_steps_run_order,priority:1" json:"runId"`
	StepOrder      *int64             `gorm:"column:step_order;type:INTEGER;index:idx_job_run_steps_run_order,priority:2" json:"stepOrder"`
	StepName       *string            `gorm:"column:step_name;type:TEXT" json:"stepName"`
	StartedAt      *time.Time         `gorm:"column:started_at;type:TIMESTAMP" json:"startedAt"`
	FinishedAt     *time.Time         `gorm:"column:finished_at;type:TIMESTAMP" json:"finishedAt"`
	Status         string             `gorm:"column:status;type:TEXT;not null;index:idx_job_run_steps_run_status,priority:2" json:"status"`
	SqlText        *string            `gorm:"column:sql_text;type:TEXT" json:"sqlText"`
	TimeoutSeconds *int64             `gorm:"column:timeout_seconds;type:INTEGER" json:"timeoutSeconds"`
	CommandText    *string            `gorm:"column:command_text;type:TEXT" json:"commandText"`
	ScriptText     *string            `gorm:"column:script_text;type:TEXT" json:"scriptText"`
	ShellPath      *string            `gorm:"column:shell_path;type:TEXT" json:"shellPath"`
	WorkingDir     *string            `gorm:"column:working_dir;type:TEXT" json:"workingDir"`
	ExitCode       *int64             `gorm:"column:exit_code;type:INTEGER" json:"exitCode"`
	RowsCount      *int64             `gorm:"column:rows_count;type:INTEGER" json:"rowsCount"`
	RowsAffected   *int64             `gorm:"column:rows_affected;type:INTEGER" json:"rowsAffected"`
	Expectation    *datatypes.JSONMap `gorm:"column:expectation;type:JSONB" json:"expectation"`
	ExpectOk       *bool              `gorm:"column:expect_ok;type:BOOL" json:"expectOk"`
	ExpectMessage  *string            `gorm:"column:expect_message;type:TEXT" json:"expectMessage"`
	ErrorCode      *string            `gorm:"column:error_code;type:TEXT" json:"errorCode"`
	ErrorMessage   *string            `gorm:"column:error_message;type:TEXT" json:"errorMessage"`
	Details        *datatypes.JSONMap `gorm:"column:details;type:JSONB" json:"details"`
}

// TableName JobRunStep's table name
func (*JobRunStep) TableName() string {
	return TableNameJobRunStep
}
