// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package models

import (
	"time"

	"gorm.io/datatypes"
)

const TableNameJobRunEvent = "job_run_events"

// JobRunEvent mapped from table <job_run_events>
type JobRunEvent struct {
	ID        *int64             `gorm:"column:id;type:INTEGER;primaryKey" json:"id"`
	RunID     int64              `gorm:"column:run_id;type:INTEGER;not null;index:idx_job_run_events_run_time,priority:1" json:"runId"`
	StepID    *int64             `gorm:"column:step_id;type:INTEGER;index:idx_job_run_events_step_time,priority:1" json:"stepId"`
	CreatedAt *time.Time         `gorm:"column:created_at;type:TIMESTAMP;index:idx_job_run_events_step_time,priority:2;index:idx_job_run_events_run_time,priority:2" json:"createdAt"`
	Kind      *string            `gorm:"column:kind;type:TEXT" json:"kind"`
	Message   *string            `gorm:"column:message;type:TEXT" json:"message"`
	Data      *datatypes.JSONMap `gorm:"column:data;type:JSONB" json:"data"`
}

// TableName JobRunEvent's table name
func (*JobRunEvent) TableName() string {
	return TableNameJobRunEvent
}
