// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package models

import (
	"gorm.io/datatypes"
)

const TableNameJobRunWebtaskIo = "job_run_webtask_io"

// JobRunWebtaskIo mapped from table <job_run_webtask_io>
type JobRunWebtaskIo struct {
	ID              *int64             `gorm:"column:id;type:INTEGER;primaryKey" json:"id"`
	StepID          int64              `gorm:"column:step_id;type:INTEGER;not null;index:idx_job_run_webtask_io_step,priority:1" json:"stepId"`
	RequestURL      *string            `gorm:"column:request_url;type:TEXT" json:"requestUrl"`
	RequestMethod   *string            `gorm:"column:request_method;type:TEXT" json:"requestMethod"`
	RequestHeaders  *datatypes.JSONMap `gorm:"column:request_headers;type:JSONB" json:"requestHeaders"`
	RequestBody     *string            `gorm:"column:request_body;type:TEXT" json:"requestBody"`
	ResponseStatus  *int64             `gorm:"column:response_status;type:INTEGER" json:"responseStatus"`
	ResponseHeaders *datatypes.JSONMap `gorm:"column:response_headers;type:JSONB" json:"responseHeaders"`
	ResponseBody    *string            `gorm:"column:response_body;type:TEXT" json:"responseBody"`
	LatencyMs       *int64             `gorm:"column:latency_ms;type:INTEGER" json:"latencyMs"`
}

// TableName JobRunWebtaskIo's table name
func (*JobRunWebtaskIo) TableName() string {
	return TableNameJobRunWebtaskIo
}
