// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package models

import (
	"time"

	"gorm.io/datatypes"
)

const TableNameJob = "jobs"

// Job mapped from table <jobs>
type Job struct {
	ID                  *int64            `gorm:"column:id;type:INTEGER;primaryKey" json:"id"`
	Name                string            `gorm:"column:name;type:TEXT;not null" json:"name"`
	Description         *string           `gorm:"column:description;type:TEXT" json:"description"`
	Notes               *string           `gorm:"column:notes;type:TEXT" json:"notes"`
	ConnectionID        *int64            `gorm:"column:connection_id;type:INTEGER;index:idx_jobs_conn,priority:1" json:"connectionId"`
	ActionID            int64             `gorm:"column:action_id;type:INTEGER;not null;index:idx_jobs_action,priority:1" json:"actionId"`
	TargetKind          string            `gorm:"column:target_kind;type:TEXT;not null;index:idx_jobs_target_kind,priority:1" json:"targetKind"`
	ShellConnectionID   *int64            `gorm:"column:shell_connection_id;type:INTEGER;index:idx_jobs_shell_conn,priority:1" json:"shellConnectionId"`
	WebtaskConnectionID *int64            `gorm:"column:webtask_connection_id;type:INTEGER" json:"webtaskConnectionId"`
	ScheduleJSON        datatypes.JSONMap `gorm:"column:schedule_json;type:JSONB;not null" json:"scheduleJson"`
	Enabled             *bool             `gorm:"column:enabled;type:BOOL" json:"enabled"`
	Suspended           bool              `gorm:"column:suspended;type:BOOL;not null" json:"suspended"`
	AlertEmails         *string           `gorm:"column:alert_emails;type:TEXT" json:"alertEmails"`
	AlertPhones         *string           `gorm:"column:alert_phones;type:TEXT" json:"alertPhones"`
	NotifyOnSuccess     *bool             `gorm:"column:notify_on_success;type:BOOL" json:"notifyOnSuccess"`
	NotifyOnError       *bool             `gorm:"column:notify_on_error;type:BOOL" json:"notifyOnError"`
	NotifyIncludeOutput *bool             `gorm:"column:notify_include_output;type:BOOL" json:"notifyIncludeOutput"`
	CreatedAt           time.Time         `gorm:"column:created_at;type:TIMESTAMP;not null" json:"createdAt"`
	UpdatedAt           time.Time         `gorm:"column:updated_at;type:TIMESTAMP;not null" json:"updatedAt"`
}

// TableName Job's table name
func (*Job) TableName() string {
	return TableNameJob
}
