// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package models

import (
	"time"
)

const TableNameNotificationRecipient = "notification_recipients"

// NotificationRecipient mapped from table <notification_recipients>
type NotificationRecipient struct {
	NotificationID int64      `gorm:"column:notification_id;type:INTEGER;primaryKey" json:"notificationId"`
	UserID         int64      `gorm:"column:user_id;type:INTEGER;not null;index:idx_notification_recipients_user_seen,priority:1" json:"userId"`
	Seen           bool       `gorm:"column:seen;type:BOOL;not null;index:idx_notification_recipients_user_seen,priority:2" json:"seen"`
	SeenAt         *time.Time `gorm:"column:seen_at;type:TIMESTAMP" json:"seenAt"`
	RemovedAt      *time.Time `gorm:"column:removed_at;type:TIMESTAMP" json:"removedAt"`
	DeliveredAt    time.Time  `gorm:"column:delivered_at;type:TIMESTAMP;not null;index:idx_notification_recipients_user_seen,priority:3" json:"deliveredAt"`
}

// TableName NotificationRecipient's table name
func (*NotificationRecipient) TableName() string {
	return TableNameNotificationRecipient
}
