// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package models

import (
	"time"

	"gorm.io/datatypes"
)

const TableNameNotification = "notifications"

// Notification mapped from table <notifications>
type Notification struct {
	ID        *int64             `gorm:"column:id;type:INTEGER;primaryKey" json:"id"`
	CreatedAt time.Time          `gorm:"column:created_at;type:TIMESTAMP;not null" json:"createdAt"`
	Category  string             `gorm:"column:category;type:TEXT;not null" json:"category"`
	Severity  string             `gorm:"column:severity;type:TEXT;not null" json:"severity"`
	Subject   string             `gorm:"column:subject;type:TEXT;not null" json:"subject"`
	Origin    *string            `gorm:"column:origin;type:TEXT" json:"origin"`
	Data      *datatypes.JSONMap `gorm:"column:data;type:JSONB" json:"data"`
}

// TableName Notification's table name
func (*Notification) TableName() string {
	return TableNameNotification
}
