// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package models

import (
	"time"
)

const TableNameShellConnection = "shell_connections"

// ShellConnection mapped from table <shell_connections>
type ShellConnection struct {
	ID                       *int64     `gorm:"column:id;type:INTEGER;primaryKey" json:"id"`
	Name                     string     `gorm:"column:name;type:TEXT;not null" json:"name"`
	Description              *string    `gorm:"column:description;type:TEXT" json:"description"`
	AgentUUID                *string    `gorm:"column:agent_uuid;type:TEXT;index:idx_shell_connections_agent,priority:1" json:"agentUuid"`
	Mode                     string     `gorm:"column:mode;type:TEXT;not null;index:idx_shell_connections_mode,priority:1" json:"mode"`
	RunAsUser                *string    `gorm:"column:run_as_user;type:TEXT" json:"runAsUser"`
	Sudo                     *bool      `gorm:"column:sudo;type:BOOL" json:"sudo"`
	Host                     *string    `gorm:"column:host;type:TEXT" json:"host"`
	Port                     *int64     `gorm:"column:port;type:INTEGER" json:"port"`
	SSHUsername              *string    `gorm:"column:ssh_username;type:TEXT" json:"sshUsername"`
	AuthMethod               *string    `gorm:"column:auth_method;type:TEXT" json:"authMethod"`
	SSHPassword              *string    `gorm:"column:ssh_password;type:TEXT" json:"sshPassword"`
	SSHPrivateKey            *string    `gorm:"column:ssh_private_key;type:TEXT" json:"sshPrivateKey"`
	SSHKeyPass               *string    `gorm:"column:ssh_key_pass;type:TEXT" json:"sshKeyPass"`
	SudoPassword             *string    `gorm:"column:sudo_password;type:TEXT" json:"sudoPassword"`
	AutoCheckEnabled         *int64     `gorm:"column:auto_check_enabled;type:INTEGER" json:"autoCheckEnabled"`
	AutoCheckIntervalSeconds int64      `gorm:"column:auto_check_interval_seconds;type:INTEGER;not null" json:"autoCheckIntervalSeconds"`
	CreatedAt                time.Time  `gorm:"column:created_at;type:TIMESTAMP;not null" json:"createdAt"`
	UpdatedAt                time.Time  `gorm:"column:updated_at;type:TIMESTAMP;not null" json:"updatedAt"`
	LastStatus               *string    `gorm:"column:last_status;type:TEXT" json:"lastStatus"`
	LastError                *string    `gorm:"column:last_error;type:TEXT" json:"lastError"`
	LastCheckedAt            *time.Time `gorm:"column:last_checked_at;type:TIMESTAMP" json:"lastCheckedAt"`
	AlertEmails              *string    `gorm:"column:alert_emails;type:TEXT" json:"alertEmails"`
	AlertPhones              *string    `gorm:"column:alert_phones;type:TEXT" json:"alertPhones"`
	NotifyOnFailure          *bool      `gorm:"column:notify_on_failure;type:BOOL" json:"notifyOnFailure"`
	Enabled                  bool       `gorm:"column:enabled;type:BOOL;not null" json:"enabled"`
	Suspended                bool       `gorm:"column:suspended;type:BOOL;not null" json:"suspended"`
}

// TableName ShellConnection's table name
func (*ShellConnection) TableName() string {
	return TableNameShellConnection
}
