// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package models

import (
	"gorm.io/datatypes"
)

const TableNameShellActionStep = "shell_action_steps"

// ShellActionStep mapped from table <shell_action_steps>
type ShellActionStep struct {
	ID                    *int64             `gorm:"column:id;type:INTEGER;primaryKey" json:"id"`
	ActionID              int64              `gorm:"column:action_id;type:INTEGER;not null;uniqueIndex:uq_shell_action_steps_action_order,priority:1;index:idx_shell_action_steps_action,priority:1" json:"actionId"`
	StepOrder             *int64             `gorm:"column:step_order;type:INTEGER;uniqueIndex:uq_shell_action_steps_action_order,priority:2" json:"stepOrder"`
	Name                  string             `gorm:"column:name;type:TEXT;not null" json:"name"`
	RunMode               *string            `gorm:"column:run_mode;type:TEXT" json:"runMode"`
	Command               *string            `gorm:"column:command;type:TEXT" json:"command"`
	ScriptText            *string            `gorm:"column:script_text;type:TEXT" json:"scriptText"`
	ShellPath             *string            `gorm:"column:shell_path;type:TEXT" json:"shellPath"`
	WorkingDir            *string            `gorm:"column:working_dir;type:TEXT" json:"workingDir"`
	TimeoutSeconds        *int64             `gorm:"column:timeout_seconds;type:INTEGER" json:"timeoutSeconds"`
	EnvJSON               *datatypes.JSONMap `gorm:"column:env_json;type:JSONB" json:"envJson"`
	OutputCaptureMaxBytes *int64             `gorm:"column:output_capture_max_bytes;type:INTEGER" json:"outputCaptureMaxBytes"`
	OutputTruncation      *string            `gorm:"column:output_truncation;type:TEXT" json:"outputTruncation"`
	Expectation           *datatypes.JSONMap `gorm:"column:expectation;type:JSONB" json:"expectation"`
	OutputCapture         *datatypes.JSONMap `gorm:"column:output_capture;type:JSONB" json:"outputCapture"`
	OnFailure             *string            `gorm:"column:on_failure;type:TEXT" json:"onFailure"`
}

// TableName ShellActionStep's table name
func (*ShellActionStep) TableName() string {
	return TableNameShellActionStep
}
