// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package models

import (
	"time"
)

const TableNameUserActivity = "user_activity"

// UserActivity mapped from table <user_activity>
type UserActivity struct {
	ID        *int64    `gorm:"column:id;type:INTEGER;primaryKey" json:"id"`
	UserID    int64     `gorm:"column:user_id;type:INTEGER;not null;index:idx_user_activity_user_created,priority:1" json:"userId"`
	CreatedAt time.Time `gorm:"column:created_at;type:TIMESTAMP;not null;index:idx_user_activity_created,priority:1;index:idx_user_activity_user_created,priority:2" json:"createdAt"`
	Action    string    `gorm:"column:action;type:TEXT;not null" json:"action"`
	Details   *string   `gorm:"column:details;type:TEXT" json:"details"`
	IP        *string   `gorm:"column:ip;type:TEXT" json:"ip"`
	UserAgent *string   `gorm:"column:user_agent;type:TEXT" json:"userAgent"`
}

// TableName UserActivity's table name
func (*UserActivity) TableName() string {
	return TableNameUserActivity
}
