// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package models

import (
	"time"
)

const TableNameWebhook = "webhooks"

// Webhook mapped from table <webhooks>
type Webhook struct {
	ID        *int64    `gorm:"column:id;type:INTEGER;primaryKey" json:"id"`
	Name      string    `gorm:"column:name;type:TEXT;not null" json:"name"`
	URL       string    `gorm:"column:url;type:TEXT;not null" json:"url"`
	Secret    *string   `gorm:"column:secret;type:TEXT" json:"secret"`
	Events    string    `gorm:"column:events;type:TEXT;not null" json:"events"`
	Enabled   *bool     `gorm:"column:enabled;type:BOOL" json:"enabled"`
	CreatedAt time.Time `gorm:"column:created_at;type:TIMESTAMP;not null" json:"createdAt"`
	UpdatedAt time.Time `gorm:"column:updated_at;type:TIMESTAMP;not null" json:"updatedAt"`
}

// TableName Webhook's table name
func (*Webhook) TableName() string {
	return TableNameWebhook
}
