// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package models

import (
	"gorm.io/datatypes"
)

const TableNameWebtaskActionStep = "webtask_action_steps"

// WebtaskActionStep mapped from table <webtask_action_steps>
type WebtaskActionStep struct {
	ID              *int64             `gorm:"column:id;type:INTEGER;primaryKey" json:"id"`
	ActionID        int64              `gorm:"column:action_id;type:INTEGER;not null;uniqueIndex:uq_webtask_action_steps_action_order,priority:1" json:"actionId"`
	StepOrder       *int64             `gorm:"column:step_order;type:INTEGER;uniqueIndex:uq_webtask_action_steps_action_order,priority:2" json:"stepOrder"`
	Name            string             `gorm:"column:name;type:TEXT;not null" json:"name"`
	Method          string             `gorm:"column:method;type:TEXT;not null" json:"method"`
	URL             string             `gorm:"column:url;type:TEXT;not null" json:"url"`
	Headers         *datatypes.JSONMap `gorm:"column:headers;type:JSONB" json:"headers"`
	Body            *string            `gorm:"column:body;type:TEXT" json:"body"`
	TimeoutSeconds  *int64             `gorm:"column:timeout_seconds;type:INTEGER" json:"timeoutSeconds"`
	Expectation     *datatypes.JSONMap `gorm:"column:expectation;type:JSONB" json:"expectation"`
	ResponseCapture *datatypes.JSONMap `gorm:"column:response_capture;type:JSONB" json:"responseCapture"`
	OnFailure       *string            `gorm:"column:on_failure;type:TEXT" json:"onFailure"`
}

// TableName WebtaskActionStep's table name
func (*WebtaskActionStep) TableName() string {
	return TableNameWebtaskActionStep
}
