// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package db

import (
	"context"
	"database/sql"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"chronix/internal/db/models"
)

func newActionStep(db *gorm.DB, opts ...gen.DOOption) actionStep {
	_actionStep := actionStep{}

	_actionStep.actionStepDo.UseDB(db, opts...)
	_actionStep.actionStepDo.UseModel(&models.ActionStep{})

	tableName := _actionStep.actionStepDo.TableName()
	_actionStep.ALL = field.NewAsterisk(tableName)
	_actionStep.ID = field.NewInt64(tableName, "id")
	_actionStep.ActionID = field.NewInt64(tableName, "action_id")
	_actionStep.StepOrder = field.NewInt64(tableName, "step_order")
	_actionStep.Name = field.NewString(tableName, "name")
	_actionStep.SqlText = field.NewString(tableName, "sql_text")
	_actionStep.TimeoutSeconds = field.NewInt64(tableName, "timeout_seconds")
	_actionStep.Expectation = field.NewField(tableName, "expectation")
	_actionStep.OutputCapture = field.NewField(tableName, "output_capture")
	_actionStep.OnFailure = field.NewString(tableName, "on_failure")

	_actionStep.fillFieldMap()

	return _actionStep
}

type actionStep struct {
	actionStepDo

	ALL            field.Asterisk
	ID             field.Int64
	ActionID       field.Int64
	StepOrder      field.Int64
	Name           field.String
	SqlText        field.String
	TimeoutSeconds field.Int64
	Expectation    field.Field
	OutputCapture  field.Field
	OnFailure      field.String

	fieldMap map[string]field.Expr
}

func (a actionStep) Table(newTableName string) *actionStep {
	a.actionStepDo.UseTable(newTableName)
	return a.updateTableName(newTableName)
}

func (a actionStep) As(alias string) *actionStep {
	a.actionStepDo.DO = *(a.actionStepDo.As(alias).(*gen.DO))
	return a.updateTableName(alias)
}

func (a *actionStep) updateTableName(table string) *actionStep {
	a.ALL = field.NewAsterisk(table)
	a.ID = field.NewInt64(table, "id")
	a.ActionID = field.NewInt64(table, "action_id")
	a.StepOrder = field.NewInt64(table, "step_order")
	a.Name = field.NewString(table, "name")
	a.SqlText = field.NewString(table, "sql_text")
	a.TimeoutSeconds = field.NewInt64(table, "timeout_seconds")
	a.Expectation = field.NewField(table, "expectation")
	a.OutputCapture = field.NewField(table, "output_capture")
	a.OnFailure = field.NewString(table, "on_failure")

	a.fillFieldMap()

	return a
}

func (a *actionStep) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := a.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (a *actionStep) fillFieldMap() {
	a.fieldMap = make(map[string]field.Expr, 9)
	a.fieldMap["id"] = a.ID
	a.fieldMap["action_id"] = a.ActionID
	a.fieldMap["step_order"] = a.StepOrder
	a.fieldMap["name"] = a.Name
	a.fieldMap["sql_text"] = a.SqlText
	a.fieldMap["timeout_seconds"] = a.TimeoutSeconds
	a.fieldMap["expectation"] = a.Expectation
	a.fieldMap["output_capture"] = a.OutputCapture
	a.fieldMap["on_failure"] = a.OnFailure
}

func (a actionStep) clone(db *gorm.DB) actionStep {
	a.actionStepDo.ReplaceConnPool(db.Statement.ConnPool)
	return a
}

func (a actionStep) replaceDB(db *gorm.DB) actionStep {
	a.actionStepDo.ReplaceDB(db)
	return a
}

type actionStepDo struct{ gen.DO }

type IActionStepDo interface {
	gen.SubQuery
	Debug() IActionStepDo
	WithContext(ctx context.Context) IActionStepDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() IActionStepDo
	WriteDB() IActionStepDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) IActionStepDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) IActionStepDo
	Not(conds ...gen.Condition) IActionStepDo
	Or(conds ...gen.Condition) IActionStepDo
	Select(conds ...field.Expr) IActionStepDo
	Where(conds ...gen.Condition) IActionStepDo
	Order(conds ...field.Expr) IActionStepDo
	Distinct(cols ...field.Expr) IActionStepDo
	Omit(cols ...field.Expr) IActionStepDo
	Join(table schema.Tabler, on ...field.Expr) IActionStepDo
	LeftJoin(table schema.Tabler, on ...field.Expr) IActionStepDo
	RightJoin(table schema.Tabler, on ...field.Expr) IActionStepDo
	Group(cols ...field.Expr) IActionStepDo
	Having(conds ...gen.Condition) IActionStepDo
	Limit(limit int) IActionStepDo
	Offset(offset int) IActionStepDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) IActionStepDo
	Unscoped() IActionStepDo
	Create(values ...*models.ActionStep) error
	CreateInBatches(values []*models.ActionStep, batchSize int) error
	Save(values ...*models.ActionStep) error
	First() (*models.ActionStep, error)
	Take() (*models.ActionStep, error)
	Last() (*models.ActionStep, error)
	Find() ([]*models.ActionStep, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*models.ActionStep, err error)
	FindInBatches(result *[]*models.ActionStep, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*models.ActionStep) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) IActionStepDo
	Assign(attrs ...field.AssignExpr) IActionStepDo
	Joins(fields ...field.RelationField) IActionStepDo
	Preload(fields ...field.RelationField) IActionStepDo
	FirstOrInit() (*models.ActionStep, error)
	FirstOrCreate() (*models.ActionStep, error)
	FindByPage(offset int, limit int) (result []*models.ActionStep, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Rows() (*sql.Rows, error)
	Row() *sql.Row
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) IActionStepDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (a actionStepDo) Debug() IActionStepDo {
	return a.withDO(a.DO.Debug())
}

func (a actionStepDo) WithContext(ctx context.Context) IActionStepDo {
	return a.withDO(a.DO.WithContext(ctx))
}

func (a actionStepDo) ReadDB() IActionStepDo {
	return a.Clauses(dbresolver.Read)
}

func (a actionStepDo) WriteDB() IActionStepDo {
	return a.Clauses(dbresolver.Write)
}

func (a actionStepDo) Session(config *gorm.Session) IActionStepDo {
	return a.withDO(a.DO.Session(config))
}

func (a actionStepDo) Clauses(conds ...clause.Expression) IActionStepDo {
	return a.withDO(a.DO.Clauses(conds...))
}

func (a actionStepDo) Returning(value interface{}, columns ...string) IActionStepDo {
	return a.withDO(a.DO.Returning(value, columns...))
}

func (a actionStepDo) Not(conds ...gen.Condition) IActionStepDo {
	return a.withDO(a.DO.Not(conds...))
}

func (a actionStepDo) Or(conds ...gen.Condition) IActionStepDo {
	return a.withDO(a.DO.Or(conds...))
}

func (a actionStepDo) Select(conds ...field.Expr) IActionStepDo {
	return a.withDO(a.DO.Select(conds...))
}

func (a actionStepDo) Where(conds ...gen.Condition) IActionStepDo {
	return a.withDO(a.DO.Where(conds...))
}

func (a actionStepDo) Order(conds ...field.Expr) IActionStepDo {
	return a.withDO(a.DO.Order(conds...))
}

func (a actionStepDo) Distinct(cols ...field.Expr) IActionStepDo {
	return a.withDO(a.DO.Distinct(cols...))
}

func (a actionStepDo) Omit(cols ...field.Expr) IActionStepDo {
	return a.withDO(a.DO.Omit(cols...))
}

func (a actionStepDo) Join(table schema.Tabler, on ...field.Expr) IActionStepDo {
	return a.withDO(a.DO.Join(table, on...))
}

func (a actionStepDo) LeftJoin(table schema.Tabler, on ...field.Expr) IActionStepDo {
	return a.withDO(a.DO.LeftJoin(table, on...))
}

func (a actionStepDo) RightJoin(table schema.Tabler, on ...field.Expr) IActionStepDo {
	return a.withDO(a.DO.RightJoin(table, on...))
}

func (a actionStepDo) Group(cols ...field.Expr) IActionStepDo {
	return a.withDO(a.DO.Group(cols...))
}

func (a actionStepDo) Having(conds ...gen.Condition) IActionStepDo {
	return a.withDO(a.DO.Having(conds...))
}

func (a actionStepDo) Limit(limit int) IActionStepDo {
	return a.withDO(a.DO.Limit(limit))
}

func (a actionStepDo) Offset(offset int) IActionStepDo {
	return a.withDO(a.DO.Offset(offset))
}

func (a actionStepDo) Scopes(funcs ...func(gen.Dao) gen.Dao) IActionStepDo {
	return a.withDO(a.DO.Scopes(funcs...))
}

func (a actionStepDo) Unscoped() IActionStepDo {
	return a.withDO(a.DO.Unscoped())
}

func (a actionStepDo) Create(values ...*models.ActionStep) error {
	if len(values) == 0 {
		return nil
	}
	return a.DO.Create(values)
}

func (a actionStepDo) CreateInBatches(values []*models.ActionStep, batchSize int) error {
	return a.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (a actionStepDo) Save(values ...*models.ActionStep) error {
	if len(values) == 0 {
		return nil
	}
	return a.DO.Save(values)
}

func (a actionStepDo) First() (*models.ActionStep, error) {
	if result, err := a.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*models.ActionStep), nil
	}
}

func (a actionStepDo) Take() (*models.ActionStep, error) {
	if result, err := a.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*models.ActionStep), nil
	}
}

func (a actionStepDo) Last() (*models.ActionStep, error) {
	if result, err := a.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*models.ActionStep), nil
	}
}

func (a actionStepDo) Find() ([]*models.ActionStep, error) {
	result, err := a.DO.Find()
	return result.([]*models.ActionStep), err
}

func (a actionStepDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*models.ActionStep, err error) {
	buf := make([]*models.ActionStep, 0, batchSize)
	err = a.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (a actionStepDo) FindInBatches(result *[]*models.ActionStep, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return a.DO.FindInBatches(result, batchSize, fc)
}

func (a actionStepDo) Attrs(attrs ...field.AssignExpr) IActionStepDo {
	return a.withDO(a.DO.Attrs(attrs...))
}

func (a actionStepDo) Assign(attrs ...field.AssignExpr) IActionStepDo {
	return a.withDO(a.DO.Assign(attrs...))
}

func (a actionStepDo) Joins(fields ...field.RelationField) IActionStepDo {
	for _, _f := range fields {
		a = *a.withDO(a.DO.Joins(_f))
	}
	return &a
}

func (a actionStepDo) Preload(fields ...field.RelationField) IActionStepDo {
	for _, _f := range fields {
		a = *a.withDO(a.DO.Preload(_f))
	}
	return &a
}

func (a actionStepDo) FirstOrInit() (*models.ActionStep, error) {
	if result, err := a.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*models.ActionStep), nil
	}
}

func (a actionStepDo) FirstOrCreate() (*models.ActionStep, error) {
	if result, err := a.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*models.ActionStep), nil
	}
}

func (a actionStepDo) FindByPage(offset int, limit int) (result []*models.ActionStep, count int64, err error) {
	result, err = a.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = a.Offset(-1).Limit(-1).Count()
	return
}

func (a actionStepDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = a.Count()
	if err != nil {
		return
	}

	err = a.Offset(offset).Limit(limit).Scan(result)
	return
}

func (a actionStepDo) Scan(result interface{}) (err error) {
	return a.DO.Scan(result)
}

func (a actionStepDo) Delete(models ...*models.ActionStep) (result gen.ResultInfo, err error) {
	return a.DO.Delete(models)
}

func (a *actionStepDo) withDO(do gen.Dao) *actionStepDo {
	a.DO = *do.(*gen.DO)
	return a
}
