// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package db

import (
	"context"
	"database/sql"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"chronix/internal/db/models"
)

func newAction(db *gorm.DB, opts ...gen.DOOption) action {
	_action := action{}

	_action.actionDo.UseDB(db, opts...)
	_action.actionDo.UseModel(&models.Action{})

	tableName := _action.actionDo.TableName()
	_action.ALL = field.NewAsterisk(tableName)
	_action.ID = field.NewInt64(tableName, "id")
	_action.Name = field.NewString(tableName, "name")
	_action.Dialect = field.NewString(tableName, "dialect")
	_action.Description = field.NewString(tableName, "description")
	_action.Notes = field.NewString(tableName, "notes")
	_action.ActionType = field.NewString(tableName, "action_type")
	_action.Enabled = field.NewBool(tableName, "enabled")
	_action.Suspended = field.NewBool(tableName, "suspended")
	_action.CreatedAt = field.NewTime(tableName, "created_at")
	_action.UpdatedAt = field.NewTime(tableName, "updated_at")

	_action.fillFieldMap()

	return _action
}

type action struct {
	actionDo

	ALL         field.Asterisk
	ID          field.Int64
	Name        field.String
	Dialect     field.String
	Description field.String
	Notes       field.String
	ActionType  field.String
	Enabled     field.Bool
	Suspended   field.Bool
	CreatedAt   field.Time
	UpdatedAt   field.Time

	fieldMap map[string]field.Expr
}

func (a action) Table(newTableName string) *action {
	a.actionDo.UseTable(newTableName)
	return a.updateTableName(newTableName)
}

func (a action) As(alias string) *action {
	a.actionDo.DO = *(a.actionDo.As(alias).(*gen.DO))
	return a.updateTableName(alias)
}

func (a *action) updateTableName(table string) *action {
	a.ALL = field.NewAsterisk(table)
	a.ID = field.NewInt64(table, "id")
	a.Name = field.NewString(table, "name")
	a.Dialect = field.NewString(table, "dialect")
	a.Description = field.NewString(table, "description")
	a.Notes = field.NewString(table, "notes")
	a.ActionType = field.NewString(table, "action_type")
	a.Enabled = field.NewBool(table, "enabled")
	a.Suspended = field.NewBool(table, "suspended")
	a.CreatedAt = field.NewTime(table, "created_at")
	a.UpdatedAt = field.NewTime(table, "updated_at")

	a.fillFieldMap()

	return a
}

func (a *action) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := a.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (a *action) fillFieldMap() {
	a.fieldMap = make(map[string]field.Expr, 10)
	a.fieldMap["id"] = a.ID
	a.fieldMap["name"] = a.Name
	a.fieldMap["dialect"] = a.Dialect
	a.fieldMap["description"] = a.Description
	a.fieldMap["notes"] = a.Notes
	a.fieldMap["action_type"] = a.ActionType
	a.fieldMap["enabled"] = a.Enabled
	a.fieldMap["suspended"] = a.Suspended
	a.fieldMap["created_at"] = a.CreatedAt
	a.fieldMap["updated_at"] = a.UpdatedAt
}

func (a action) clone(db *gorm.DB) action {
	a.actionDo.ReplaceConnPool(db.Statement.ConnPool)
	return a
}

func (a action) replaceDB(db *gorm.DB) action {
	a.actionDo.ReplaceDB(db)
	return a
}

type actionDo struct{ gen.DO }

type IActionDo interface {
	gen.SubQuery
	Debug() IActionDo
	WithContext(ctx context.Context) IActionDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() IActionDo
	WriteDB() IActionDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) IActionDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) IActionDo
	Not(conds ...gen.Condition) IActionDo
	Or(conds ...gen.Condition) IActionDo
	Select(conds ...field.Expr) IActionDo
	Where(conds ...gen.Condition) IActionDo
	Order(conds ...field.Expr) IActionDo
	Distinct(cols ...field.Expr) IActionDo
	Omit(cols ...field.Expr) IActionDo
	Join(table schema.Tabler, on ...field.Expr) IActionDo
	LeftJoin(table schema.Tabler, on ...field.Expr) IActionDo
	RightJoin(table schema.Tabler, on ...field.Expr) IActionDo
	Group(cols ...field.Expr) IActionDo
	Having(conds ...gen.Condition) IActionDo
	Limit(limit int) IActionDo
	Offset(offset int) IActionDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) IActionDo
	Unscoped() IActionDo
	Create(values ...*models.Action) error
	CreateInBatches(values []*models.Action, batchSize int) error
	Save(values ...*models.Action) error
	First() (*models.Action, error)
	Take() (*models.Action, error)
	Last() (*models.Action, error)
	Find() ([]*models.Action, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*models.Action, err error)
	FindInBatches(result *[]*models.Action, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*models.Action) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) IActionDo
	Assign(attrs ...field.AssignExpr) IActionDo
	Joins(fields ...field.RelationField) IActionDo
	Preload(fields ...field.RelationField) IActionDo
	FirstOrInit() (*models.Action, error)
	FirstOrCreate() (*models.Action, error)
	FindByPage(offset int, limit int) (result []*models.Action, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Rows() (*sql.Rows, error)
	Row() *sql.Row
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) IActionDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (a actionDo) Debug() IActionDo {
	return a.withDO(a.DO.Debug())
}

func (a actionDo) WithContext(ctx context.Context) IActionDo {
	return a.withDO(a.DO.WithContext(ctx))
}

func (a actionDo) ReadDB() IActionDo {
	return a.Clauses(dbresolver.Read)
}

func (a actionDo) WriteDB() IActionDo {
	return a.Clauses(dbresolver.Write)
}

func (a actionDo) Session(config *gorm.Session) IActionDo {
	return a.withDO(a.DO.Session(config))
}

func (a actionDo) Clauses(conds ...clause.Expression) IActionDo {
	return a.withDO(a.DO.Clauses(conds...))
}

func (a actionDo) Returning(value interface{}, columns ...string) IActionDo {
	return a.withDO(a.DO.Returning(value, columns...))
}

func (a actionDo) Not(conds ...gen.Condition) IActionDo {
	return a.withDO(a.DO.Not(conds...))
}

func (a actionDo) Or(conds ...gen.Condition) IActionDo {
	return a.withDO(a.DO.Or(conds...))
}

func (a actionDo) Select(conds ...field.Expr) IActionDo {
	return a.withDO(a.DO.Select(conds...))
}

func (a actionDo) Where(conds ...gen.Condition) IActionDo {
	return a.withDO(a.DO.Where(conds...))
}

func (a actionDo) Order(conds ...field.Expr) IActionDo {
	return a.withDO(a.DO.Order(conds...))
}

func (a actionDo) Distinct(cols ...field.Expr) IActionDo {
	return a.withDO(a.DO.Distinct(cols...))
}

func (a actionDo) Omit(cols ...field.Expr) IActionDo {
	return a.withDO(a.DO.Omit(cols...))
}

func (a actionDo) Join(table schema.Tabler, on ...field.Expr) IActionDo {
	return a.withDO(a.DO.Join(table, on...))
}

func (a actionDo) LeftJoin(table schema.Tabler, on ...field.Expr) IActionDo {
	return a.withDO(a.DO.LeftJoin(table, on...))
}

func (a actionDo) RightJoin(table schema.Tabler, on ...field.Expr) IActionDo {
	return a.withDO(a.DO.RightJoin(table, on...))
}

func (a actionDo) Group(cols ...field.Expr) IActionDo {
	return a.withDO(a.DO.Group(cols...))
}

func (a actionDo) Having(conds ...gen.Condition) IActionDo {
	return a.withDO(a.DO.Having(conds...))
}

func (a actionDo) Limit(limit int) IActionDo {
	return a.withDO(a.DO.Limit(limit))
}

func (a actionDo) Offset(offset int) IActionDo {
	return a.withDO(a.DO.Offset(offset))
}

func (a actionDo) Scopes(funcs ...func(gen.Dao) gen.Dao) IActionDo {
	return a.withDO(a.DO.Scopes(funcs...))
}

func (a actionDo) Unscoped() IActionDo {
	return a.withDO(a.DO.Unscoped())
}

func (a actionDo) Create(values ...*models.Action) error {
	if len(values) == 0 {
		return nil
	}
	return a.DO.Create(values)
}

func (a actionDo) CreateInBatches(values []*models.Action, batchSize int) error {
	return a.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (a actionDo) Save(values ...*models.Action) error {
	if len(values) == 0 {
		return nil
	}
	return a.DO.Save(values)
}

func (a actionDo) First() (*models.Action, error) {
	if result, err := a.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*models.Action), nil
	}
}

func (a actionDo) Take() (*models.Action, error) {
	if result, err := a.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*models.Action), nil
	}
}

func (a actionDo) Last() (*models.Action, error) {
	if result, err := a.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*models.Action), nil
	}
}

func (a actionDo) Find() ([]*models.Action, error) {
	result, err := a.DO.Find()
	return result.([]*models.Action), err
}

func (a actionDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*models.Action, err error) {
	buf := make([]*models.Action, 0, batchSize)
	err = a.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (a actionDo) FindInBatches(result *[]*models.Action, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return a.DO.FindInBatches(result, batchSize, fc)
}

func (a actionDo) Attrs(attrs ...field.AssignExpr) IActionDo {
	return a.withDO(a.DO.Attrs(attrs...))
}

func (a actionDo) Assign(attrs ...field.AssignExpr) IActionDo {
	return a.withDO(a.DO.Assign(attrs...))
}

func (a actionDo) Joins(fields ...field.RelationField) IActionDo {
	for _, _f := range fields {
		a = *a.withDO(a.DO.Joins(_f))
	}
	return &a
}

func (a actionDo) Preload(fields ...field.RelationField) IActionDo {
	for _, _f := range fields {
		a = *a.withDO(a.DO.Preload(_f))
	}
	return &a
}

func (a actionDo) FirstOrInit() (*models.Action, error) {
	if result, err := a.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*models.Action), nil
	}
}

func (a actionDo) FirstOrCreate() (*models.Action, error) {
	if result, err := a.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*models.Action), nil
	}
}

func (a actionDo) FindByPage(offset int, limit int) (result []*models.Action, count int64, err error) {
	result, err = a.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = a.Offset(-1).Limit(-1).Count()
	return
}

func (a actionDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = a.Count()
	if err != nil {
		return
	}

	err = a.Offset(offset).Limit(limit).Scan(result)
	return
}

func (a actionDo) Scan(result interface{}) (err error) {
	return a.DO.Scan(result)
}

func (a actionDo) Delete(models ...*models.Action) (result gen.ResultInfo, err error) {
	return a.DO.Delete(models)
}

func (a *actionDo) withDO(do gen.Dao) *actionDo {
	a.DO = *do.(*gen.DO)
	return a
}
