// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package db

import (
	"context"
	"database/sql"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"chronix/internal/db/models"
)

func newAgentRegistrationRequest(db *gorm.DB, opts ...gen.DOOption) agentRegistrationRequest {
	_agentRegistrationRequest := agentRegistrationRequest{}

	_agentRegistrationRequest.agentRegistrationRequestDo.UseDB(db, opts...)
	_agentRegistrationRequest.agentRegistrationRequestDo.UseModel(&models.AgentRegistrationRequest{})

	tableName := _agentRegistrationRequest.agentRegistrationRequestDo.TableName()
	_agentRegistrationRequest.ALL = field.NewAsterisk(tableName)
	_agentRegistrationRequest.RequestID = field.NewString(tableName, "request_id")
	_agentRegistrationRequest.UUID = field.NewString(tableName, "uuid")
	_agentRegistrationRequest.Name = field.NewString(tableName, "name")
	_agentRegistrationRequest.PublicKey = field.NewString(tableName, "public_key")
	_agentRegistrationRequest.Version = field.NewString(tableName, "version")
	_agentRegistrationRequest.Os = field.NewString(tableName, "os")
	_agentRegistrationRequest.Arch = field.NewString(tableName, "arch")
	_agentRegistrationRequest.OsVersion = field.NewString(tableName, "os_version")
	_agentRegistrationRequest.OsType = field.NewString(tableName, "os_type")
	_agentRegistrationRequest.RunningUser = field.NewString(tableName, "running_user")
	_agentRegistrationRequest.IP = field.NewString(tableName, "ip")
	_agentRegistrationRequest.MetadataJSON = field.NewField(tableName, "metadata_json")
	_agentRegistrationRequest.Status = field.NewString(tableName, "status")
	_agentRegistrationRequest.CreatedAt = field.NewTime(tableName, "created_at")
	_agentRegistrationRequest.ExpiresAt = field.NewTime(tableName, "expires_at")
	_agentRegistrationRequest.ApprovedByUserID = field.NewInt64(tableName, "approved_by_user_id")
	_agentRegistrationRequest.ApprovedAt = field.NewTime(tableName, "approved_at")
	_agentRegistrationRequest.ConsumedAt = field.NewTime(tableName, "consumed_at")

	_agentRegistrationRequest.fillFieldMap()

	return _agentRegistrationRequest
}

type agentRegistrationRequest struct {
	agentRegistrationRequestDo

	ALL              field.Asterisk
	RequestID        field.String
	UUID             field.String
	Name             field.String
	PublicKey        field.String
	Version          field.String
	Os               field.String
	Arch             field.String
	OsVersion        field.String
	OsType           field.String
	RunningUser      field.String
	IP               field.String
	MetadataJSON     field.Field
	Status           field.String
	CreatedAt        field.Time
	ExpiresAt        field.Time
	ApprovedByUserID field.Int64
	ApprovedAt       field.Time
	ConsumedAt       field.Time

	fieldMap map[string]field.Expr
}

func (a agentRegistrationRequest) Table(newTableName string) *agentRegistrationRequest {
	a.agentRegistrationRequestDo.UseTable(newTableName)
	return a.updateTableName(newTableName)
}

func (a agentRegistrationRequest) As(alias string) *agentRegistrationRequest {
	a.agentRegistrationRequestDo.DO = *(a.agentRegistrationRequestDo.As(alias).(*gen.DO))
	return a.updateTableName(alias)
}

func (a *agentRegistrationRequest) updateTableName(table string) *agentRegistrationRequest {
	a.ALL = field.NewAsterisk(table)
	a.RequestID = field.NewString(table, "request_id")
	a.UUID = field.NewString(table, "uuid")
	a.Name = field.NewString(table, "name")
	a.PublicKey = field.NewString(table, "public_key")
	a.Version = field.NewString(table, "version")
	a.Os = field.NewString(table, "os")
	a.Arch = field.NewString(table, "arch")
	a.OsVersion = field.NewString(table, "os_version")
	a.OsType = field.NewString(table, "os_type")
	a.RunningUser = field.NewString(table, "running_user")
	a.IP = field.NewString(table, "ip")
	a.MetadataJSON = field.NewField(table, "metadata_json")
	a.Status = field.NewString(table, "status")
	a.CreatedAt = field.NewTime(table, "created_at")
	a.ExpiresAt = field.NewTime(table, "expires_at")
	a.ApprovedByUserID = field.NewInt64(table, "approved_by_user_id")
	a.ApprovedAt = field.NewTime(table, "approved_at")
	a.ConsumedAt = field.NewTime(table, "consumed_at")

	a.fillFieldMap()

	return a
}

func (a *agentRegistrationRequest) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := a.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (a *agentRegistrationRequest) fillFieldMap() {
	a.fieldMap = make(map[string]field.Expr, 18)
	a.fieldMap["request_id"] = a.RequestID
	a.fieldMap["uuid"] = a.UUID
	a.fieldMap["name"] = a.Name
	a.fieldMap["public_key"] = a.PublicKey
	a.fieldMap["version"] = a.Version
	a.fieldMap["os"] = a.Os
	a.fieldMap["arch"] = a.Arch
	a.fieldMap["os_version"] = a.OsVersion
	a.fieldMap["os_type"] = a.OsType
	a.fieldMap["running_user"] = a.RunningUser
	a.fieldMap["ip"] = a.IP
	a.fieldMap["metadata_json"] = a.MetadataJSON
	a.fieldMap["status"] = a.Status
	a.fieldMap["created_at"] = a.CreatedAt
	a.fieldMap["expires_at"] = a.ExpiresAt
	a.fieldMap["approved_by_user_id"] = a.ApprovedByUserID
	a.fieldMap["approved_at"] = a.ApprovedAt
	a.fieldMap["consumed_at"] = a.ConsumedAt
}

func (a agentRegistrationRequest) clone(db *gorm.DB) agentRegistrationRequest {
	a.agentRegistrationRequestDo.ReplaceConnPool(db.Statement.ConnPool)
	return a
}

func (a agentRegistrationRequest) replaceDB(db *gorm.DB) agentRegistrationRequest {
	a.agentRegistrationRequestDo.ReplaceDB(db)
	return a
}

type agentRegistrationRequestDo struct{ gen.DO }

type IAgentRegistrationRequestDo interface {
	gen.SubQuery
	Debug() IAgentRegistrationRequestDo
	WithContext(ctx context.Context) IAgentRegistrationRequestDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() IAgentRegistrationRequestDo
	WriteDB() IAgentRegistrationRequestDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) IAgentRegistrationRequestDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) IAgentRegistrationRequestDo
	Not(conds ...gen.Condition) IAgentRegistrationRequestDo
	Or(conds ...gen.Condition) IAgentRegistrationRequestDo
	Select(conds ...field.Expr) IAgentRegistrationRequestDo
	Where(conds ...gen.Condition) IAgentRegistrationRequestDo
	Order(conds ...field.Expr) IAgentRegistrationRequestDo
	Distinct(cols ...field.Expr) IAgentRegistrationRequestDo
	Omit(cols ...field.Expr) IAgentRegistrationRequestDo
	Join(table schema.Tabler, on ...field.Expr) IAgentRegistrationRequestDo
	LeftJoin(table schema.Tabler, on ...field.Expr) IAgentRegistrationRequestDo
	RightJoin(table schema.Tabler, on ...field.Expr) IAgentRegistrationRequestDo
	Group(cols ...field.Expr) IAgentRegistrationRequestDo
	Having(conds ...gen.Condition) IAgentRegistrationRequestDo
	Limit(limit int) IAgentRegistrationRequestDo
	Offset(offset int) IAgentRegistrationRequestDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) IAgentRegistrationRequestDo
	Unscoped() IAgentRegistrationRequestDo
	Create(values ...*models.AgentRegistrationRequest) error
	CreateInBatches(values []*models.AgentRegistrationRequest, batchSize int) error
	Save(values ...*models.AgentRegistrationRequest) error
	First() (*models.AgentRegistrationRequest, error)
	Take() (*models.AgentRegistrationRequest, error)
	Last() (*models.AgentRegistrationRequest, error)
	Find() ([]*models.AgentRegistrationRequest, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*models.AgentRegistrationRequest, err error)
	FindInBatches(result *[]*models.AgentRegistrationRequest, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*models.AgentRegistrationRequest) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) IAgentRegistrationRequestDo
	Assign(attrs ...field.AssignExpr) IAgentRegistrationRequestDo
	Joins(fields ...field.RelationField) IAgentRegistrationRequestDo
	Preload(fields ...field.RelationField) IAgentRegistrationRequestDo
	FirstOrInit() (*models.AgentRegistrationRequest, error)
	FirstOrCreate() (*models.AgentRegistrationRequest, error)
	FindByPage(offset int, limit int) (result []*models.AgentRegistrationRequest, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Rows() (*sql.Rows, error)
	Row() *sql.Row
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) IAgentRegistrationRequestDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (a agentRegistrationRequestDo) Debug() IAgentRegistrationRequestDo {
	return a.withDO(a.DO.Debug())
}

func (a agentRegistrationRequestDo) WithContext(ctx context.Context) IAgentRegistrationRequestDo {
	return a.withDO(a.DO.WithContext(ctx))
}

func (a agentRegistrationRequestDo) ReadDB() IAgentRegistrationRequestDo {
	return a.Clauses(dbresolver.Read)
}

func (a agentRegistrationRequestDo) WriteDB() IAgentRegistrationRequestDo {
	return a.Clauses(dbresolver.Write)
}

func (a agentRegistrationRequestDo) Session(config *gorm.Session) IAgentRegistrationRequestDo {
	return a.withDO(a.DO.Session(config))
}

func (a agentRegistrationRequestDo) Clauses(conds ...clause.Expression) IAgentRegistrationRequestDo {
	return a.withDO(a.DO.Clauses(conds...))
}

func (a agentRegistrationRequestDo) Returning(value interface{}, columns ...string) IAgentRegistrationRequestDo {
	return a.withDO(a.DO.Returning(value, columns...))
}

func (a agentRegistrationRequestDo) Not(conds ...gen.Condition) IAgentRegistrationRequestDo {
	return a.withDO(a.DO.Not(conds...))
}

func (a agentRegistrationRequestDo) Or(conds ...gen.Condition) IAgentRegistrationRequestDo {
	return a.withDO(a.DO.Or(conds...))
}

func (a agentRegistrationRequestDo) Select(conds ...field.Expr) IAgentRegistrationRequestDo {
	return a.withDO(a.DO.Select(conds...))
}

func (a agentRegistrationRequestDo) Where(conds ...gen.Condition) IAgentRegistrationRequestDo {
	return a.withDO(a.DO.Where(conds...))
}

func (a agentRegistrationRequestDo) Order(conds ...field.Expr) IAgentRegistrationRequestDo {
	return a.withDO(a.DO.Order(conds...))
}

func (a agentRegistrationRequestDo) Distinct(cols ...field.Expr) IAgentRegistrationRequestDo {
	return a.withDO(a.DO.Distinct(cols...))
}

func (a agentRegistrationRequestDo) Omit(cols ...field.Expr) IAgentRegistrationRequestDo {
	return a.withDO(a.DO.Omit(cols...))
}

func (a agentRegistrationRequestDo) Join(table schema.Tabler, on ...field.Expr) IAgentRegistrationRequestDo {
	return a.withDO(a.DO.Join(table, on...))
}

func (a agentRegistrationRequestDo) LeftJoin(table schema.Tabler, on ...field.Expr) IAgentRegistrationRequestDo {
	return a.withDO(a.DO.LeftJoin(table, on...))
}

func (a agentRegistrationRequestDo) RightJoin(table schema.Tabler, on ...field.Expr) IAgentRegistrationRequestDo {
	return a.withDO(a.DO.RightJoin(table, on...))
}

func (a agentRegistrationRequestDo) Group(cols ...field.Expr) IAgentRegistrationRequestDo {
	return a.withDO(a.DO.Group(cols...))
}

func (a agentRegistrationRequestDo) Having(conds ...gen.Condition) IAgentRegistrationRequestDo {
	return a.withDO(a.DO.Having(conds...))
}

func (a agentRegistrationRequestDo) Limit(limit int) IAgentRegistrationRequestDo {
	return a.withDO(a.DO.Limit(limit))
}

func (a agentRegistrationRequestDo) Offset(offset int) IAgentRegistrationRequestDo {
	return a.withDO(a.DO.Offset(offset))
}

func (a agentRegistrationRequestDo) Scopes(funcs ...func(gen.Dao) gen.Dao) IAgentRegistrationRequestDo {
	return a.withDO(a.DO.Scopes(funcs...))
}

func (a agentRegistrationRequestDo) Unscoped() IAgentRegistrationRequestDo {
	return a.withDO(a.DO.Unscoped())
}

func (a agentRegistrationRequestDo) Create(values ...*models.AgentRegistrationRequest) error {
	if len(values) == 0 {
		return nil
	}
	return a.DO.Create(values)
}

func (a agentRegistrationRequestDo) CreateInBatches(values []*models.AgentRegistrationRequest, batchSize int) error {
	return a.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (a agentRegistrationRequestDo) Save(values ...*models.AgentRegistrationRequest) error {
	if len(values) == 0 {
		return nil
	}
	return a.DO.Save(values)
}

func (a agentRegistrationRequestDo) First() (*models.AgentRegistrationRequest, error) {
	if result, err := a.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*models.AgentRegistrationRequest), nil
	}
}

func (a agentRegistrationRequestDo) Take() (*models.AgentRegistrationRequest, error) {
	if result, err := a.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*models.AgentRegistrationRequest), nil
	}
}

func (a agentRegistrationRequestDo) Last() (*models.AgentRegistrationRequest, error) {
	if result, err := a.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*models.AgentRegistrationRequest), nil
	}
}

func (a agentRegistrationRequestDo) Find() ([]*models.AgentRegistrationRequest, error) {
	result, err := a.DO.Find()
	return result.([]*models.AgentRegistrationRequest), err
}

func (a agentRegistrationRequestDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*models.AgentRegistrationRequest, err error) {
	buf := make([]*models.AgentRegistrationRequest, 0, batchSize)
	err = a.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (a agentRegistrationRequestDo) FindInBatches(result *[]*models.AgentRegistrationRequest, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return a.DO.FindInBatches(result, batchSize, fc)
}

func (a agentRegistrationRequestDo) Attrs(attrs ...field.AssignExpr) IAgentRegistrationRequestDo {
	return a.withDO(a.DO.Attrs(attrs...))
}

func (a agentRegistrationRequestDo) Assign(attrs ...field.AssignExpr) IAgentRegistrationRequestDo {
	return a.withDO(a.DO.Assign(attrs...))
}

func (a agentRegistrationRequestDo) Joins(fields ...field.RelationField) IAgentRegistrationRequestDo {
	for _, _f := range fields {
		a = *a.withDO(a.DO.Joins(_f))
	}
	return &a
}

func (a agentRegistrationRequestDo) Preload(fields ...field.RelationField) IAgentRegistrationRequestDo {
	for _, _f := range fields {
		a = *a.withDO(a.DO.Preload(_f))
	}
	return &a
}

func (a agentRegistrationRequestDo) FirstOrInit() (*models.AgentRegistrationRequest, error) {
	if result, err := a.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*models.AgentRegistrationRequest), nil
	}
}

func (a agentRegistrationRequestDo) FirstOrCreate() (*models.AgentRegistrationRequest, error) {
	if result, err := a.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*models.AgentRegistrationRequest), nil
	}
}

func (a agentRegistrationRequestDo) FindByPage(offset int, limit int) (result []*models.AgentRegistrationRequest, count int64, err error) {
	result, err = a.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = a.Offset(-1).Limit(-1).Count()
	return
}

func (a agentRegistrationRequestDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = a.Count()
	if err != nil {
		return
	}

	err = a.Offset(offset).Limit(limit).Scan(result)
	return
}

func (a agentRegistrationRequestDo) Scan(result interface{}) (err error) {
	return a.DO.Scan(result)
}

func (a agentRegistrationRequestDo) Delete(models ...*models.AgentRegistrationRequest) (result gen.ResultInfo, err error) {
	return a.DO.Delete(models)
}

func (a *agentRegistrationRequestDo) withDO(do gen.Dao) *agentRegistrationRequestDo {
	a.DO = *do.(*gen.DO)
	return a
}
