// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package db

import (
	"context"
	"database/sql"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"chronix/internal/db/models"
)

func newAuthKey(db *gorm.DB, opts ...gen.DOOption) authKey {
	_authKey := authKey{}

	_authKey.authKeyDo.UseDB(db, opts...)
	_authKey.authKeyDo.UseModel(&models.AuthKey{})

	tableName := _authKey.authKeyDo.TableName()
	_authKey.ALL = field.NewAsterisk(tableName)
	_authKey.AuthKey = field.NewString(tableName, "auth_key")

	_authKey.fillFieldMap()

	return _authKey
}

type authKey struct {
	authKeyDo

	ALL     field.Asterisk
	AuthKey field.String

	fieldMap map[string]field.Expr
}

func (a authKey) Table(newTableName string) *authKey {
	a.authKeyDo.UseTable(newTableName)
	return a.updateTableName(newTableName)
}

func (a authKey) As(alias string) *authKey {
	a.authKeyDo.DO = *(a.authKeyDo.As(alias).(*gen.DO))
	return a.updateTableName(alias)
}

func (a *authKey) updateTableName(table string) *authKey {
	a.ALL = field.NewAsterisk(table)
	a.AuthKey = field.NewString(table, "auth_key")

	a.fillFieldMap()

	return a
}

func (a *authKey) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := a.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (a *authKey) fillFieldMap() {
	a.fieldMap = make(map[string]field.Expr, 1)
	a.fieldMap["auth_key"] = a.AuthKey
}

func (a authKey) clone(db *gorm.DB) authKey {
	a.authKeyDo.ReplaceConnPool(db.Statement.ConnPool)
	return a
}

func (a authKey) replaceDB(db *gorm.DB) authKey {
	a.authKeyDo.ReplaceDB(db)
	return a
}

type authKeyDo struct{ gen.DO }

type IAuthKeyDo interface {
	gen.SubQuery
	Debug() IAuthKeyDo
	WithContext(ctx context.Context) IAuthKeyDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() IAuthKeyDo
	WriteDB() IAuthKeyDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) IAuthKeyDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) IAuthKeyDo
	Not(conds ...gen.Condition) IAuthKeyDo
	Or(conds ...gen.Condition) IAuthKeyDo
	Select(conds ...field.Expr) IAuthKeyDo
	Where(conds ...gen.Condition) IAuthKeyDo
	Order(conds ...field.Expr) IAuthKeyDo
	Distinct(cols ...field.Expr) IAuthKeyDo
	Omit(cols ...field.Expr) IAuthKeyDo
	Join(table schema.Tabler, on ...field.Expr) IAuthKeyDo
	LeftJoin(table schema.Tabler, on ...field.Expr) IAuthKeyDo
	RightJoin(table schema.Tabler, on ...field.Expr) IAuthKeyDo
	Group(cols ...field.Expr) IAuthKeyDo
	Having(conds ...gen.Condition) IAuthKeyDo
	Limit(limit int) IAuthKeyDo
	Offset(offset int) IAuthKeyDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) IAuthKeyDo
	Unscoped() IAuthKeyDo
	Create(values ...*models.AuthKey) error
	CreateInBatches(values []*models.AuthKey, batchSize int) error
	Save(values ...*models.AuthKey) error
	First() (*models.AuthKey, error)
	Take() (*models.AuthKey, error)
	Last() (*models.AuthKey, error)
	Find() ([]*models.AuthKey, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*models.AuthKey, err error)
	FindInBatches(result *[]*models.AuthKey, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*models.AuthKey) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) IAuthKeyDo
	Assign(attrs ...field.AssignExpr) IAuthKeyDo
	Joins(fields ...field.RelationField) IAuthKeyDo
	Preload(fields ...field.RelationField) IAuthKeyDo
	FirstOrInit() (*models.AuthKey, error)
	FirstOrCreate() (*models.AuthKey, error)
	FindByPage(offset int, limit int) (result []*models.AuthKey, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Rows() (*sql.Rows, error)
	Row() *sql.Row
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) IAuthKeyDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (a authKeyDo) Debug() IAuthKeyDo {
	return a.withDO(a.DO.Debug())
}

func (a authKeyDo) WithContext(ctx context.Context) IAuthKeyDo {
	return a.withDO(a.DO.WithContext(ctx))
}

func (a authKeyDo) ReadDB() IAuthKeyDo {
	return a.Clauses(dbresolver.Read)
}

func (a authKeyDo) WriteDB() IAuthKeyDo {
	return a.Clauses(dbresolver.Write)
}

func (a authKeyDo) Session(config *gorm.Session) IAuthKeyDo {
	return a.withDO(a.DO.Session(config))
}

func (a authKeyDo) Clauses(conds ...clause.Expression) IAuthKeyDo {
	return a.withDO(a.DO.Clauses(conds...))
}

func (a authKeyDo) Returning(value interface{}, columns ...string) IAuthKeyDo {
	return a.withDO(a.DO.Returning(value, columns...))
}

func (a authKeyDo) Not(conds ...gen.Condition) IAuthKeyDo {
	return a.withDO(a.DO.Not(conds...))
}

func (a authKeyDo) Or(conds ...gen.Condition) IAuthKeyDo {
	return a.withDO(a.DO.Or(conds...))
}

func (a authKeyDo) Select(conds ...field.Expr) IAuthKeyDo {
	return a.withDO(a.DO.Select(conds...))
}

func (a authKeyDo) Where(conds ...gen.Condition) IAuthKeyDo {
	return a.withDO(a.DO.Where(conds...))
}

func (a authKeyDo) Order(conds ...field.Expr) IAuthKeyDo {
	return a.withDO(a.DO.Order(conds...))
}

func (a authKeyDo) Distinct(cols ...field.Expr) IAuthKeyDo {
	return a.withDO(a.DO.Distinct(cols...))
}

func (a authKeyDo) Omit(cols ...field.Expr) IAuthKeyDo {
	return a.withDO(a.DO.Omit(cols...))
}

func (a authKeyDo) Join(table schema.Tabler, on ...field.Expr) IAuthKeyDo {
	return a.withDO(a.DO.Join(table, on...))
}

func (a authKeyDo) LeftJoin(table schema.Tabler, on ...field.Expr) IAuthKeyDo {
	return a.withDO(a.DO.LeftJoin(table, on...))
}

func (a authKeyDo) RightJoin(table schema.Tabler, on ...field.Expr) IAuthKeyDo {
	return a.withDO(a.DO.RightJoin(table, on...))
}

func (a authKeyDo) Group(cols ...field.Expr) IAuthKeyDo {
	return a.withDO(a.DO.Group(cols...))
}

func (a authKeyDo) Having(conds ...gen.Condition) IAuthKeyDo {
	return a.withDO(a.DO.Having(conds...))
}

func (a authKeyDo) Limit(limit int) IAuthKeyDo {
	return a.withDO(a.DO.Limit(limit))
}

func (a authKeyDo) Offset(offset int) IAuthKeyDo {
	return a.withDO(a.DO.Offset(offset))
}

func (a authKeyDo) Scopes(funcs ...func(gen.Dao) gen.Dao) IAuthKeyDo {
	return a.withDO(a.DO.Scopes(funcs...))
}

func (a authKeyDo) Unscoped() IAuthKeyDo {
	return a.withDO(a.DO.Unscoped())
}

func (a authKeyDo) Create(values ...*models.AuthKey) error {
	if len(values) == 0 {
		return nil
	}
	return a.DO.Create(values)
}

func (a authKeyDo) CreateInBatches(values []*models.AuthKey, batchSize int) error {
	return a.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (a authKeyDo) Save(values ...*models.AuthKey) error {
	if len(values) == 0 {
		return nil
	}
	return a.DO.Save(values)
}

func (a authKeyDo) First() (*models.AuthKey, error) {
	if result, err := a.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*models.AuthKey), nil
	}
}

func (a authKeyDo) Take() (*models.AuthKey, error) {
	if result, err := a.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*models.AuthKey), nil
	}
}

func (a authKeyDo) Last() (*models.AuthKey, error) {
	if result, err := a.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*models.AuthKey), nil
	}
}

func (a authKeyDo) Find() ([]*models.AuthKey, error) {
	result, err := a.DO.Find()
	return result.([]*models.AuthKey), err
}

func (a authKeyDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*models.AuthKey, err error) {
	buf := make([]*models.AuthKey, 0, batchSize)
	err = a.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (a authKeyDo) FindInBatches(result *[]*models.AuthKey, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return a.DO.FindInBatches(result, batchSize, fc)
}

func (a authKeyDo) Attrs(attrs ...field.AssignExpr) IAuthKeyDo {
	return a.withDO(a.DO.Attrs(attrs...))
}

func (a authKeyDo) Assign(attrs ...field.AssignExpr) IAuthKeyDo {
	return a.withDO(a.DO.Assign(attrs...))
}

func (a authKeyDo) Joins(fields ...field.RelationField) IAuthKeyDo {
	for _, _f := range fields {
		a = *a.withDO(a.DO.Joins(_f))
	}
	return &a
}

func (a authKeyDo) Preload(fields ...field.RelationField) IAuthKeyDo {
	for _, _f := range fields {
		a = *a.withDO(a.DO.Preload(_f))
	}
	return &a
}

func (a authKeyDo) FirstOrInit() (*models.AuthKey, error) {
	if result, err := a.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*models.AuthKey), nil
	}
}

func (a authKeyDo) FirstOrCreate() (*models.AuthKey, error) {
	if result, err := a.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*models.AuthKey), nil
	}
}

func (a authKeyDo) FindByPage(offset int, limit int) (result []*models.AuthKey, count int64, err error) {
	result, err = a.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = a.Offset(-1).Limit(-1).Count()
	return
}

func (a authKeyDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = a.Count()
	if err != nil {
		return
	}

	err = a.Offset(offset).Limit(limit).Scan(result)
	return
}

func (a authKeyDo) Scan(result interface{}) (err error) {
	return a.DO.Scan(result)
}

func (a authKeyDo) Delete(models ...*models.AuthKey) (result gen.ResultInfo, err error) {
	return a.DO.Delete(models)
}

func (a *authKeyDo) withDO(do gen.Dao) *authKeyDo {
	a.DO = *do.(*gen.DO)
	return a
}
