// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package db

import (
	"context"
	"database/sql"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"chronix/internal/db/models"
)

func newBugReport(db *gorm.DB, opts ...gen.DOOption) bugReport {
	_bugReport := bugReport{}

	_bugReport.bugReportDo.UseDB(db, opts...)
	_bugReport.bugReportDo.UseModel(&models.BugReport{})

	tableName := _bugReport.bugReportDo.TableName()
	_bugReport.ALL = field.NewAsterisk(tableName)
	_bugReport.ID = field.NewInt64(tableName, "id")
	_bugReport.Summary = field.NewString(tableName, "summary")
	_bugReport.Description = field.NewString(tableName, "description")
	_bugReport.UserID = field.NewInt64(tableName, "user_id")
	_bugReport.CreatedAt = field.NewTime(tableName, "created_at")
	_bugReport.Status = field.NewString(tableName, "status")
	_bugReport.FeedbackAttachments = bugReportHasManyFeedbackAttachments{
		db: db.Session(&gorm.Session{}),

		RelationField: field.NewRelation("FeedbackAttachments", "models.FeedbackAttachment"),
	}

	_bugReport.fillFieldMap()

	return _bugReport
}

type bugReport struct {
	bugReportDo

	ALL                 field.Asterisk
	ID                  field.Int64
	Summary             field.String
	Description         field.String
	UserID              field.Int64
	CreatedAt           field.Time
	Status              field.String
	FeedbackAttachments bugReportHasManyFeedbackAttachments

	fieldMap map[string]field.Expr
}

func (b bugReport) Table(newTableName string) *bugReport {
	b.bugReportDo.UseTable(newTableName)
	return b.updateTableName(newTableName)
}

func (b bugReport) As(alias string) *bugReport {
	b.bugReportDo.DO = *(b.bugReportDo.As(alias).(*gen.DO))
	return b.updateTableName(alias)
}

func (b *bugReport) updateTableName(table string) *bugReport {
	b.ALL = field.NewAsterisk(table)
	b.ID = field.NewInt64(table, "id")
	b.Summary = field.NewString(table, "summary")
	b.Description = field.NewString(table, "description")
	b.UserID = field.NewInt64(table, "user_id")
	b.CreatedAt = field.NewTime(table, "created_at")
	b.Status = field.NewString(table, "status")

	b.fillFieldMap()

	return b
}

func (b *bugReport) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := b.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (b *bugReport) fillFieldMap() {
	b.fieldMap = make(map[string]field.Expr, 7)
	b.fieldMap["id"] = b.ID
	b.fieldMap["summary"] = b.Summary
	b.fieldMap["description"] = b.Description
	b.fieldMap["user_id"] = b.UserID
	b.fieldMap["created_at"] = b.CreatedAt
	b.fieldMap["status"] = b.Status

}

func (b bugReport) clone(db *gorm.DB) bugReport {
	b.bugReportDo.ReplaceConnPool(db.Statement.ConnPool)
	b.FeedbackAttachments.db = db.Session(&gorm.Session{Initialized: true})
	b.FeedbackAttachments.db.Statement.ConnPool = db.Statement.ConnPool
	return b
}

func (b bugReport) replaceDB(db *gorm.DB) bugReport {
	b.bugReportDo.ReplaceDB(db)
	b.FeedbackAttachments.db = db.Session(&gorm.Session{})
	return b
}

type bugReportHasManyFeedbackAttachments struct {
	db *gorm.DB

	field.RelationField
}

func (a bugReportHasManyFeedbackAttachments) Where(conds ...field.Expr) *bugReportHasManyFeedbackAttachments {
	if len(conds) == 0 {
		return &a
	}

	exprs := make([]clause.Expression, 0, len(conds))
	for _, cond := range conds {
		exprs = append(exprs, cond.BeCond().(clause.Expression))
	}
	a.db = a.db.Clauses(clause.Where{Exprs: exprs})
	return &a
}

func (a bugReportHasManyFeedbackAttachments) WithContext(ctx context.Context) *bugReportHasManyFeedbackAttachments {
	a.db = a.db.WithContext(ctx)
	return &a
}

func (a bugReportHasManyFeedbackAttachments) Session(session *gorm.Session) *bugReportHasManyFeedbackAttachments {
	a.db = a.db.Session(session)
	return &a
}

func (a bugReportHasManyFeedbackAttachments) Model(m *models.BugReport) *bugReportHasManyFeedbackAttachmentsTx {
	return &bugReportHasManyFeedbackAttachmentsTx{a.db.Model(m).Association(a.Name())}
}

func (a bugReportHasManyFeedbackAttachments) Unscoped() *bugReportHasManyFeedbackAttachments {
	a.db = a.db.Unscoped()
	return &a
}

type bugReportHasManyFeedbackAttachmentsTx struct{ tx *gorm.Association }

func (a bugReportHasManyFeedbackAttachmentsTx) Find() (result []*models.FeedbackAttachment, err error) {
	return result, a.tx.Find(&result)
}

func (a bugReportHasManyFeedbackAttachmentsTx) Append(values ...*models.FeedbackAttachment) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Append(targetValues...)
}

func (a bugReportHasManyFeedbackAttachmentsTx) Replace(values ...*models.FeedbackAttachment) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Replace(targetValues...)
}

func (a bugReportHasManyFeedbackAttachmentsTx) Delete(values ...*models.FeedbackAttachment) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Delete(targetValues...)
}

func (a bugReportHasManyFeedbackAttachmentsTx) Clear() error {
	return a.tx.Clear()
}

func (a bugReportHasManyFeedbackAttachmentsTx) Count() int64 {
	return a.tx.Count()
}

func (a bugReportHasManyFeedbackAttachmentsTx) Unscoped() *bugReportHasManyFeedbackAttachmentsTx {
	a.tx = a.tx.Unscoped()
	return &a
}

type bugReportDo struct{ gen.DO }

type IBugReportDo interface {
	gen.SubQuery
	Debug() IBugReportDo
	WithContext(ctx context.Context) IBugReportDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() IBugReportDo
	WriteDB() IBugReportDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) IBugReportDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) IBugReportDo
	Not(conds ...gen.Condition) IBugReportDo
	Or(conds ...gen.Condition) IBugReportDo
	Select(conds ...field.Expr) IBugReportDo
	Where(conds ...gen.Condition) IBugReportDo
	Order(conds ...field.Expr) IBugReportDo
	Distinct(cols ...field.Expr) IBugReportDo
	Omit(cols ...field.Expr) IBugReportDo
	Join(table schema.Tabler, on ...field.Expr) IBugReportDo
	LeftJoin(table schema.Tabler, on ...field.Expr) IBugReportDo
	RightJoin(table schema.Tabler, on ...field.Expr) IBugReportDo
	Group(cols ...field.Expr) IBugReportDo
	Having(conds ...gen.Condition) IBugReportDo
	Limit(limit int) IBugReportDo
	Offset(offset int) IBugReportDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) IBugReportDo
	Unscoped() IBugReportDo
	Create(values ...*models.BugReport) error
	CreateInBatches(values []*models.BugReport, batchSize int) error
	Save(values ...*models.BugReport) error
	First() (*models.BugReport, error)
	Take() (*models.BugReport, error)
	Last() (*models.BugReport, error)
	Find() ([]*models.BugReport, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*models.BugReport, err error)
	FindInBatches(result *[]*models.BugReport, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*models.BugReport) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) IBugReportDo
	Assign(attrs ...field.AssignExpr) IBugReportDo
	Joins(fields ...field.RelationField) IBugReportDo
	Preload(fields ...field.RelationField) IBugReportDo
	FirstOrInit() (*models.BugReport, error)
	FirstOrCreate() (*models.BugReport, error)
	FindByPage(offset int, limit int) (result []*models.BugReport, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Rows() (*sql.Rows, error)
	Row() *sql.Row
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) IBugReportDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (b bugReportDo) Debug() IBugReportDo {
	return b.withDO(b.DO.Debug())
}

func (b bugReportDo) WithContext(ctx context.Context) IBugReportDo {
	return b.withDO(b.DO.WithContext(ctx))
}

func (b bugReportDo) ReadDB() IBugReportDo {
	return b.Clauses(dbresolver.Read)
}

func (b bugReportDo) WriteDB() IBugReportDo {
	return b.Clauses(dbresolver.Write)
}

func (b bugReportDo) Session(config *gorm.Session) IBugReportDo {
	return b.withDO(b.DO.Session(config))
}

func (b bugReportDo) Clauses(conds ...clause.Expression) IBugReportDo {
	return b.withDO(b.DO.Clauses(conds...))
}

func (b bugReportDo) Returning(value interface{}, columns ...string) IBugReportDo {
	return b.withDO(b.DO.Returning(value, columns...))
}

func (b bugReportDo) Not(conds ...gen.Condition) IBugReportDo {
	return b.withDO(b.DO.Not(conds...))
}

func (b bugReportDo) Or(conds ...gen.Condition) IBugReportDo {
	return b.withDO(b.DO.Or(conds...))
}

func (b bugReportDo) Select(conds ...field.Expr) IBugReportDo {
	return b.withDO(b.DO.Select(conds...))
}

func (b bugReportDo) Where(conds ...gen.Condition) IBugReportDo {
	return b.withDO(b.DO.Where(conds...))
}

func (b bugReportDo) Order(conds ...field.Expr) IBugReportDo {
	return b.withDO(b.DO.Order(conds...))
}

func (b bugReportDo) Distinct(cols ...field.Expr) IBugReportDo {
	return b.withDO(b.DO.Distinct(cols...))
}

func (b bugReportDo) Omit(cols ...field.Expr) IBugReportDo {
	return b.withDO(b.DO.Omit(cols...))
}

func (b bugReportDo) Join(table schema.Tabler, on ...field.Expr) IBugReportDo {
	return b.withDO(b.DO.Join(table, on...))
}

func (b bugReportDo) LeftJoin(table schema.Tabler, on ...field.Expr) IBugReportDo {
	return b.withDO(b.DO.LeftJoin(table, on...))
}

func (b bugReportDo) RightJoin(table schema.Tabler, on ...field.Expr) IBugReportDo {
	return b.withDO(b.DO.RightJoin(table, on...))
}

func (b bugReportDo) Group(cols ...field.Expr) IBugReportDo {
	return b.withDO(b.DO.Group(cols...))
}

func (b bugReportDo) Having(conds ...gen.Condition) IBugReportDo {
	return b.withDO(b.DO.Having(conds...))
}

func (b bugReportDo) Limit(limit int) IBugReportDo {
	return b.withDO(b.DO.Limit(limit))
}

func (b bugReportDo) Offset(offset int) IBugReportDo {
	return b.withDO(b.DO.Offset(offset))
}

func (b bugReportDo) Scopes(funcs ...func(gen.Dao) gen.Dao) IBugReportDo {
	return b.withDO(b.DO.Scopes(funcs...))
}

func (b bugReportDo) Unscoped() IBugReportDo {
	return b.withDO(b.DO.Unscoped())
}

func (b bugReportDo) Create(values ...*models.BugReport) error {
	if len(values) == 0 {
		return nil
	}
	return b.DO.Create(values)
}

func (b bugReportDo) CreateInBatches(values []*models.BugReport, batchSize int) error {
	return b.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (b bugReportDo) Save(values ...*models.BugReport) error {
	if len(values) == 0 {
		return nil
	}
	return b.DO.Save(values)
}

func (b bugReportDo) First() (*models.BugReport, error) {
	if result, err := b.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*models.BugReport), nil
	}
}

func (b bugReportDo) Take() (*models.BugReport, error) {
	if result, err := b.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*models.BugReport), nil
	}
}

func (b bugReportDo) Last() (*models.BugReport, error) {
	if result, err := b.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*models.BugReport), nil
	}
}

func (b bugReportDo) Find() ([]*models.BugReport, error) {
	result, err := b.DO.Find()
	return result.([]*models.BugReport), err
}

func (b bugReportDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*models.BugReport, err error) {
	buf := make([]*models.BugReport, 0, batchSize)
	err = b.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (b bugReportDo) FindInBatches(result *[]*models.BugReport, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return b.DO.FindInBatches(result, batchSize, fc)
}

func (b bugReportDo) Attrs(attrs ...field.AssignExpr) IBugReportDo {
	return b.withDO(b.DO.Attrs(attrs...))
}

func (b bugReportDo) Assign(attrs ...field.AssignExpr) IBugReportDo {
	return b.withDO(b.DO.Assign(attrs...))
}

func (b bugReportDo) Joins(fields ...field.RelationField) IBugReportDo {
	for _, _f := range fields {
		b = *b.withDO(b.DO.Joins(_f))
	}
	return &b
}

func (b bugReportDo) Preload(fields ...field.RelationField) IBugReportDo {
	for _, _f := range fields {
		b = *b.withDO(b.DO.Preload(_f))
	}
	return &b
}

func (b bugReportDo) FirstOrInit() (*models.BugReport, error) {
	if result, err := b.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*models.BugReport), nil
	}
}

func (b bugReportDo) FirstOrCreate() (*models.BugReport, error) {
	if result, err := b.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*models.BugReport), nil
	}
}

func (b bugReportDo) FindByPage(offset int, limit int) (result []*models.BugReport, count int64, err error) {
	result, err = b.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = b.Offset(-1).Limit(-1).Count()
	return
}

func (b bugReportDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = b.Count()
	if err != nil {
		return
	}

	err = b.Offset(offset).Limit(limit).Scan(result)
	return
}

func (b bugReportDo) Scan(result interface{}) (err error) {
	return b.DO.Scan(result)
}

func (b bugReportDo) Delete(models ...*models.BugReport) (result gen.ResultInfo, err error) {
	return b.DO.Delete(models)
}

func (b *bugReportDo) withDO(do gen.Dao) *bugReportDo {
	b.DO = *do.(*gen.DO)
	return b
}
