// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package db

import (
	"context"
	"database/sql"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"chronix/internal/db/models"
)

func newCxSetting(db *gorm.DB, opts ...gen.DOOption) cxSetting {
	_cxSetting := cxSetting{}

	_cxSetting.cxSettingDo.UseDB(db, opts...)
	_cxSetting.cxSettingDo.UseModel(&models.CxSetting{})

	tableName := _cxSetting.cxSettingDo.TableName()
	_cxSetting.ALL = field.NewAsterisk(tableName)
	_cxSetting.ServerURL = field.NewString(tableName, "server_url")
	_cxSetting.SMTPHost = field.NewString(tableName, "smtp_host")
	_cxSetting.SMTPPort = field.NewInt64(tableName, "smtp_port")
	_cxSetting.SMTPSecure = field.NewString(tableName, "smtp_secure")
	_cxSetting.SMTPFromName = field.NewString(tableName, "smtp_from_name")
	_cxSetting.SMTPFromEmail = field.NewString(tableName, "smtp_from_email")
	_cxSetting.SMTPLogin = field.NewString(tableName, "smtp_login")
	_cxSetting.SMTPPassword = field.NewString(tableName, "smtp_password")
	_cxSetting.HTTPEnabled = field.NewBool(tableName, "http_enabled")
	_cxSetting.HTTPPort = field.NewInt64(tableName, "http_port")
	_cxSetting.HTTPSMode = field.NewString(tableName, "https_mode")
	_cxSetting.HTTPSPort = field.NewInt64(tableName, "https_port")
	_cxSetting.HTTPSEnabled = field.NewBool(tableName, "https_enabled")
	_cxSetting.HTTPSCertPem = field.NewString(tableName, "https_cert_pem")
	_cxSetting.HTTPSKeyPem = field.NewString(tableName, "https_key_pem")
	_cxSetting.SmsProvider = field.NewString(tableName, "sms_provider")
	_cxSetting.SmsFromNumber = field.NewString(tableName, "sms_from_number")
	_cxSetting.TwilioUsername = field.NewString(tableName, "twilio_username")
	_cxSetting.TwilioPassword = field.NewString(tableName, "twilio_password")
	_cxSetting.TwilioAccountSid = field.NewString(tableName, "twilio_account_sid")
	_cxSetting.TwilioAPIKey = field.NewString(tableName, "twilio_api_key")
	_cxSetting.TwilioAPISecret = field.NewString(tableName, "twilio_api_secret")
	_cxSetting.AgentEnabled = field.NewBool(tableName, "agent_enabled")
	_cxSetting.AgentPort = field.NewInt64(tableName, "agent_port")
	_cxSetting.SystemAlertEmails = field.NewString(tableName, "system_alert_emails")
	_cxSetting.SystemAlertPhones = field.NewString(tableName, "system_alert_phones")
	_cxSetting.AlertOnAgentLost = field.NewBool(tableName, "alert_on_agent_lost")
	_cxSetting.UpdaterEnabled = field.NewBool(tableName, "updater_enabled")
	_cxSetting.UpdaterMode = field.NewString(tableName, "updater_mode")
	_cxSetting.UpdaterWindowStart = field.NewString(tableName, "updater_window_start")
	_cxSetting.UpdaterAgentEnabled = field.NewBool(tableName, "updater_agent_enabled")
	_cxSetting.UpdaterAgentMode = field.NewString(tableName, "updater_agent_mode")
	_cxSetting.UpdaterAgentWindowStart = field.NewString(tableName, "updater_agent_window_start")
	_cxSetting.BrandLogoURL = field.NewString(tableName, "brand_logo_url")
	_cxSetting.BrandName = field.NewString(tableName, "brand_name")
	_cxSetting.ID = field.NewInt64(tableName, "id")

	_cxSetting.fillFieldMap()

	return _cxSetting
}

type cxSetting struct {
	cxSettingDo

	ALL                     field.Asterisk
	ServerURL               field.String
	SMTPHost                field.String
	SMTPPort                field.Int64
	SMTPSecure              field.String
	SMTPFromName            field.String
	SMTPFromEmail           field.String
	SMTPLogin               field.String
	SMTPPassword            field.String
	HTTPEnabled             field.Bool
	HTTPPort                field.Int64
	HTTPSMode               field.String
	HTTPSPort               field.Int64
	HTTPSEnabled            field.Bool
	HTTPSCertPem            field.String
	HTTPSKeyPem             field.String
	SmsProvider             field.String
	SmsFromNumber           field.String
	TwilioUsername          field.String
	TwilioPassword          field.String
	TwilioAccountSid        field.String
	TwilioAPIKey            field.String
	TwilioAPISecret         field.String
	AgentEnabled            field.Bool
	AgentPort               field.Int64
	SystemAlertEmails       field.String
	SystemAlertPhones       field.String
	AlertOnAgentLost        field.Bool
	UpdaterEnabled          field.Bool
	UpdaterMode             field.String
	UpdaterWindowStart      field.String
	UpdaterAgentEnabled     field.Bool
	UpdaterAgentMode        field.String
	UpdaterAgentWindowStart field.String
	BrandLogoURL            field.String
	BrandName               field.String
	ID                      field.Int64

	fieldMap map[string]field.Expr
}

func (c cxSetting) Table(newTableName string) *cxSetting {
	c.cxSettingDo.UseTable(newTableName)
	return c.updateTableName(newTableName)
}

func (c cxSetting) As(alias string) *cxSetting {
	c.cxSettingDo.DO = *(c.cxSettingDo.As(alias).(*gen.DO))
	return c.updateTableName(alias)
}

func (c *cxSetting) updateTableName(table string) *cxSetting {
	c.ALL = field.NewAsterisk(table)
	c.ServerURL = field.NewString(table, "server_url")
	c.SMTPHost = field.NewString(table, "smtp_host")
	c.SMTPPort = field.NewInt64(table, "smtp_port")
	c.SMTPSecure = field.NewString(table, "smtp_secure")
	c.SMTPFromName = field.NewString(table, "smtp_from_name")
	c.SMTPFromEmail = field.NewString(table, "smtp_from_email")
	c.SMTPLogin = field.NewString(table, "smtp_login")
	c.SMTPPassword = field.NewString(table, "smtp_password")
	c.HTTPEnabled = field.NewBool(table, "http_enabled")
	c.HTTPPort = field.NewInt64(table, "http_port")
	c.HTTPSMode = field.NewString(table, "https_mode")
	c.HTTPSPort = field.NewInt64(table, "https_port")
	c.HTTPSEnabled = field.NewBool(table, "https_enabled")
	c.HTTPSCertPem = field.NewString(table, "https_cert_pem")
	c.HTTPSKeyPem = field.NewString(table, "https_key_pem")
	c.SmsProvider = field.NewString(table, "sms_provider")
	c.SmsFromNumber = field.NewString(table, "sms_from_number")
	c.TwilioUsername = field.NewString(table, "twilio_username")
	c.TwilioPassword = field.NewString(table, "twilio_password")
	c.TwilioAccountSid = field.NewString(table, "twilio_account_sid")
	c.TwilioAPIKey = field.NewString(table, "twilio_api_key")
	c.TwilioAPISecret = field.NewString(table, "twilio_api_secret")
	c.AgentEnabled = field.NewBool(table, "agent_enabled")
	c.AgentPort = field.NewInt64(table, "agent_port")
	c.SystemAlertEmails = field.NewString(table, "system_alert_emails")
	c.SystemAlertPhones = field.NewString(table, "system_alert_phones")
	c.AlertOnAgentLost = field.NewBool(table, "alert_on_agent_lost")
	c.UpdaterEnabled = field.NewBool(table, "updater_enabled")
	c.UpdaterMode = field.NewString(table, "updater_mode")
	c.UpdaterWindowStart = field.NewString(table, "updater_window_start")
	c.UpdaterAgentEnabled = field.NewBool(table, "updater_agent_enabled")
	c.UpdaterAgentMode = field.NewString(table, "updater_agent_mode")
	c.UpdaterAgentWindowStart = field.NewString(table, "updater_agent_window_start")
	c.BrandLogoURL = field.NewString(table, "brand_logo_url")
	c.BrandName = field.NewString(table, "brand_name")
	c.ID = field.NewInt64(table, "id")

	c.fillFieldMap()

	return c
}

func (c *cxSetting) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := c.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (c *cxSetting) fillFieldMap() {
	c.fieldMap = make(map[string]field.Expr, 36)
	c.fieldMap["server_url"] = c.ServerURL
	c.fieldMap["smtp_host"] = c.SMTPHost
	c.fieldMap["smtp_port"] = c.SMTPPort
	c.fieldMap["smtp_secure"] = c.SMTPSecure
	c.fieldMap["smtp_from_name"] = c.SMTPFromName
	c.fieldMap["smtp_from_email"] = c.SMTPFromEmail
	c.fieldMap["smtp_login"] = c.SMTPLogin
	c.fieldMap["smtp_password"] = c.SMTPPassword
	c.fieldMap["http_enabled"] = c.HTTPEnabled
	c.fieldMap["http_port"] = c.HTTPPort
	c.fieldMap["https_mode"] = c.HTTPSMode
	c.fieldMap["https_port"] = c.HTTPSPort
	c.fieldMap["https_enabled"] = c.HTTPSEnabled
	c.fieldMap["https_cert_pem"] = c.HTTPSCertPem
	c.fieldMap["https_key_pem"] = c.HTTPSKeyPem
	c.fieldMap["sms_provider"] = c.SmsProvider
	c.fieldMap["sms_from_number"] = c.SmsFromNumber
	c.fieldMap["twilio_username"] = c.TwilioUsername
	c.fieldMap["twilio_password"] = c.TwilioPassword
	c.fieldMap["twilio_account_sid"] = c.TwilioAccountSid
	c.fieldMap["twilio_api_key"] = c.TwilioAPIKey
	c.fieldMap["twilio_api_secret"] = c.TwilioAPISecret
	c.fieldMap["agent_enabled"] = c.AgentEnabled
	c.fieldMap["agent_port"] = c.AgentPort
	c.fieldMap["system_alert_emails"] = c.SystemAlertEmails
	c.fieldMap["system_alert_phones"] = c.SystemAlertPhones
	c.fieldMap["alert_on_agent_lost"] = c.AlertOnAgentLost
	c.fieldMap["updater_enabled"] = c.UpdaterEnabled
	c.fieldMap["updater_mode"] = c.UpdaterMode
	c.fieldMap["updater_window_start"] = c.UpdaterWindowStart
	c.fieldMap["updater_agent_enabled"] = c.UpdaterAgentEnabled
	c.fieldMap["updater_agent_mode"] = c.UpdaterAgentMode
	c.fieldMap["updater_agent_window_start"] = c.UpdaterAgentWindowStart
	c.fieldMap["brand_logo_url"] = c.BrandLogoURL
	c.fieldMap["brand_name"] = c.BrandName
	c.fieldMap["id"] = c.ID
}

func (c cxSetting) clone(db *gorm.DB) cxSetting {
	c.cxSettingDo.ReplaceConnPool(db.Statement.ConnPool)
	return c
}

func (c cxSetting) replaceDB(db *gorm.DB) cxSetting {
	c.cxSettingDo.ReplaceDB(db)
	return c
}

type cxSettingDo struct{ gen.DO }

type ICxSettingDo interface {
	gen.SubQuery
	Debug() ICxSettingDo
	WithContext(ctx context.Context) ICxSettingDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() ICxSettingDo
	WriteDB() ICxSettingDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) ICxSettingDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) ICxSettingDo
	Not(conds ...gen.Condition) ICxSettingDo
	Or(conds ...gen.Condition) ICxSettingDo
	Select(conds ...field.Expr) ICxSettingDo
	Where(conds ...gen.Condition) ICxSettingDo
	Order(conds ...field.Expr) ICxSettingDo
	Distinct(cols ...field.Expr) ICxSettingDo
	Omit(cols ...field.Expr) ICxSettingDo
	Join(table schema.Tabler, on ...field.Expr) ICxSettingDo
	LeftJoin(table schema.Tabler, on ...field.Expr) ICxSettingDo
	RightJoin(table schema.Tabler, on ...field.Expr) ICxSettingDo
	Group(cols ...field.Expr) ICxSettingDo
	Having(conds ...gen.Condition) ICxSettingDo
	Limit(limit int) ICxSettingDo
	Offset(offset int) ICxSettingDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) ICxSettingDo
	Unscoped() ICxSettingDo
	Create(values ...*models.CxSetting) error
	CreateInBatches(values []*models.CxSetting, batchSize int) error
	Save(values ...*models.CxSetting) error
	First() (*models.CxSetting, error)
	Take() (*models.CxSetting, error)
	Last() (*models.CxSetting, error)
	Find() ([]*models.CxSetting, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*models.CxSetting, err error)
	FindInBatches(result *[]*models.CxSetting, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*models.CxSetting) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) ICxSettingDo
	Assign(attrs ...field.AssignExpr) ICxSettingDo
	Joins(fields ...field.RelationField) ICxSettingDo
	Preload(fields ...field.RelationField) ICxSettingDo
	FirstOrInit() (*models.CxSetting, error)
	FirstOrCreate() (*models.CxSetting, error)
	FindByPage(offset int, limit int) (result []*models.CxSetting, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Rows() (*sql.Rows, error)
	Row() *sql.Row
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) ICxSettingDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (c cxSettingDo) Debug() ICxSettingDo {
	return c.withDO(c.DO.Debug())
}

func (c cxSettingDo) WithContext(ctx context.Context) ICxSettingDo {
	return c.withDO(c.DO.WithContext(ctx))
}

func (c cxSettingDo) ReadDB() ICxSettingDo {
	return c.Clauses(dbresolver.Read)
}

func (c cxSettingDo) WriteDB() ICxSettingDo {
	return c.Clauses(dbresolver.Write)
}

func (c cxSettingDo) Session(config *gorm.Session) ICxSettingDo {
	return c.withDO(c.DO.Session(config))
}

func (c cxSettingDo) Clauses(conds ...clause.Expression) ICxSettingDo {
	return c.withDO(c.DO.Clauses(conds...))
}

func (c cxSettingDo) Returning(value interface{}, columns ...string) ICxSettingDo {
	return c.withDO(c.DO.Returning(value, columns...))
}

func (c cxSettingDo) Not(conds ...gen.Condition) ICxSettingDo {
	return c.withDO(c.DO.Not(conds...))
}

func (c cxSettingDo) Or(conds ...gen.Condition) ICxSettingDo {
	return c.withDO(c.DO.Or(conds...))
}

func (c cxSettingDo) Select(conds ...field.Expr) ICxSettingDo {
	return c.withDO(c.DO.Select(conds...))
}

func (c cxSettingDo) Where(conds ...gen.Condition) ICxSettingDo {
	return c.withDO(c.DO.Where(conds...))
}

func (c cxSettingDo) Order(conds ...field.Expr) ICxSettingDo {
	return c.withDO(c.DO.Order(conds...))
}

func (c cxSettingDo) Distinct(cols ...field.Expr) ICxSettingDo {
	return c.withDO(c.DO.Distinct(cols...))
}

func (c cxSettingDo) Omit(cols ...field.Expr) ICxSettingDo {
	return c.withDO(c.DO.Omit(cols...))
}

func (c cxSettingDo) Join(table schema.Tabler, on ...field.Expr) ICxSettingDo {
	return c.withDO(c.DO.Join(table, on...))
}

func (c cxSettingDo) LeftJoin(table schema.Tabler, on ...field.Expr) ICxSettingDo {
	return c.withDO(c.DO.LeftJoin(table, on...))
}

func (c cxSettingDo) RightJoin(table schema.Tabler, on ...field.Expr) ICxSettingDo {
	return c.withDO(c.DO.RightJoin(table, on...))
}

func (c cxSettingDo) Group(cols ...field.Expr) ICxSettingDo {
	return c.withDO(c.DO.Group(cols...))
}

func (c cxSettingDo) Having(conds ...gen.Condition) ICxSettingDo {
	return c.withDO(c.DO.Having(conds...))
}

func (c cxSettingDo) Limit(limit int) ICxSettingDo {
	return c.withDO(c.DO.Limit(limit))
}

func (c cxSettingDo) Offset(offset int) ICxSettingDo {
	return c.withDO(c.DO.Offset(offset))
}

func (c cxSettingDo) Scopes(funcs ...func(gen.Dao) gen.Dao) ICxSettingDo {
	return c.withDO(c.DO.Scopes(funcs...))
}

func (c cxSettingDo) Unscoped() ICxSettingDo {
	return c.withDO(c.DO.Unscoped())
}

func (c cxSettingDo) Create(values ...*models.CxSetting) error {
	if len(values) == 0 {
		return nil
	}
	return c.DO.Create(values)
}

func (c cxSettingDo) CreateInBatches(values []*models.CxSetting, batchSize int) error {
	return c.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (c cxSettingDo) Save(values ...*models.CxSetting) error {
	if len(values) == 0 {
		return nil
	}
	return c.DO.Save(values)
}

func (c cxSettingDo) First() (*models.CxSetting, error) {
	if result, err := c.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*models.CxSetting), nil
	}
}

func (c cxSettingDo) Take() (*models.CxSetting, error) {
	if result, err := c.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*models.CxSetting), nil
	}
}

func (c cxSettingDo) Last() (*models.CxSetting, error) {
	if result, err := c.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*models.CxSetting), nil
	}
}

func (c cxSettingDo) Find() ([]*models.CxSetting, error) {
	result, err := c.DO.Find()
	return result.([]*models.CxSetting), err
}

func (c cxSettingDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*models.CxSetting, err error) {
	buf := make([]*models.CxSetting, 0, batchSize)
	err = c.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (c cxSettingDo) FindInBatches(result *[]*models.CxSetting, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return c.DO.FindInBatches(result, batchSize, fc)
}

func (c cxSettingDo) Attrs(attrs ...field.AssignExpr) ICxSettingDo {
	return c.withDO(c.DO.Attrs(attrs...))
}

func (c cxSettingDo) Assign(attrs ...field.AssignExpr) ICxSettingDo {
	return c.withDO(c.DO.Assign(attrs...))
}

func (c cxSettingDo) Joins(fields ...field.RelationField) ICxSettingDo {
	for _, _f := range fields {
		c = *c.withDO(c.DO.Joins(_f))
	}
	return &c
}

func (c cxSettingDo) Preload(fields ...field.RelationField) ICxSettingDo {
	for _, _f := range fields {
		c = *c.withDO(c.DO.Preload(_f))
	}
	return &c
}

func (c cxSettingDo) FirstOrInit() (*models.CxSetting, error) {
	if result, err := c.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*models.CxSetting), nil
	}
}

func (c cxSettingDo) FirstOrCreate() (*models.CxSetting, error) {
	if result, err := c.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*models.CxSetting), nil
	}
}

func (c cxSettingDo) FindByPage(offset int, limit int) (result []*models.CxSetting, count int64, err error) {
	result, err = c.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = c.Offset(-1).Limit(-1).Count()
	return
}

func (c cxSettingDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = c.Count()
	if err != nil {
		return
	}

	err = c.Offset(offset).Limit(limit).Scan(result)
	return
}

func (c cxSettingDo) Scan(result interface{}) (err error) {
	return c.DO.Scan(result)
}

func (c cxSettingDo) Delete(models ...*models.CxSetting) (result gen.ResultInfo, err error) {
	return c.DO.Delete(models)
}

func (c *cxSettingDo) withDO(do gen.Dao) *cxSettingDo {
	c.DO = *do.(*gen.DO)
	return c
}
