// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package db

import (
	"context"
	"database/sql"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"chronix/internal/db/models"
)

func newCxUser(db *gorm.DB, opts ...gen.DOOption) cxUser {
	_cxUser := cxUser{}

	_cxUser.cxUserDo.UseDB(db, opts...)
	_cxUser.cxUserDo.UseModel(&models.CxUser{})

	tableName := _cxUser.cxUserDo.TableName()
	_cxUser.ALL = field.NewAsterisk(tableName)
	_cxUser.ID = field.NewInt64(tableName, "id")
	_cxUser.Email = field.NewString(tableName, "email")
	_cxUser.Name = field.NewString(tableName, "name")
	_cxUser.Phone = field.NewString(tableName, "phone")
	_cxUser.Password = field.NewString(tableName, "password")
	_cxUser.ForcePasswordChange = field.NewBool(tableName, "force_password_change")
	_cxUser.Enabled = field.NewBool(tableName, "enabled")
	_cxUser.Suspended = field.NewBool(tableName, "suspended")
	_cxUser.Admin = field.NewBool(tableName, "admin")
	_cxUser.Sv = field.NewInt32(tableName, "sv")
	_cxUser.TimeZone = field.NewString(tableName, "time_zone")
	_cxUser.TimeFormat = field.NewString(tableName, "time_format")

	_cxUser.fillFieldMap()

	return _cxUser
}

type cxUser struct {
	cxUserDo

	ALL                 field.Asterisk
	ID                  field.Int64
	Email               field.String
	Name                field.String
	Phone               field.String
	Password            field.String
	ForcePasswordChange field.Bool
	Enabled             field.Bool
	Suspended           field.Bool
	Admin               field.Bool
	Sv                  field.Int32
	TimeZone            field.String
	TimeFormat          field.String

	fieldMap map[string]field.Expr
}

func (c cxUser) Table(newTableName string) *cxUser {
	c.cxUserDo.UseTable(newTableName)
	return c.updateTableName(newTableName)
}

func (c cxUser) As(alias string) *cxUser {
	c.cxUserDo.DO = *(c.cxUserDo.As(alias).(*gen.DO))
	return c.updateTableName(alias)
}

func (c *cxUser) updateTableName(table string) *cxUser {
	c.ALL = field.NewAsterisk(table)
	c.ID = field.NewInt64(table, "id")
	c.Email = field.NewString(table, "email")
	c.Name = field.NewString(table, "name")
	c.Phone = field.NewString(table, "phone")
	c.Password = field.NewString(table, "password")
	c.ForcePasswordChange = field.NewBool(table, "force_password_change")
	c.Enabled = field.NewBool(table, "enabled")
	c.Suspended = field.NewBool(table, "suspended")
	c.Admin = field.NewBool(table, "admin")
	c.Sv = field.NewInt32(table, "sv")
	c.TimeZone = field.NewString(table, "time_zone")
	c.TimeFormat = field.NewString(table, "time_format")

	c.fillFieldMap()

	return c
}

func (c *cxUser) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := c.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (c *cxUser) fillFieldMap() {
	c.fieldMap = make(map[string]field.Expr, 12)
	c.fieldMap["id"] = c.ID
	c.fieldMap["email"] = c.Email
	c.fieldMap["name"] = c.Name
	c.fieldMap["phone"] = c.Phone
	c.fieldMap["password"] = c.Password
	c.fieldMap["force_password_change"] = c.ForcePasswordChange
	c.fieldMap["enabled"] = c.Enabled
	c.fieldMap["suspended"] = c.Suspended
	c.fieldMap["admin"] = c.Admin
	c.fieldMap["sv"] = c.Sv
	c.fieldMap["time_zone"] = c.TimeZone
	c.fieldMap["time_format"] = c.TimeFormat
}

func (c cxUser) clone(db *gorm.DB) cxUser {
	c.cxUserDo.ReplaceConnPool(db.Statement.ConnPool)
	return c
}

func (c cxUser) replaceDB(db *gorm.DB) cxUser {
	c.cxUserDo.ReplaceDB(db)
	return c
}

type cxUserDo struct{ gen.DO }

type ICxUserDo interface {
	gen.SubQuery
	Debug() ICxUserDo
	WithContext(ctx context.Context) ICxUserDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() ICxUserDo
	WriteDB() ICxUserDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) ICxUserDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) ICxUserDo
	Not(conds ...gen.Condition) ICxUserDo
	Or(conds ...gen.Condition) ICxUserDo
	Select(conds ...field.Expr) ICxUserDo
	Where(conds ...gen.Condition) ICxUserDo
	Order(conds ...field.Expr) ICxUserDo
	Distinct(cols ...field.Expr) ICxUserDo
	Omit(cols ...field.Expr) ICxUserDo
	Join(table schema.Tabler, on ...field.Expr) ICxUserDo
	LeftJoin(table schema.Tabler, on ...field.Expr) ICxUserDo
	RightJoin(table schema.Tabler, on ...field.Expr) ICxUserDo
	Group(cols ...field.Expr) ICxUserDo
	Having(conds ...gen.Condition) ICxUserDo
	Limit(limit int) ICxUserDo
	Offset(offset int) ICxUserDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) ICxUserDo
	Unscoped() ICxUserDo
	Create(values ...*models.CxUser) error
	CreateInBatches(values []*models.CxUser, batchSize int) error
	Save(values ...*models.CxUser) error
	First() (*models.CxUser, error)
	Take() (*models.CxUser, error)
	Last() (*models.CxUser, error)
	Find() ([]*models.CxUser, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*models.CxUser, err error)
	FindInBatches(result *[]*models.CxUser, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*models.CxUser) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) ICxUserDo
	Assign(attrs ...field.AssignExpr) ICxUserDo
	Joins(fields ...field.RelationField) ICxUserDo
	Preload(fields ...field.RelationField) ICxUserDo
	FirstOrInit() (*models.CxUser, error)
	FirstOrCreate() (*models.CxUser, error)
	FindByPage(offset int, limit int) (result []*models.CxUser, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Rows() (*sql.Rows, error)
	Row() *sql.Row
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) ICxUserDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (c cxUserDo) Debug() ICxUserDo {
	return c.withDO(c.DO.Debug())
}

func (c cxUserDo) WithContext(ctx context.Context) ICxUserDo {
	return c.withDO(c.DO.WithContext(ctx))
}

func (c cxUserDo) ReadDB() ICxUserDo {
	return c.Clauses(dbresolver.Read)
}

func (c cxUserDo) WriteDB() ICxUserDo {
	return c.Clauses(dbresolver.Write)
}

func (c cxUserDo) Session(config *gorm.Session) ICxUserDo {
	return c.withDO(c.DO.Session(config))
}

func (c cxUserDo) Clauses(conds ...clause.Expression) ICxUserDo {
	return c.withDO(c.DO.Clauses(conds...))
}

func (c cxUserDo) Returning(value interface{}, columns ...string) ICxUserDo {
	return c.withDO(c.DO.Returning(value, columns...))
}

func (c cxUserDo) Not(conds ...gen.Condition) ICxUserDo {
	return c.withDO(c.DO.Not(conds...))
}

func (c cxUserDo) Or(conds ...gen.Condition) ICxUserDo {
	return c.withDO(c.DO.Or(conds...))
}

func (c cxUserDo) Select(conds ...field.Expr) ICxUserDo {
	return c.withDO(c.DO.Select(conds...))
}

func (c cxUserDo) Where(conds ...gen.Condition) ICxUserDo {
	return c.withDO(c.DO.Where(conds...))
}

func (c cxUserDo) Order(conds ...field.Expr) ICxUserDo {
	return c.withDO(c.DO.Order(conds...))
}

func (c cxUserDo) Distinct(cols ...field.Expr) ICxUserDo {
	return c.withDO(c.DO.Distinct(cols...))
}

func (c cxUserDo) Omit(cols ...field.Expr) ICxUserDo {
	return c.withDO(c.DO.Omit(cols...))
}

func (c cxUserDo) Join(table schema.Tabler, on ...field.Expr) ICxUserDo {
	return c.withDO(c.DO.Join(table, on...))
}

func (c cxUserDo) LeftJoin(table schema.Tabler, on ...field.Expr) ICxUserDo {
	return c.withDO(c.DO.LeftJoin(table, on...))
}

func (c cxUserDo) RightJoin(table schema.Tabler, on ...field.Expr) ICxUserDo {
	return c.withDO(c.DO.RightJoin(table, on...))
}

func (c cxUserDo) Group(cols ...field.Expr) ICxUserDo {
	return c.withDO(c.DO.Group(cols...))
}

func (c cxUserDo) Having(conds ...gen.Condition) ICxUserDo {
	return c.withDO(c.DO.Having(conds...))
}

func (c cxUserDo) Limit(limit int) ICxUserDo {
	return c.withDO(c.DO.Limit(limit))
}

func (c cxUserDo) Offset(offset int) ICxUserDo {
	return c.withDO(c.DO.Offset(offset))
}

func (c cxUserDo) Scopes(funcs ...func(gen.Dao) gen.Dao) ICxUserDo {
	return c.withDO(c.DO.Scopes(funcs...))
}

func (c cxUserDo) Unscoped() ICxUserDo {
	return c.withDO(c.DO.Unscoped())
}

func (c cxUserDo) Create(values ...*models.CxUser) error {
	if len(values) == 0 {
		return nil
	}
	return c.DO.Create(values)
}

func (c cxUserDo) CreateInBatches(values []*models.CxUser, batchSize int) error {
	return c.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (c cxUserDo) Save(values ...*models.CxUser) error {
	if len(values) == 0 {
		return nil
	}
	return c.DO.Save(values)
}

func (c cxUserDo) First() (*models.CxUser, error) {
	if result, err := c.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*models.CxUser), nil
	}
}

func (c cxUserDo) Take() (*models.CxUser, error) {
	if result, err := c.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*models.CxUser), nil
	}
}

func (c cxUserDo) Last() (*models.CxUser, error) {
	if result, err := c.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*models.CxUser), nil
	}
}

func (c cxUserDo) Find() ([]*models.CxUser, error) {
	result, err := c.DO.Find()
	return result.([]*models.CxUser), err
}

func (c cxUserDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*models.CxUser, err error) {
	buf := make([]*models.CxUser, 0, batchSize)
	err = c.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (c cxUserDo) FindInBatches(result *[]*models.CxUser, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return c.DO.FindInBatches(result, batchSize, fc)
}

func (c cxUserDo) Attrs(attrs ...field.AssignExpr) ICxUserDo {
	return c.withDO(c.DO.Attrs(attrs...))
}

func (c cxUserDo) Assign(attrs ...field.AssignExpr) ICxUserDo {
	return c.withDO(c.DO.Assign(attrs...))
}

func (c cxUserDo) Joins(fields ...field.RelationField) ICxUserDo {
	for _, _f := range fields {
		c = *c.withDO(c.DO.Joins(_f))
	}
	return &c
}

func (c cxUserDo) Preload(fields ...field.RelationField) ICxUserDo {
	for _, _f := range fields {
		c = *c.withDO(c.DO.Preload(_f))
	}
	return &c
}

func (c cxUserDo) FirstOrInit() (*models.CxUser, error) {
	if result, err := c.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*models.CxUser), nil
	}
}

func (c cxUserDo) FirstOrCreate() (*models.CxUser, error) {
	if result, err := c.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*models.CxUser), nil
	}
}

func (c cxUserDo) FindByPage(offset int, limit int) (result []*models.CxUser, count int64, err error) {
	result, err = c.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = c.Offset(-1).Limit(-1).Count()
	return
}

func (c cxUserDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = c.Count()
	if err != nil {
		return
	}

	err = c.Offset(offset).Limit(limit).Scan(result)
	return
}

func (c cxUserDo) Scan(result interface{}) (err error) {
	return c.DO.Scan(result)
}

func (c cxUserDo) Delete(models ...*models.CxUser) (result gen.ResultInfo, err error) {
	return c.DO.Delete(models)
}

func (c *cxUserDo) withDO(do gen.Dao) *cxUserDo {
	c.DO = *do.(*gen.DO)
	return c
}
