// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package db

import (
	"context"
	"database/sql"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"chronix/internal/db/models"
)

func newDbConnection(db *gorm.DB, opts ...gen.DOOption) dbConnection {
	_dbConnection := dbConnection{}

	_dbConnection.dbConnectionDo.UseDB(db, opts...)
	_dbConnection.dbConnectionDo.UseModel(&models.DbConnection{})

	tableName := _dbConnection.dbConnectionDo.TableName()
	_dbConnection.ALL = field.NewAsterisk(tableName)
	_dbConnection.ID = field.NewInt64(tableName, "id")
	_dbConnection.Name = field.NewString(tableName, "name")
	_dbConnection.Driver = field.NewString(tableName, "driver")
	_dbConnection.Dsn = field.NewString(tableName, "dsn")
	_dbConnection.Description = field.NewString(tableName, "description")
	_dbConnection.AutoCheckEnabled = field.NewInt64(tableName, "auto_check_enabled")
	_dbConnection.AutoCheckIntervalSeconds = field.NewInt64(tableName, "auto_check_interval_seconds")
	_dbConnection.AgentUUID = field.NewString(tableName, "agent_uuid")
	_dbConnection.CreatedAt = field.NewTime(tableName, "created_at")
	_dbConnection.UpdatedAt = field.NewTime(tableName, "updated_at")
	_dbConnection.LastStatus = field.NewString(tableName, "last_status")
	_dbConnection.LastError = field.NewString(tableName, "last_error")
	_dbConnection.LastCheckedAt = field.NewTime(tableName, "last_checked_at")
	_dbConnection.AlertEmails = field.NewString(tableName, "alert_emails")
	_dbConnection.AlertPhones = field.NewString(tableName, "alert_phones")
	_dbConnection.NotifyOnFailure = field.NewBool(tableName, "notify_on_failure")
	_dbConnection.Enabled = field.NewBool(tableName, "enabled")
	_dbConnection.Suspended = field.NewBool(tableName, "suspended")

	_dbConnection.fillFieldMap()

	return _dbConnection
}

type dbConnection struct {
	dbConnectionDo

	ALL                      field.Asterisk
	ID                       field.Int64
	Name                     field.String
	Driver                   field.String
	Dsn                      field.String
	Description              field.String
	AutoCheckEnabled         field.Int64
	AutoCheckIntervalSeconds field.Int64
	AgentUUID                field.String
	CreatedAt                field.Time
	UpdatedAt                field.Time
	LastStatus               field.String
	LastError                field.String
	LastCheckedAt            field.Time
	AlertEmails              field.String
	AlertPhones              field.String
	NotifyOnFailure          field.Bool
	Enabled                  field.Bool
	Suspended                field.Bool

	fieldMap map[string]field.Expr
}

func (d dbConnection) Table(newTableName string) *dbConnection {
	d.dbConnectionDo.UseTable(newTableName)
	return d.updateTableName(newTableName)
}

func (d dbConnection) As(alias string) *dbConnection {
	d.dbConnectionDo.DO = *(d.dbConnectionDo.As(alias).(*gen.DO))
	return d.updateTableName(alias)
}

func (d *dbConnection) updateTableName(table string) *dbConnection {
	d.ALL = field.NewAsterisk(table)
	d.ID = field.NewInt64(table, "id")
	d.Name = field.NewString(table, "name")
	d.Driver = field.NewString(table, "driver")
	d.Dsn = field.NewString(table, "dsn")
	d.Description = field.NewString(table, "description")
	d.AutoCheckEnabled = field.NewInt64(table, "auto_check_enabled")
	d.AutoCheckIntervalSeconds = field.NewInt64(table, "auto_check_interval_seconds")
	d.AgentUUID = field.NewString(table, "agent_uuid")
	d.CreatedAt = field.NewTime(table, "created_at")
	d.UpdatedAt = field.NewTime(table, "updated_at")
	d.LastStatus = field.NewString(table, "last_status")
	d.LastError = field.NewString(table, "last_error")
	d.LastCheckedAt = field.NewTime(table, "last_checked_at")
	d.AlertEmails = field.NewString(table, "alert_emails")
	d.AlertPhones = field.NewString(table, "alert_phones")
	d.NotifyOnFailure = field.NewBool(table, "notify_on_failure")
	d.Enabled = field.NewBool(table, "enabled")
	d.Suspended = field.NewBool(table, "suspended")

	d.fillFieldMap()

	return d
}

func (d *dbConnection) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := d.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (d *dbConnection) fillFieldMap() {
	d.fieldMap = make(map[string]field.Expr, 18)
	d.fieldMap["id"] = d.ID
	d.fieldMap["name"] = d.Name
	d.fieldMap["driver"] = d.Driver
	d.fieldMap["dsn"] = d.Dsn
	d.fieldMap["description"] = d.Description
	d.fieldMap["auto_check_enabled"] = d.AutoCheckEnabled
	d.fieldMap["auto_check_interval_seconds"] = d.AutoCheckIntervalSeconds
	d.fieldMap["agent_uuid"] = d.AgentUUID
	d.fieldMap["created_at"] = d.CreatedAt
	d.fieldMap["updated_at"] = d.UpdatedAt
	d.fieldMap["last_status"] = d.LastStatus
	d.fieldMap["last_error"] = d.LastError
	d.fieldMap["last_checked_at"] = d.LastCheckedAt
	d.fieldMap["alert_emails"] = d.AlertEmails
	d.fieldMap["alert_phones"] = d.AlertPhones
	d.fieldMap["notify_on_failure"] = d.NotifyOnFailure
	d.fieldMap["enabled"] = d.Enabled
	d.fieldMap["suspended"] = d.Suspended
}

func (d dbConnection) clone(db *gorm.DB) dbConnection {
	d.dbConnectionDo.ReplaceConnPool(db.Statement.ConnPool)
	return d
}

func (d dbConnection) replaceDB(db *gorm.DB) dbConnection {
	d.dbConnectionDo.ReplaceDB(db)
	return d
}

type dbConnectionDo struct{ gen.DO }

type IDbConnectionDo interface {
	gen.SubQuery
	Debug() IDbConnectionDo
	WithContext(ctx context.Context) IDbConnectionDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() IDbConnectionDo
	WriteDB() IDbConnectionDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) IDbConnectionDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) IDbConnectionDo
	Not(conds ...gen.Condition) IDbConnectionDo
	Or(conds ...gen.Condition) IDbConnectionDo
	Select(conds ...field.Expr) IDbConnectionDo
	Where(conds ...gen.Condition) IDbConnectionDo
	Order(conds ...field.Expr) IDbConnectionDo
	Distinct(cols ...field.Expr) IDbConnectionDo
	Omit(cols ...field.Expr) IDbConnectionDo
	Join(table schema.Tabler, on ...field.Expr) IDbConnectionDo
	LeftJoin(table schema.Tabler, on ...field.Expr) IDbConnectionDo
	RightJoin(table schema.Tabler, on ...field.Expr) IDbConnectionDo
	Group(cols ...field.Expr) IDbConnectionDo
	Having(conds ...gen.Condition) IDbConnectionDo
	Limit(limit int) IDbConnectionDo
	Offset(offset int) IDbConnectionDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) IDbConnectionDo
	Unscoped() IDbConnectionDo
	Create(values ...*models.DbConnection) error
	CreateInBatches(values []*models.DbConnection, batchSize int) error
	Save(values ...*models.DbConnection) error
	First() (*models.DbConnection, error)
	Take() (*models.DbConnection, error)
	Last() (*models.DbConnection, error)
	Find() ([]*models.DbConnection, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*models.DbConnection, err error)
	FindInBatches(result *[]*models.DbConnection, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*models.DbConnection) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) IDbConnectionDo
	Assign(attrs ...field.AssignExpr) IDbConnectionDo
	Joins(fields ...field.RelationField) IDbConnectionDo
	Preload(fields ...field.RelationField) IDbConnectionDo
	FirstOrInit() (*models.DbConnection, error)
	FirstOrCreate() (*models.DbConnection, error)
	FindByPage(offset int, limit int) (result []*models.DbConnection, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Rows() (*sql.Rows, error)
	Row() *sql.Row
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) IDbConnectionDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (d dbConnectionDo) Debug() IDbConnectionDo {
	return d.withDO(d.DO.Debug())
}

func (d dbConnectionDo) WithContext(ctx context.Context) IDbConnectionDo {
	return d.withDO(d.DO.WithContext(ctx))
}

func (d dbConnectionDo) ReadDB() IDbConnectionDo {
	return d.Clauses(dbresolver.Read)
}

func (d dbConnectionDo) WriteDB() IDbConnectionDo {
	return d.Clauses(dbresolver.Write)
}

func (d dbConnectionDo) Session(config *gorm.Session) IDbConnectionDo {
	return d.withDO(d.DO.Session(config))
}

func (d dbConnectionDo) Clauses(conds ...clause.Expression) IDbConnectionDo {
	return d.withDO(d.DO.Clauses(conds...))
}

func (d dbConnectionDo) Returning(value interface{}, columns ...string) IDbConnectionDo {
	return d.withDO(d.DO.Returning(value, columns...))
}

func (d dbConnectionDo) Not(conds ...gen.Condition) IDbConnectionDo {
	return d.withDO(d.DO.Not(conds...))
}

func (d dbConnectionDo) Or(conds ...gen.Condition) IDbConnectionDo {
	return d.withDO(d.DO.Or(conds...))
}

func (d dbConnectionDo) Select(conds ...field.Expr) IDbConnectionDo {
	return d.withDO(d.DO.Select(conds...))
}

func (d dbConnectionDo) Where(conds ...gen.Condition) IDbConnectionDo {
	return d.withDO(d.DO.Where(conds...))
}

func (d dbConnectionDo) Order(conds ...field.Expr) IDbConnectionDo {
	return d.withDO(d.DO.Order(conds...))
}

func (d dbConnectionDo) Distinct(cols ...field.Expr) IDbConnectionDo {
	return d.withDO(d.DO.Distinct(cols...))
}

func (d dbConnectionDo) Omit(cols ...field.Expr) IDbConnectionDo {
	return d.withDO(d.DO.Omit(cols...))
}

func (d dbConnectionDo) Join(table schema.Tabler, on ...field.Expr) IDbConnectionDo {
	return d.withDO(d.DO.Join(table, on...))
}

func (d dbConnectionDo) LeftJoin(table schema.Tabler, on ...field.Expr) IDbConnectionDo {
	return d.withDO(d.DO.LeftJoin(table, on...))
}

func (d dbConnectionDo) RightJoin(table schema.Tabler, on ...field.Expr) IDbConnectionDo {
	return d.withDO(d.DO.RightJoin(table, on...))
}

func (d dbConnectionDo) Group(cols ...field.Expr) IDbConnectionDo {
	return d.withDO(d.DO.Group(cols...))
}

func (d dbConnectionDo) Having(conds ...gen.Condition) IDbConnectionDo {
	return d.withDO(d.DO.Having(conds...))
}

func (d dbConnectionDo) Limit(limit int) IDbConnectionDo {
	return d.withDO(d.DO.Limit(limit))
}

func (d dbConnectionDo) Offset(offset int) IDbConnectionDo {
	return d.withDO(d.DO.Offset(offset))
}

func (d dbConnectionDo) Scopes(funcs ...func(gen.Dao) gen.Dao) IDbConnectionDo {
	return d.withDO(d.DO.Scopes(funcs...))
}

func (d dbConnectionDo) Unscoped() IDbConnectionDo {
	return d.withDO(d.DO.Unscoped())
}

func (d dbConnectionDo) Create(values ...*models.DbConnection) error {
	if len(values) == 0 {
		return nil
	}
	return d.DO.Create(values)
}

func (d dbConnectionDo) CreateInBatches(values []*models.DbConnection, batchSize int) error {
	return d.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (d dbConnectionDo) Save(values ...*models.DbConnection) error {
	if len(values) == 0 {
		return nil
	}
	return d.DO.Save(values)
}

func (d dbConnectionDo) First() (*models.DbConnection, error) {
	if result, err := d.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*models.DbConnection), nil
	}
}

func (d dbConnectionDo) Take() (*models.DbConnection, error) {
	if result, err := d.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*models.DbConnection), nil
	}
}

func (d dbConnectionDo) Last() (*models.DbConnection, error) {
	if result, err := d.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*models.DbConnection), nil
	}
}

func (d dbConnectionDo) Find() ([]*models.DbConnection, error) {
	result, err := d.DO.Find()
	return result.([]*models.DbConnection), err
}

func (d dbConnectionDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*models.DbConnection, err error) {
	buf := make([]*models.DbConnection, 0, batchSize)
	err = d.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (d dbConnectionDo) FindInBatches(result *[]*models.DbConnection, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return d.DO.FindInBatches(result, batchSize, fc)
}

func (d dbConnectionDo) Attrs(attrs ...field.AssignExpr) IDbConnectionDo {
	return d.withDO(d.DO.Attrs(attrs...))
}

func (d dbConnectionDo) Assign(attrs ...field.AssignExpr) IDbConnectionDo {
	return d.withDO(d.DO.Assign(attrs...))
}

func (d dbConnectionDo) Joins(fields ...field.RelationField) IDbConnectionDo {
	for _, _f := range fields {
		d = *d.withDO(d.DO.Joins(_f))
	}
	return &d
}

func (d dbConnectionDo) Preload(fields ...field.RelationField) IDbConnectionDo {
	for _, _f := range fields {
		d = *d.withDO(d.DO.Preload(_f))
	}
	return &d
}

func (d dbConnectionDo) FirstOrInit() (*models.DbConnection, error) {
	if result, err := d.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*models.DbConnection), nil
	}
}

func (d dbConnectionDo) FirstOrCreate() (*models.DbConnection, error) {
	if result, err := d.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*models.DbConnection), nil
	}
}

func (d dbConnectionDo) FindByPage(offset int, limit int) (result []*models.DbConnection, count int64, err error) {
	result, err = d.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = d.Offset(-1).Limit(-1).Count()
	return
}

func (d dbConnectionDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = d.Count()
	if err != nil {
		return
	}

	err = d.Offset(offset).Limit(limit).Scan(result)
	return
}

func (d dbConnectionDo) Scan(result interface{}) (err error) {
	return d.DO.Scan(result)
}

func (d dbConnectionDo) Delete(models ...*models.DbConnection) (result gen.ResultInfo, err error) {
	return d.DO.Delete(models)
}

func (d *dbConnectionDo) withDO(do gen.Dao) *dbConnectionDo {
	d.DO = *do.(*gen.DO)
	return d
}
