// Code generated by gormdb2struct; DO NOT EDIT.
// This file was generated automatically to initialize SQLite DB connections.
// Warning: Manual edits may be overwritten by the generator and IDEs like GoLand may mark this as generated code.
package db

import (
	"github.com/glebarez/sqlite"
	slogGorm "github.com/orandin/slog-gorm"
	"gorm.io/gorm"
	"log/slog"
	"os"
)

var (
	DbPath = "dev/db-query-model-generator/schema.db"
	DB     *gorm.DB
)

// DbInit opens the SQLite database. If optionalFilePath is provided, it will be used instead of the default DbPath.
func DbInit(optionalFilePath ...string) {
	var filePath string
	if len(optionalFilePath) > 0 && optionalFilePath[0] != "" {
		filePath = optionalFilePath[0]
	} else {
		filePath = DbPath
	}
	slog.Info("Connecting to sqlite database", slog.String("path", filePath))
	gormDB, err := gorm.Open(sqlite.Open(filePath), &gorm.Config{Logger: slogGorm.New()})
	if err != nil {
		slog.Error(err.Error())
		os.Exit(1)
	}
	sqldb, _ := gormDB.DB()
	if err = sqldb.Ping(); err != nil {
		slog.Error("Unable to ping database: ", slog.String("error", err.Error()))
		os.Exit(1)
	}
	slog.Info("SQLite database connection established")

	// Expose the query objects for use elsewhere in the app.
	SetDefault(gormDB)
	DB = gormDB
	slog.Debug("GORM query objects (SQLite) initialized")
}
