// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package db

import (
	"context"
	"database/sql"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"chronix/internal/db/models"
)

func newFeatureRequest(db *gorm.DB, opts ...gen.DOOption) featureRequest {
	_featureRequest := featureRequest{}

	_featureRequest.featureRequestDo.UseDB(db, opts...)
	_featureRequest.featureRequestDo.UseModel(&models.FeatureRequest{})

	tableName := _featureRequest.featureRequestDo.TableName()
	_featureRequest.ALL = field.NewAsterisk(tableName)
	_featureRequest.ID = field.NewInt64(tableName, "id")
	_featureRequest.Summary = field.NewString(tableName, "summary")
	_featureRequest.Description = field.NewString(tableName, "description")
	_featureRequest.UserID = field.NewInt64(tableName, "user_id")
	_featureRequest.CreatedAt = field.NewTime(tableName, "created_at")
	_featureRequest.Status = field.NewString(tableName, "status")
	_featureRequest.FeedbackAttachments = featureRequestHasManyFeedbackAttachments{
		db: db.Session(&gorm.Session{}),

		RelationField: field.NewRelation("FeedbackAttachments", "models.FeedbackAttachment"),
	}

	_featureRequest.fillFieldMap()

	return _featureRequest
}

type featureRequest struct {
	featureRequestDo

	ALL                 field.Asterisk
	ID                  field.Int64
	Summary             field.String
	Description         field.String
	UserID              field.Int64
	CreatedAt           field.Time
	Status              field.String
	FeedbackAttachments featureRequestHasManyFeedbackAttachments

	fieldMap map[string]field.Expr
}

func (f featureRequest) Table(newTableName string) *featureRequest {
	f.featureRequestDo.UseTable(newTableName)
	return f.updateTableName(newTableName)
}

func (f featureRequest) As(alias string) *featureRequest {
	f.featureRequestDo.DO = *(f.featureRequestDo.As(alias).(*gen.DO))
	return f.updateTableName(alias)
}

func (f *featureRequest) updateTableName(table string) *featureRequest {
	f.ALL = field.NewAsterisk(table)
	f.ID = field.NewInt64(table, "id")
	f.Summary = field.NewString(table, "summary")
	f.Description = field.NewString(table, "description")
	f.UserID = field.NewInt64(table, "user_id")
	f.CreatedAt = field.NewTime(table, "created_at")
	f.Status = field.NewString(table, "status")

	f.fillFieldMap()

	return f
}

func (f *featureRequest) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := f.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (f *featureRequest) fillFieldMap() {
	f.fieldMap = make(map[string]field.Expr, 7)
	f.fieldMap["id"] = f.ID
	f.fieldMap["summary"] = f.Summary
	f.fieldMap["description"] = f.Description
	f.fieldMap["user_id"] = f.UserID
	f.fieldMap["created_at"] = f.CreatedAt
	f.fieldMap["status"] = f.Status

}

func (f featureRequest) clone(db *gorm.DB) featureRequest {
	f.featureRequestDo.ReplaceConnPool(db.Statement.ConnPool)
	f.FeedbackAttachments.db = db.Session(&gorm.Session{Initialized: true})
	f.FeedbackAttachments.db.Statement.ConnPool = db.Statement.ConnPool
	return f
}

func (f featureRequest) replaceDB(db *gorm.DB) featureRequest {
	f.featureRequestDo.ReplaceDB(db)
	f.FeedbackAttachments.db = db.Session(&gorm.Session{})
	return f
}

type featureRequestHasManyFeedbackAttachments struct {
	db *gorm.DB

	field.RelationField
}

func (a featureRequestHasManyFeedbackAttachments) Where(conds ...field.Expr) *featureRequestHasManyFeedbackAttachments {
	if len(conds) == 0 {
		return &a
	}

	exprs := make([]clause.Expression, 0, len(conds))
	for _, cond := range conds {
		exprs = append(exprs, cond.BeCond().(clause.Expression))
	}
	a.db = a.db.Clauses(clause.Where{Exprs: exprs})
	return &a
}

func (a featureRequestHasManyFeedbackAttachments) WithContext(ctx context.Context) *featureRequestHasManyFeedbackAttachments {
	a.db = a.db.WithContext(ctx)
	return &a
}

func (a featureRequestHasManyFeedbackAttachments) Session(session *gorm.Session) *featureRequestHasManyFeedbackAttachments {
	a.db = a.db.Session(session)
	return &a
}

func (a featureRequestHasManyFeedbackAttachments) Model(m *models.FeatureRequest) *featureRequestHasManyFeedbackAttachmentsTx {
	return &featureRequestHasManyFeedbackAttachmentsTx{a.db.Model(m).Association(a.Name())}
}

func (a featureRequestHasManyFeedbackAttachments) Unscoped() *featureRequestHasManyFeedbackAttachments {
	a.db = a.db.Unscoped()
	return &a
}

type featureRequestHasManyFeedbackAttachmentsTx struct{ tx *gorm.Association }

func (a featureRequestHasManyFeedbackAttachmentsTx) Find() (result []*models.FeedbackAttachment, err error) {
	return result, a.tx.Find(&result)
}

func (a featureRequestHasManyFeedbackAttachmentsTx) Append(values ...*models.FeedbackAttachment) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Append(targetValues...)
}

func (a featureRequestHasManyFeedbackAttachmentsTx) Replace(values ...*models.FeedbackAttachment) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Replace(targetValues...)
}

func (a featureRequestHasManyFeedbackAttachmentsTx) Delete(values ...*models.FeedbackAttachment) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Delete(targetValues...)
}

func (a featureRequestHasManyFeedbackAttachmentsTx) Clear() error {
	return a.tx.Clear()
}

func (a featureRequestHasManyFeedbackAttachmentsTx) Count() int64 {
	return a.tx.Count()
}

func (a featureRequestHasManyFeedbackAttachmentsTx) Unscoped() *featureRequestHasManyFeedbackAttachmentsTx {
	a.tx = a.tx.Unscoped()
	return &a
}

type featureRequestDo struct{ gen.DO }

type IFeatureRequestDo interface {
	gen.SubQuery
	Debug() IFeatureRequestDo
	WithContext(ctx context.Context) IFeatureRequestDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() IFeatureRequestDo
	WriteDB() IFeatureRequestDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) IFeatureRequestDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) IFeatureRequestDo
	Not(conds ...gen.Condition) IFeatureRequestDo
	Or(conds ...gen.Condition) IFeatureRequestDo
	Select(conds ...field.Expr) IFeatureRequestDo
	Where(conds ...gen.Condition) IFeatureRequestDo
	Order(conds ...field.Expr) IFeatureRequestDo
	Distinct(cols ...field.Expr) IFeatureRequestDo
	Omit(cols ...field.Expr) IFeatureRequestDo
	Join(table schema.Tabler, on ...field.Expr) IFeatureRequestDo
	LeftJoin(table schema.Tabler, on ...field.Expr) IFeatureRequestDo
	RightJoin(table schema.Tabler, on ...field.Expr) IFeatureRequestDo
	Group(cols ...field.Expr) IFeatureRequestDo
	Having(conds ...gen.Condition) IFeatureRequestDo
	Limit(limit int) IFeatureRequestDo
	Offset(offset int) IFeatureRequestDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) IFeatureRequestDo
	Unscoped() IFeatureRequestDo
	Create(values ...*models.FeatureRequest) error
	CreateInBatches(values []*models.FeatureRequest, batchSize int) error
	Save(values ...*models.FeatureRequest) error
	First() (*models.FeatureRequest, error)
	Take() (*models.FeatureRequest, error)
	Last() (*models.FeatureRequest, error)
	Find() ([]*models.FeatureRequest, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*models.FeatureRequest, err error)
	FindInBatches(result *[]*models.FeatureRequest, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*models.FeatureRequest) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) IFeatureRequestDo
	Assign(attrs ...field.AssignExpr) IFeatureRequestDo
	Joins(fields ...field.RelationField) IFeatureRequestDo
	Preload(fields ...field.RelationField) IFeatureRequestDo
	FirstOrInit() (*models.FeatureRequest, error)
	FirstOrCreate() (*models.FeatureRequest, error)
	FindByPage(offset int, limit int) (result []*models.FeatureRequest, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Rows() (*sql.Rows, error)
	Row() *sql.Row
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) IFeatureRequestDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (f featureRequestDo) Debug() IFeatureRequestDo {
	return f.withDO(f.DO.Debug())
}

func (f featureRequestDo) WithContext(ctx context.Context) IFeatureRequestDo {
	return f.withDO(f.DO.WithContext(ctx))
}

func (f featureRequestDo) ReadDB() IFeatureRequestDo {
	return f.Clauses(dbresolver.Read)
}

func (f featureRequestDo) WriteDB() IFeatureRequestDo {
	return f.Clauses(dbresolver.Write)
}

func (f featureRequestDo) Session(config *gorm.Session) IFeatureRequestDo {
	return f.withDO(f.DO.Session(config))
}

func (f featureRequestDo) Clauses(conds ...clause.Expression) IFeatureRequestDo {
	return f.withDO(f.DO.Clauses(conds...))
}

func (f featureRequestDo) Returning(value interface{}, columns ...string) IFeatureRequestDo {
	return f.withDO(f.DO.Returning(value, columns...))
}

func (f featureRequestDo) Not(conds ...gen.Condition) IFeatureRequestDo {
	return f.withDO(f.DO.Not(conds...))
}

func (f featureRequestDo) Or(conds ...gen.Condition) IFeatureRequestDo {
	return f.withDO(f.DO.Or(conds...))
}

func (f featureRequestDo) Select(conds ...field.Expr) IFeatureRequestDo {
	return f.withDO(f.DO.Select(conds...))
}

func (f featureRequestDo) Where(conds ...gen.Condition) IFeatureRequestDo {
	return f.withDO(f.DO.Where(conds...))
}

func (f featureRequestDo) Order(conds ...field.Expr) IFeatureRequestDo {
	return f.withDO(f.DO.Order(conds...))
}

func (f featureRequestDo) Distinct(cols ...field.Expr) IFeatureRequestDo {
	return f.withDO(f.DO.Distinct(cols...))
}

func (f featureRequestDo) Omit(cols ...field.Expr) IFeatureRequestDo {
	return f.withDO(f.DO.Omit(cols...))
}

func (f featureRequestDo) Join(table schema.Tabler, on ...field.Expr) IFeatureRequestDo {
	return f.withDO(f.DO.Join(table, on...))
}

func (f featureRequestDo) LeftJoin(table schema.Tabler, on ...field.Expr) IFeatureRequestDo {
	return f.withDO(f.DO.LeftJoin(table, on...))
}

func (f featureRequestDo) RightJoin(table schema.Tabler, on ...field.Expr) IFeatureRequestDo {
	return f.withDO(f.DO.RightJoin(table, on...))
}

func (f featureRequestDo) Group(cols ...field.Expr) IFeatureRequestDo {
	return f.withDO(f.DO.Group(cols...))
}

func (f featureRequestDo) Having(conds ...gen.Condition) IFeatureRequestDo {
	return f.withDO(f.DO.Having(conds...))
}

func (f featureRequestDo) Limit(limit int) IFeatureRequestDo {
	return f.withDO(f.DO.Limit(limit))
}

func (f featureRequestDo) Offset(offset int) IFeatureRequestDo {
	return f.withDO(f.DO.Offset(offset))
}

func (f featureRequestDo) Scopes(funcs ...func(gen.Dao) gen.Dao) IFeatureRequestDo {
	return f.withDO(f.DO.Scopes(funcs...))
}

func (f featureRequestDo) Unscoped() IFeatureRequestDo {
	return f.withDO(f.DO.Unscoped())
}

func (f featureRequestDo) Create(values ...*models.FeatureRequest) error {
	if len(values) == 0 {
		return nil
	}
	return f.DO.Create(values)
}

func (f featureRequestDo) CreateInBatches(values []*models.FeatureRequest, batchSize int) error {
	return f.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (f featureRequestDo) Save(values ...*models.FeatureRequest) error {
	if len(values) == 0 {
		return nil
	}
	return f.DO.Save(values)
}

func (f featureRequestDo) First() (*models.FeatureRequest, error) {
	if result, err := f.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*models.FeatureRequest), nil
	}
}

func (f featureRequestDo) Take() (*models.FeatureRequest, error) {
	if result, err := f.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*models.FeatureRequest), nil
	}
}

func (f featureRequestDo) Last() (*models.FeatureRequest, error) {
	if result, err := f.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*models.FeatureRequest), nil
	}
}

func (f featureRequestDo) Find() ([]*models.FeatureRequest, error) {
	result, err := f.DO.Find()
	return result.([]*models.FeatureRequest), err
}

func (f featureRequestDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*models.FeatureRequest, err error) {
	buf := make([]*models.FeatureRequest, 0, batchSize)
	err = f.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (f featureRequestDo) FindInBatches(result *[]*models.FeatureRequest, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return f.DO.FindInBatches(result, batchSize, fc)
}

func (f featureRequestDo) Attrs(attrs ...field.AssignExpr) IFeatureRequestDo {
	return f.withDO(f.DO.Attrs(attrs...))
}

func (f featureRequestDo) Assign(attrs ...field.AssignExpr) IFeatureRequestDo {
	return f.withDO(f.DO.Assign(attrs...))
}

func (f featureRequestDo) Joins(fields ...field.RelationField) IFeatureRequestDo {
	for _, _f := range fields {
		f = *f.withDO(f.DO.Joins(_f))
	}
	return &f
}

func (f featureRequestDo) Preload(fields ...field.RelationField) IFeatureRequestDo {
	for _, _f := range fields {
		f = *f.withDO(f.DO.Preload(_f))
	}
	return &f
}

func (f featureRequestDo) FirstOrInit() (*models.FeatureRequest, error) {
	if result, err := f.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*models.FeatureRequest), nil
	}
}

func (f featureRequestDo) FirstOrCreate() (*models.FeatureRequest, error) {
	if result, err := f.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*models.FeatureRequest), nil
	}
}

func (f featureRequestDo) FindByPage(offset int, limit int) (result []*models.FeatureRequest, count int64, err error) {
	result, err = f.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = f.Offset(-1).Limit(-1).Count()
	return
}

func (f featureRequestDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = f.Count()
	if err != nil {
		return
	}

	err = f.Offset(offset).Limit(limit).Scan(result)
	return
}

func (f featureRequestDo) Scan(result interface{}) (err error) {
	return f.DO.Scan(result)
}

func (f featureRequestDo) Delete(models ...*models.FeatureRequest) (result gen.ResultInfo, err error) {
	return f.DO.Delete(models)
}

func (f *featureRequestDo) withDO(do gen.Dao) *featureRequestDo {
	f.DO = *do.(*gen.DO)
	return f
}
