// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package db

import (
	"context"
	"database/sql"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"chronix/internal/db/models"
)

func newFeedbackAttachment(db *gorm.DB, opts ...gen.DOOption) feedbackAttachment {
	_feedbackAttachment := feedbackAttachment{}

	_feedbackAttachment.feedbackAttachmentDo.UseDB(db, opts...)
	_feedbackAttachment.feedbackAttachmentDo.UseModel(&models.FeedbackAttachment{})

	tableName := _feedbackAttachment.feedbackAttachmentDo.TableName()
	_feedbackAttachment.ALL = field.NewAsterisk(tableName)
	_feedbackAttachment.ID = field.NewInt64(tableName, "id")
	_feedbackAttachment.BugReportID = field.NewInt64(tableName, "bug_report_id")
	_feedbackAttachment.FeatureRequestID = field.NewInt64(tableName, "feature_request_id")
	_feedbackAttachment.FileName = field.NewString(tableName, "file_name")
	_feedbackAttachment.FilePath = field.NewString(tableName, "file_path")
	_feedbackAttachment.ContentType = field.NewString(tableName, "content_type")
	_feedbackAttachment.FileSize = field.NewInt64(tableName, "file_size")
	_feedbackAttachment.CreatedAt = field.NewTime(tableName, "created_at")

	_feedbackAttachment.fillFieldMap()

	return _feedbackAttachment
}

type feedbackAttachment struct {
	feedbackAttachmentDo

	ALL              field.Asterisk
	ID               field.Int64
	BugReportID      field.Int64
	FeatureRequestID field.Int64
	FileName         field.String
	FilePath         field.String
	ContentType      field.String
	FileSize         field.Int64
	CreatedAt        field.Time

	fieldMap map[string]field.Expr
}

func (f feedbackAttachment) Table(newTableName string) *feedbackAttachment {
	f.feedbackAttachmentDo.UseTable(newTableName)
	return f.updateTableName(newTableName)
}

func (f feedbackAttachment) As(alias string) *feedbackAttachment {
	f.feedbackAttachmentDo.DO = *(f.feedbackAttachmentDo.As(alias).(*gen.DO))
	return f.updateTableName(alias)
}

func (f *feedbackAttachment) updateTableName(table string) *feedbackAttachment {
	f.ALL = field.NewAsterisk(table)
	f.ID = field.NewInt64(table, "id")
	f.BugReportID = field.NewInt64(table, "bug_report_id")
	f.FeatureRequestID = field.NewInt64(table, "feature_request_id")
	f.FileName = field.NewString(table, "file_name")
	f.FilePath = field.NewString(table, "file_path")
	f.ContentType = field.NewString(table, "content_type")
	f.FileSize = field.NewInt64(table, "file_size")
	f.CreatedAt = field.NewTime(table, "created_at")

	f.fillFieldMap()

	return f
}

func (f *feedbackAttachment) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := f.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (f *feedbackAttachment) fillFieldMap() {
	f.fieldMap = make(map[string]field.Expr, 8)
	f.fieldMap["id"] = f.ID
	f.fieldMap["bug_report_id"] = f.BugReportID
	f.fieldMap["feature_request_id"] = f.FeatureRequestID
	f.fieldMap["file_name"] = f.FileName
	f.fieldMap["file_path"] = f.FilePath
	f.fieldMap["content_type"] = f.ContentType
	f.fieldMap["file_size"] = f.FileSize
	f.fieldMap["created_at"] = f.CreatedAt
}

func (f feedbackAttachment) clone(db *gorm.DB) feedbackAttachment {
	f.feedbackAttachmentDo.ReplaceConnPool(db.Statement.ConnPool)
	return f
}

func (f feedbackAttachment) replaceDB(db *gorm.DB) feedbackAttachment {
	f.feedbackAttachmentDo.ReplaceDB(db)
	return f
}

type feedbackAttachmentDo struct{ gen.DO }

type IFeedbackAttachmentDo interface {
	gen.SubQuery
	Debug() IFeedbackAttachmentDo
	WithContext(ctx context.Context) IFeedbackAttachmentDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() IFeedbackAttachmentDo
	WriteDB() IFeedbackAttachmentDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) IFeedbackAttachmentDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) IFeedbackAttachmentDo
	Not(conds ...gen.Condition) IFeedbackAttachmentDo
	Or(conds ...gen.Condition) IFeedbackAttachmentDo
	Select(conds ...field.Expr) IFeedbackAttachmentDo
	Where(conds ...gen.Condition) IFeedbackAttachmentDo
	Order(conds ...field.Expr) IFeedbackAttachmentDo
	Distinct(cols ...field.Expr) IFeedbackAttachmentDo
	Omit(cols ...field.Expr) IFeedbackAttachmentDo
	Join(table schema.Tabler, on ...field.Expr) IFeedbackAttachmentDo
	LeftJoin(table schema.Tabler, on ...field.Expr) IFeedbackAttachmentDo
	RightJoin(table schema.Tabler, on ...field.Expr) IFeedbackAttachmentDo
	Group(cols ...field.Expr) IFeedbackAttachmentDo
	Having(conds ...gen.Condition) IFeedbackAttachmentDo
	Limit(limit int) IFeedbackAttachmentDo
	Offset(offset int) IFeedbackAttachmentDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) IFeedbackAttachmentDo
	Unscoped() IFeedbackAttachmentDo
	Create(values ...*models.FeedbackAttachment) error
	CreateInBatches(values []*models.FeedbackAttachment, batchSize int) error
	Save(values ...*models.FeedbackAttachment) error
	First() (*models.FeedbackAttachment, error)
	Take() (*models.FeedbackAttachment, error)
	Last() (*models.FeedbackAttachment, error)
	Find() ([]*models.FeedbackAttachment, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*models.FeedbackAttachment, err error)
	FindInBatches(result *[]*models.FeedbackAttachment, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*models.FeedbackAttachment) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) IFeedbackAttachmentDo
	Assign(attrs ...field.AssignExpr) IFeedbackAttachmentDo
	Joins(fields ...field.RelationField) IFeedbackAttachmentDo
	Preload(fields ...field.RelationField) IFeedbackAttachmentDo
	FirstOrInit() (*models.FeedbackAttachment, error)
	FirstOrCreate() (*models.FeedbackAttachment, error)
	FindByPage(offset int, limit int) (result []*models.FeedbackAttachment, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Rows() (*sql.Rows, error)
	Row() *sql.Row
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) IFeedbackAttachmentDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (f feedbackAttachmentDo) Debug() IFeedbackAttachmentDo {
	return f.withDO(f.DO.Debug())
}

func (f feedbackAttachmentDo) WithContext(ctx context.Context) IFeedbackAttachmentDo {
	return f.withDO(f.DO.WithContext(ctx))
}

func (f feedbackAttachmentDo) ReadDB() IFeedbackAttachmentDo {
	return f.Clauses(dbresolver.Read)
}

func (f feedbackAttachmentDo) WriteDB() IFeedbackAttachmentDo {
	return f.Clauses(dbresolver.Write)
}

func (f feedbackAttachmentDo) Session(config *gorm.Session) IFeedbackAttachmentDo {
	return f.withDO(f.DO.Session(config))
}

func (f feedbackAttachmentDo) Clauses(conds ...clause.Expression) IFeedbackAttachmentDo {
	return f.withDO(f.DO.Clauses(conds...))
}

func (f feedbackAttachmentDo) Returning(value interface{}, columns ...string) IFeedbackAttachmentDo {
	return f.withDO(f.DO.Returning(value, columns...))
}

func (f feedbackAttachmentDo) Not(conds ...gen.Condition) IFeedbackAttachmentDo {
	return f.withDO(f.DO.Not(conds...))
}

func (f feedbackAttachmentDo) Or(conds ...gen.Condition) IFeedbackAttachmentDo {
	return f.withDO(f.DO.Or(conds...))
}

func (f feedbackAttachmentDo) Select(conds ...field.Expr) IFeedbackAttachmentDo {
	return f.withDO(f.DO.Select(conds...))
}

func (f feedbackAttachmentDo) Where(conds ...gen.Condition) IFeedbackAttachmentDo {
	return f.withDO(f.DO.Where(conds...))
}

func (f feedbackAttachmentDo) Order(conds ...field.Expr) IFeedbackAttachmentDo {
	return f.withDO(f.DO.Order(conds...))
}

func (f feedbackAttachmentDo) Distinct(cols ...field.Expr) IFeedbackAttachmentDo {
	return f.withDO(f.DO.Distinct(cols...))
}

func (f feedbackAttachmentDo) Omit(cols ...field.Expr) IFeedbackAttachmentDo {
	return f.withDO(f.DO.Omit(cols...))
}

func (f feedbackAttachmentDo) Join(table schema.Tabler, on ...field.Expr) IFeedbackAttachmentDo {
	return f.withDO(f.DO.Join(table, on...))
}

func (f feedbackAttachmentDo) LeftJoin(table schema.Tabler, on ...field.Expr) IFeedbackAttachmentDo {
	return f.withDO(f.DO.LeftJoin(table, on...))
}

func (f feedbackAttachmentDo) RightJoin(table schema.Tabler, on ...field.Expr) IFeedbackAttachmentDo {
	return f.withDO(f.DO.RightJoin(table, on...))
}

func (f feedbackAttachmentDo) Group(cols ...field.Expr) IFeedbackAttachmentDo {
	return f.withDO(f.DO.Group(cols...))
}

func (f feedbackAttachmentDo) Having(conds ...gen.Condition) IFeedbackAttachmentDo {
	return f.withDO(f.DO.Having(conds...))
}

func (f feedbackAttachmentDo) Limit(limit int) IFeedbackAttachmentDo {
	return f.withDO(f.DO.Limit(limit))
}

func (f feedbackAttachmentDo) Offset(offset int) IFeedbackAttachmentDo {
	return f.withDO(f.DO.Offset(offset))
}

func (f feedbackAttachmentDo) Scopes(funcs ...func(gen.Dao) gen.Dao) IFeedbackAttachmentDo {
	return f.withDO(f.DO.Scopes(funcs...))
}

func (f feedbackAttachmentDo) Unscoped() IFeedbackAttachmentDo {
	return f.withDO(f.DO.Unscoped())
}

func (f feedbackAttachmentDo) Create(values ...*models.FeedbackAttachment) error {
	if len(values) == 0 {
		return nil
	}
	return f.DO.Create(values)
}

func (f feedbackAttachmentDo) CreateInBatches(values []*models.FeedbackAttachment, batchSize int) error {
	return f.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (f feedbackAttachmentDo) Save(values ...*models.FeedbackAttachment) error {
	if len(values) == 0 {
		return nil
	}
	return f.DO.Save(values)
}

func (f feedbackAttachmentDo) First() (*models.FeedbackAttachment, error) {
	if result, err := f.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*models.FeedbackAttachment), nil
	}
}

func (f feedbackAttachmentDo) Take() (*models.FeedbackAttachment, error) {
	if result, err := f.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*models.FeedbackAttachment), nil
	}
}

func (f feedbackAttachmentDo) Last() (*models.FeedbackAttachment, error) {
	if result, err := f.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*models.FeedbackAttachment), nil
	}
}

func (f feedbackAttachmentDo) Find() ([]*models.FeedbackAttachment, error) {
	result, err := f.DO.Find()
	return result.([]*models.FeedbackAttachment), err
}

func (f feedbackAttachmentDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*models.FeedbackAttachment, err error) {
	buf := make([]*models.FeedbackAttachment, 0, batchSize)
	err = f.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (f feedbackAttachmentDo) FindInBatches(result *[]*models.FeedbackAttachment, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return f.DO.FindInBatches(result, batchSize, fc)
}

func (f feedbackAttachmentDo) Attrs(attrs ...field.AssignExpr) IFeedbackAttachmentDo {
	return f.withDO(f.DO.Attrs(attrs...))
}

func (f feedbackAttachmentDo) Assign(attrs ...field.AssignExpr) IFeedbackAttachmentDo {
	return f.withDO(f.DO.Assign(attrs...))
}

func (f feedbackAttachmentDo) Joins(fields ...field.RelationField) IFeedbackAttachmentDo {
	for _, _f := range fields {
		f = *f.withDO(f.DO.Joins(_f))
	}
	return &f
}

func (f feedbackAttachmentDo) Preload(fields ...field.RelationField) IFeedbackAttachmentDo {
	for _, _f := range fields {
		f = *f.withDO(f.DO.Preload(_f))
	}
	return &f
}

func (f feedbackAttachmentDo) FirstOrInit() (*models.FeedbackAttachment, error) {
	if result, err := f.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*models.FeedbackAttachment), nil
	}
}

func (f feedbackAttachmentDo) FirstOrCreate() (*models.FeedbackAttachment, error) {
	if result, err := f.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*models.FeedbackAttachment), nil
	}
}

func (f feedbackAttachmentDo) FindByPage(offset int, limit int) (result []*models.FeedbackAttachment, count int64, err error) {
	result, err = f.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = f.Offset(-1).Limit(-1).Count()
	return
}

func (f feedbackAttachmentDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = f.Count()
	if err != nil {
		return
	}

	err = f.Offset(offset).Limit(limit).Scan(result)
	return
}

func (f feedbackAttachmentDo) Scan(result interface{}) (err error) {
	return f.DO.Scan(result)
}

func (f feedbackAttachmentDo) Delete(models ...*models.FeedbackAttachment) (result gen.ResultInfo, err error) {
	return f.DO.Delete(models)
}

func (f *feedbackAttachmentDo) withDO(do gen.Dao) *feedbackAttachmentDo {
	f.DO = *do.(*gen.DO)
	return f
}
