// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package db

import (
	"context"
	"database/sql"

	"gorm.io/gorm"

	"gorm.io/gen"

	"gorm.io/plugin/dbresolver"
)

var (
	Q                        = new(Query)
	Action                   *action
	ActionStep               *actionStep
	Agent                    *agent
	AgentRegistrationRequest *agentRegistrationRequest
	AuthKey                  *authKey
	BugReport                *bugReport
	CxSetting                *cxSetting
	CxUser                   *cxUser
	DbConnection             *dbConnection
	FeatureRequest           *featureRequest
	FeedbackAttachment       *feedbackAttachment
	Job                      *job
	JobRun                   *jobRun
	JobRunEvent              *jobRunEvent
	JobRunShellIo            *jobRunShellIo
	JobRunStep               *jobRunStep
	JobRunWebtaskIo          *jobRunWebtaskIo
	JobVariable              *jobVariable
	Notification             *notification
	NotificationRecipient    *notificationRecipient
	ShellActionStep          *shellActionStep
	ShellConnection          *shellConnection
	UserActivity             *userActivity
	Webhook                  *webhook
	WebtaskActionStep        *webtaskActionStep
	WebtaskConnection        *webtaskConnection
)

func SetDefault(db *gorm.DB, opts ...gen.DOOption) {
	*Q = *Use(db, opts...)
	Action = &Q.Action
	ActionStep = &Q.ActionStep
	Agent = &Q.Agent
	AgentRegistrationRequest = &Q.AgentRegistrationRequest
	AuthKey = &Q.AuthKey
	BugReport = &Q.BugReport
	CxSetting = &Q.CxSetting
	CxUser = &Q.CxUser
	DbConnection = &Q.DbConnection
	FeatureRequest = &Q.FeatureRequest
	FeedbackAttachment = &Q.FeedbackAttachment
	Job = &Q.Job
	JobRun = &Q.JobRun
	JobRunEvent = &Q.JobRunEvent
	JobRunShellIo = &Q.JobRunShellIo
	JobRunStep = &Q.JobRunStep
	JobRunWebtaskIo = &Q.JobRunWebtaskIo
	JobVariable = &Q.JobVariable
	Notification = &Q.Notification
	NotificationRecipient = &Q.NotificationRecipient
	ShellActionStep = &Q.ShellActionStep
	ShellConnection = &Q.ShellConnection
	UserActivity = &Q.UserActivity
	Webhook = &Q.Webhook
	WebtaskActionStep = &Q.WebtaskActionStep
	WebtaskConnection = &Q.WebtaskConnection
}

func Use(db *gorm.DB, opts ...gen.DOOption) *Query {
	return &Query{
		db:                       db,
		Action:                   newAction(db, opts...),
		ActionStep:               newActionStep(db, opts...),
		Agent:                    newAgent(db, opts...),
		AgentRegistrationRequest: newAgentRegistrationRequest(db, opts...),
		AuthKey:                  newAuthKey(db, opts...),
		BugReport:                newBugReport(db, opts...),
		CxSetting:                newCxSetting(db, opts...),
		CxUser:                   newCxUser(db, opts...),
		DbConnection:             newDbConnection(db, opts...),
		FeatureRequest:           newFeatureRequest(db, opts...),
		FeedbackAttachment:       newFeedbackAttachment(db, opts...),
		Job:                      newJob(db, opts...),
		JobRun:                   newJobRun(db, opts...),
		JobRunEvent:              newJobRunEvent(db, opts...),
		JobRunShellIo:            newJobRunShellIo(db, opts...),
		JobRunStep:               newJobRunStep(db, opts...),
		JobRunWebtaskIo:          newJobRunWebtaskIo(db, opts...),
		JobVariable:              newJobVariable(db, opts...),
		Notification:             newNotification(db, opts...),
		NotificationRecipient:    newNotificationRecipient(db, opts...),
		ShellActionStep:          newShellActionStep(db, opts...),
		ShellConnection:          newShellConnection(db, opts...),
		UserActivity:             newUserActivity(db, opts...),
		Webhook:                  newWebhook(db, opts...),
		WebtaskActionStep:        newWebtaskActionStep(db, opts...),
		WebtaskConnection:        newWebtaskConnection(db, opts...),
	}
}

type Query struct {
	db *gorm.DB

	Action                   action
	ActionStep               actionStep
	Agent                    agent
	AgentRegistrationRequest agentRegistrationRequest
	AuthKey                  authKey
	BugReport                bugReport
	CxSetting                cxSetting
	CxUser                   cxUser
	DbConnection             dbConnection
	FeatureRequest           featureRequest
	FeedbackAttachment       feedbackAttachment
	Job                      job
	JobRun                   jobRun
	JobRunEvent              jobRunEvent
	JobRunShellIo            jobRunShellIo
	JobRunStep               jobRunStep
	JobRunWebtaskIo          jobRunWebtaskIo
	JobVariable              jobVariable
	Notification             notification
	NotificationRecipient    notificationRecipient
	ShellActionStep          shellActionStep
	ShellConnection          shellConnection
	UserActivity             userActivity
	Webhook                  webhook
	WebtaskActionStep        webtaskActionStep
	WebtaskConnection        webtaskConnection
}

func (q *Query) Available() bool { return q.db != nil }

func (q *Query) clone(db *gorm.DB) *Query {
	return &Query{
		db:                       db,
		Action:                   q.Action.clone(db),
		ActionStep:               q.ActionStep.clone(db),
		Agent:                    q.Agent.clone(db),
		AgentRegistrationRequest: q.AgentRegistrationRequest.clone(db),
		AuthKey:                  q.AuthKey.clone(db),
		BugReport:                q.BugReport.clone(db),
		CxSetting:                q.CxSetting.clone(db),
		CxUser:                   q.CxUser.clone(db),
		DbConnection:             q.DbConnection.clone(db),
		FeatureRequest:           q.FeatureRequest.clone(db),
		FeedbackAttachment:       q.FeedbackAttachment.clone(db),
		Job:                      q.Job.clone(db),
		JobRun:                   q.JobRun.clone(db),
		JobRunEvent:              q.JobRunEvent.clone(db),
		JobRunShellIo:            q.JobRunShellIo.clone(db),
		JobRunStep:               q.JobRunStep.clone(db),
		JobRunWebtaskIo:          q.JobRunWebtaskIo.clone(db),
		JobVariable:              q.JobVariable.clone(db),
		Notification:             q.Notification.clone(db),
		NotificationRecipient:    q.NotificationRecipient.clone(db),
		ShellActionStep:          q.ShellActionStep.clone(db),
		ShellConnection:          q.ShellConnection.clone(db),
		UserActivity:             q.UserActivity.clone(db),
		Webhook:                  q.Webhook.clone(db),
		WebtaskActionStep:        q.WebtaskActionStep.clone(db),
		WebtaskConnection:        q.WebtaskConnection.clone(db),
	}
}

func (q *Query) ReadDB() *Query {
	return q.ReplaceDB(q.db.Clauses(dbresolver.Read))
}

func (q *Query) WriteDB() *Query {
	return q.ReplaceDB(q.db.Clauses(dbresolver.Write))
}

func (q *Query) ReplaceDB(db *gorm.DB) *Query {
	return &Query{
		db:                       db,
		Action:                   q.Action.replaceDB(db),
		ActionStep:               q.ActionStep.replaceDB(db),
		Agent:                    q.Agent.replaceDB(db),
		AgentRegistrationRequest: q.AgentRegistrationRequest.replaceDB(db),
		AuthKey:                  q.AuthKey.replaceDB(db),
		BugReport:                q.BugReport.replaceDB(db),
		CxSetting:                q.CxSetting.replaceDB(db),
		CxUser:                   q.CxUser.replaceDB(db),
		DbConnection:             q.DbConnection.replaceDB(db),
		FeatureRequest:           q.FeatureRequest.replaceDB(db),
		FeedbackAttachment:       q.FeedbackAttachment.replaceDB(db),
		Job:                      q.Job.replaceDB(db),
		JobRun:                   q.JobRun.replaceDB(db),
		JobRunEvent:              q.JobRunEvent.replaceDB(db),
		JobRunShellIo:            q.JobRunShellIo.replaceDB(db),
		JobRunStep:               q.JobRunStep.replaceDB(db),
		JobRunWebtaskIo:          q.JobRunWebtaskIo.replaceDB(db),
		JobVariable:              q.JobVariable.replaceDB(db),
		Notification:             q.Notification.replaceDB(db),
		NotificationRecipient:    q.NotificationRecipient.replaceDB(db),
		ShellActionStep:          q.ShellActionStep.replaceDB(db),
		ShellConnection:          q.ShellConnection.replaceDB(db),
		UserActivity:             q.UserActivity.replaceDB(db),
		Webhook:                  q.Webhook.replaceDB(db),
		WebtaskActionStep:        q.WebtaskActionStep.replaceDB(db),
		WebtaskConnection:        q.WebtaskConnection.replaceDB(db),
	}
}

type queryCtx struct {
	Action                   IActionDo
	ActionStep               IActionStepDo
	Agent                    IAgentDo
	AgentRegistrationRequest IAgentRegistrationRequestDo
	AuthKey                  IAuthKeyDo
	BugReport                IBugReportDo
	CxSetting                ICxSettingDo
	CxUser                   ICxUserDo
	DbConnection             IDbConnectionDo
	FeatureRequest           IFeatureRequestDo
	FeedbackAttachment       IFeedbackAttachmentDo
	Job                      IJobDo
	JobRun                   IJobRunDo
	JobRunEvent              IJobRunEventDo
	JobRunShellIo            IJobRunShellIoDo
	JobRunStep               IJobRunStepDo
	JobRunWebtaskIo          IJobRunWebtaskIoDo
	JobVariable              IJobVariableDo
	Notification             INotificationDo
	NotificationRecipient    INotificationRecipientDo
	ShellActionStep          IShellActionStepDo
	ShellConnection          IShellConnectionDo
	UserActivity             IUserActivityDo
	Webhook                  IWebhookDo
	WebtaskActionStep        IWebtaskActionStepDo
	WebtaskConnection        IWebtaskConnectionDo
}

func (q *Query) WithContext(ctx context.Context) *queryCtx {
	return &queryCtx{
		Action:                   q.Action.WithContext(ctx),
		ActionStep:               q.ActionStep.WithContext(ctx),
		Agent:                    q.Agent.WithContext(ctx),
		AgentRegistrationRequest: q.AgentRegistrationRequest.WithContext(ctx),
		AuthKey:                  q.AuthKey.WithContext(ctx),
		BugReport:                q.BugReport.WithContext(ctx),
		CxSetting:                q.CxSetting.WithContext(ctx),
		CxUser:                   q.CxUser.WithContext(ctx),
		DbConnection:             q.DbConnection.WithContext(ctx),
		FeatureRequest:           q.FeatureRequest.WithContext(ctx),
		FeedbackAttachment:       q.FeedbackAttachment.WithContext(ctx),
		Job:                      q.Job.WithContext(ctx),
		JobRun:                   q.JobRun.WithContext(ctx),
		JobRunEvent:              q.JobRunEvent.WithContext(ctx),
		JobRunShellIo:            q.JobRunShellIo.WithContext(ctx),
		JobRunStep:               q.JobRunStep.WithContext(ctx),
		JobRunWebtaskIo:          q.JobRunWebtaskIo.WithContext(ctx),
		JobVariable:              q.JobVariable.WithContext(ctx),
		Notification:             q.Notification.WithContext(ctx),
		NotificationRecipient:    q.NotificationRecipient.WithContext(ctx),
		ShellActionStep:          q.ShellActionStep.WithContext(ctx),
		ShellConnection:          q.ShellConnection.WithContext(ctx),
		UserActivity:             q.UserActivity.WithContext(ctx),
		Webhook:                  q.Webhook.WithContext(ctx),
		WebtaskActionStep:        q.WebtaskActionStep.WithContext(ctx),
		WebtaskConnection:        q.WebtaskConnection.WithContext(ctx),
	}
}

func (q *Query) Transaction(fc func(tx *Query) error, opts ...*sql.TxOptions) error {
	return q.db.Transaction(func(tx *gorm.DB) error { return fc(q.clone(tx)) }, opts...)
}

func (q *Query) Begin(opts ...*sql.TxOptions) *QueryTx {
	tx := q.db.Begin(opts...)
	return &QueryTx{Query: q.clone(tx), Error: tx.Error}
}

type QueryTx struct {
	*Query
	Error error
}

func (q *QueryTx) Commit() error {
	return q.db.Commit().Error
}

func (q *QueryTx) Rollback() error {
	return q.db.Rollback().Error
}

func (q *QueryTx) SavePoint(name string) error {
	return q.db.SavePoint(name).Error
}

func (q *QueryTx) RollbackTo(name string) error {
	return q.db.RollbackTo(name).Error
}
