// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package db

import (
	"context"
	"database/sql"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"chronix/internal/db/models"
)

func newJobRunShellIo(db *gorm.DB, opts ...gen.DOOption) jobRunShellIo {
	_jobRunShellIo := jobRunShellIo{}

	_jobRunShellIo.jobRunShellIoDo.UseDB(db, opts...)
	_jobRunShellIo.jobRunShellIoDo.UseModel(&models.JobRunShellIo{})

	tableName := _jobRunShellIo.jobRunShellIoDo.TableName()
	_jobRunShellIo.ALL = field.NewAsterisk(tableName)
	_jobRunShellIo.ID = field.NewInt64(tableName, "id")
	_jobRunShellIo.StepID = field.NewInt64(tableName, "step_id")
	_jobRunShellIo.StdoutText = field.NewString(tableName, "stdout_text")
	_jobRunShellIo.StderrText = field.NewString(tableName, "stderr_text")
	_jobRunShellIo.StdoutTruncated = field.NewBool(tableName, "stdout_truncated")
	_jobRunShellIo.StderrTruncated = field.NewBool(tableName, "stderr_truncated")
	_jobRunShellIo.StdoutBytes = field.NewInt64(tableName, "stdout_bytes")
	_jobRunShellIo.StderrBytes = field.NewInt64(tableName, "stderr_bytes")
	_jobRunShellIo.StdoutTotalBytes = field.NewInt64(tableName, "stdout_total_bytes")
	_jobRunShellIo.StderrTotalBytes = field.NewInt64(tableName, "stderr_total_bytes")

	_jobRunShellIo.fillFieldMap()

	return _jobRunShellIo
}

type jobRunShellIo struct {
	jobRunShellIoDo

	ALL              field.Asterisk
	ID               field.Int64
	StepID           field.Int64
	StdoutText       field.String
	StderrText       field.String
	StdoutTruncated  field.Bool
	StderrTruncated  field.Bool
	StdoutBytes      field.Int64
	StderrBytes      field.Int64
	StdoutTotalBytes field.Int64
	StderrTotalBytes field.Int64

	fieldMap map[string]field.Expr
}

func (j jobRunShellIo) Table(newTableName string) *jobRunShellIo {
	j.jobRunShellIoDo.UseTable(newTableName)
	return j.updateTableName(newTableName)
}

func (j jobRunShellIo) As(alias string) *jobRunShellIo {
	j.jobRunShellIoDo.DO = *(j.jobRunShellIoDo.As(alias).(*gen.DO))
	return j.updateTableName(alias)
}

func (j *jobRunShellIo) updateTableName(table string) *jobRunShellIo {
	j.ALL = field.NewAsterisk(table)
	j.ID = field.NewInt64(table, "id")
	j.StepID = field.NewInt64(table, "step_id")
	j.StdoutText = field.NewString(table, "stdout_text")
	j.StderrText = field.NewString(table, "stderr_text")
	j.StdoutTruncated = field.NewBool(table, "stdout_truncated")
	j.StderrTruncated = field.NewBool(table, "stderr_truncated")
	j.StdoutBytes = field.NewInt64(table, "stdout_bytes")
	j.StderrBytes = field.NewInt64(table, "stderr_bytes")
	j.StdoutTotalBytes = field.NewInt64(table, "stdout_total_bytes")
	j.StderrTotalBytes = field.NewInt64(table, "stderr_total_bytes")

	j.fillFieldMap()

	return j
}

func (j *jobRunShellIo) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := j.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (j *jobRunShellIo) fillFieldMap() {
	j.fieldMap = make(map[string]field.Expr, 10)
	j.fieldMap["id"] = j.ID
	j.fieldMap["step_id"] = j.StepID
	j.fieldMap["stdout_text"] = j.StdoutText
	j.fieldMap["stderr_text"] = j.StderrText
	j.fieldMap["stdout_truncated"] = j.StdoutTruncated
	j.fieldMap["stderr_truncated"] = j.StderrTruncated
	j.fieldMap["stdout_bytes"] = j.StdoutBytes
	j.fieldMap["stderr_bytes"] = j.StderrBytes
	j.fieldMap["stdout_total_bytes"] = j.StdoutTotalBytes
	j.fieldMap["stderr_total_bytes"] = j.StderrTotalBytes
}

func (j jobRunShellIo) clone(db *gorm.DB) jobRunShellIo {
	j.jobRunShellIoDo.ReplaceConnPool(db.Statement.ConnPool)
	return j
}

func (j jobRunShellIo) replaceDB(db *gorm.DB) jobRunShellIo {
	j.jobRunShellIoDo.ReplaceDB(db)
	return j
}

type jobRunShellIoDo struct{ gen.DO }

type IJobRunShellIoDo interface {
	gen.SubQuery
	Debug() IJobRunShellIoDo
	WithContext(ctx context.Context) IJobRunShellIoDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() IJobRunShellIoDo
	WriteDB() IJobRunShellIoDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) IJobRunShellIoDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) IJobRunShellIoDo
	Not(conds ...gen.Condition) IJobRunShellIoDo
	Or(conds ...gen.Condition) IJobRunShellIoDo
	Select(conds ...field.Expr) IJobRunShellIoDo
	Where(conds ...gen.Condition) IJobRunShellIoDo
	Order(conds ...field.Expr) IJobRunShellIoDo
	Distinct(cols ...field.Expr) IJobRunShellIoDo
	Omit(cols ...field.Expr) IJobRunShellIoDo
	Join(table schema.Tabler, on ...field.Expr) IJobRunShellIoDo
	LeftJoin(table schema.Tabler, on ...field.Expr) IJobRunShellIoDo
	RightJoin(table schema.Tabler, on ...field.Expr) IJobRunShellIoDo
	Group(cols ...field.Expr) IJobRunShellIoDo
	Having(conds ...gen.Condition) IJobRunShellIoDo
	Limit(limit int) IJobRunShellIoDo
	Offset(offset int) IJobRunShellIoDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) IJobRunShellIoDo
	Unscoped() IJobRunShellIoDo
	Create(values ...*models.JobRunShellIo) error
	CreateInBatches(values []*models.JobRunShellIo, batchSize int) error
	Save(values ...*models.JobRunShellIo) error
	First() (*models.JobRunShellIo, error)
	Take() (*models.JobRunShellIo, error)
	Last() (*models.JobRunShellIo, error)
	Find() ([]*models.JobRunShellIo, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*models.JobRunShellIo, err error)
	FindInBatches(result *[]*models.JobRunShellIo, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*models.JobRunShellIo) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) IJobRunShellIoDo
	Assign(attrs ...field.AssignExpr) IJobRunShellIoDo
	Joins(fields ...field.RelationField) IJobRunShellIoDo
	Preload(fields ...field.RelationField) IJobRunShellIoDo
	FirstOrInit() (*models.JobRunShellIo, error)
	FirstOrCreate() (*models.JobRunShellIo, error)
	FindByPage(offset int, limit int) (result []*models.JobRunShellIo, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Rows() (*sql.Rows, error)
	Row() *sql.Row
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) IJobRunShellIoDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (j jobRunShellIoDo) Debug() IJobRunShellIoDo {
	return j.withDO(j.DO.Debug())
}

func (j jobRunShellIoDo) WithContext(ctx context.Context) IJobRunShellIoDo {
	return j.withDO(j.DO.WithContext(ctx))
}

func (j jobRunShellIoDo) ReadDB() IJobRunShellIoDo {
	return j.Clauses(dbresolver.Read)
}

func (j jobRunShellIoDo) WriteDB() IJobRunShellIoDo {
	return j.Clauses(dbresolver.Write)
}

func (j jobRunShellIoDo) Session(config *gorm.Session) IJobRunShellIoDo {
	return j.withDO(j.DO.Session(config))
}

func (j jobRunShellIoDo) Clauses(conds ...clause.Expression) IJobRunShellIoDo {
	return j.withDO(j.DO.Clauses(conds...))
}

func (j jobRunShellIoDo) Returning(value interface{}, columns ...string) IJobRunShellIoDo {
	return j.withDO(j.DO.Returning(value, columns...))
}

func (j jobRunShellIoDo) Not(conds ...gen.Condition) IJobRunShellIoDo {
	return j.withDO(j.DO.Not(conds...))
}

func (j jobRunShellIoDo) Or(conds ...gen.Condition) IJobRunShellIoDo {
	return j.withDO(j.DO.Or(conds...))
}

func (j jobRunShellIoDo) Select(conds ...field.Expr) IJobRunShellIoDo {
	return j.withDO(j.DO.Select(conds...))
}

func (j jobRunShellIoDo) Where(conds ...gen.Condition) IJobRunShellIoDo {
	return j.withDO(j.DO.Where(conds...))
}

func (j jobRunShellIoDo) Order(conds ...field.Expr) IJobRunShellIoDo {
	return j.withDO(j.DO.Order(conds...))
}

func (j jobRunShellIoDo) Distinct(cols ...field.Expr) IJobRunShellIoDo {
	return j.withDO(j.DO.Distinct(cols...))
}

func (j jobRunShellIoDo) Omit(cols ...field.Expr) IJobRunShellIoDo {
	return j.withDO(j.DO.Omit(cols...))
}

func (j jobRunShellIoDo) Join(table schema.Tabler, on ...field.Expr) IJobRunShellIoDo {
	return j.withDO(j.DO.Join(table, on...))
}

func (j jobRunShellIoDo) LeftJoin(table schema.Tabler, on ...field.Expr) IJobRunShellIoDo {
	return j.withDO(j.DO.LeftJoin(table, on...))
}

func (j jobRunShellIoDo) RightJoin(table schema.Tabler, on ...field.Expr) IJobRunShellIoDo {
	return j.withDO(j.DO.RightJoin(table, on...))
}

func (j jobRunShellIoDo) Group(cols ...field.Expr) IJobRunShellIoDo {
	return j.withDO(j.DO.Group(cols...))
}

func (j jobRunShellIoDo) Having(conds ...gen.Condition) IJobRunShellIoDo {
	return j.withDO(j.DO.Having(conds...))
}

func (j jobRunShellIoDo) Limit(limit int) IJobRunShellIoDo {
	return j.withDO(j.DO.Limit(limit))
}

func (j jobRunShellIoDo) Offset(offset int) IJobRunShellIoDo {
	return j.withDO(j.DO.Offset(offset))
}

func (j jobRunShellIoDo) Scopes(funcs ...func(gen.Dao) gen.Dao) IJobRunShellIoDo {
	return j.withDO(j.DO.Scopes(funcs...))
}

func (j jobRunShellIoDo) Unscoped() IJobRunShellIoDo {
	return j.withDO(j.DO.Unscoped())
}

func (j jobRunShellIoDo) Create(values ...*models.JobRunShellIo) error {
	if len(values) == 0 {
		return nil
	}
	return j.DO.Create(values)
}

func (j jobRunShellIoDo) CreateInBatches(values []*models.JobRunShellIo, batchSize int) error {
	return j.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (j jobRunShellIoDo) Save(values ...*models.JobRunShellIo) error {
	if len(values) == 0 {
		return nil
	}
	return j.DO.Save(values)
}

func (j jobRunShellIoDo) First() (*models.JobRunShellIo, error) {
	if result, err := j.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*models.JobRunShellIo), nil
	}
}

func (j jobRunShellIoDo) Take() (*models.JobRunShellIo, error) {
	if result, err := j.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*models.JobRunShellIo), nil
	}
}

func (j jobRunShellIoDo) Last() (*models.JobRunShellIo, error) {
	if result, err := j.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*models.JobRunShellIo), nil
	}
}

func (j jobRunShellIoDo) Find() ([]*models.JobRunShellIo, error) {
	result, err := j.DO.Find()
	return result.([]*models.JobRunShellIo), err
}

func (j jobRunShellIoDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*models.JobRunShellIo, err error) {
	buf := make([]*models.JobRunShellIo, 0, batchSize)
	err = j.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (j jobRunShellIoDo) FindInBatches(result *[]*models.JobRunShellIo, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return j.DO.FindInBatches(result, batchSize, fc)
}

func (j jobRunShellIoDo) Attrs(attrs ...field.AssignExpr) IJobRunShellIoDo {
	return j.withDO(j.DO.Attrs(attrs...))
}

func (j jobRunShellIoDo) Assign(attrs ...field.AssignExpr) IJobRunShellIoDo {
	return j.withDO(j.DO.Assign(attrs...))
}

func (j jobRunShellIoDo) Joins(fields ...field.RelationField) IJobRunShellIoDo {
	for _, _f := range fields {
		j = *j.withDO(j.DO.Joins(_f))
	}
	return &j
}

func (j jobRunShellIoDo) Preload(fields ...field.RelationField) IJobRunShellIoDo {
	for _, _f := range fields {
		j = *j.withDO(j.DO.Preload(_f))
	}
	return &j
}

func (j jobRunShellIoDo) FirstOrInit() (*models.JobRunShellIo, error) {
	if result, err := j.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*models.JobRunShellIo), nil
	}
}

func (j jobRunShellIoDo) FirstOrCreate() (*models.JobRunShellIo, error) {
	if result, err := j.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*models.JobRunShellIo), nil
	}
}

func (j jobRunShellIoDo) FindByPage(offset int, limit int) (result []*models.JobRunShellIo, count int64, err error) {
	result, err = j.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = j.Offset(-1).Limit(-1).Count()
	return
}

func (j jobRunShellIoDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = j.Count()
	if err != nil {
		return
	}

	err = j.Offset(offset).Limit(limit).Scan(result)
	return
}

func (j jobRunShellIoDo) Scan(result interface{}) (err error) {
	return j.DO.Scan(result)
}

func (j jobRunShellIoDo) Delete(models ...*models.JobRunShellIo) (result gen.ResultInfo, err error) {
	return j.DO.Delete(models)
}

func (j *jobRunShellIoDo) withDO(do gen.Dao) *jobRunShellIoDo {
	j.DO = *do.(*gen.DO)
	return j
}
