// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package db

import (
	"context"
	"database/sql"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"chronix/internal/db/models"
)

func newJobRun(db *gorm.DB, opts ...gen.DOOption) jobRun {
	_jobRun := jobRun{}

	_jobRun.jobRunDo.UseDB(db, opts...)
	_jobRun.jobRunDo.UseModel(&models.JobRun{})

	tableName := _jobRun.jobRunDo.TableName()
	_jobRun.ALL = field.NewAsterisk(tableName)
	_jobRun.ID = field.NewInt64(tableName, "id")
	_jobRun.RunUID = field.NewString(tableName, "run_uid")
	_jobRun.JobID = field.NewInt64(tableName, "job_id")
	_jobRun.JobName = field.NewString(tableName, "job_name")
	_jobRun.ConnectionID = field.NewInt64(tableName, "connection_id")
	_jobRun.ActionID = field.NewInt64(tableName, "action_id")
	_jobRun.ConnectionKind = field.NewString(tableName, "connection_kind")
	_jobRun.ShellConnectionID = field.NewInt64(tableName, "shell_connection_id")
	_jobRun.WebtaskConnectionID = field.NewInt64(tableName, "webtask_connection_id")
	_jobRun.QueuedAt = field.NewTime(tableName, "queued_at")
	_jobRun.StartedAt = field.NewTime(tableName, "started_at")
	_jobRun.FinishedAt = field.NewTime(tableName, "finished_at")
	_jobRun.Status = field.NewString(tableName, "status")
	_jobRun.TriggeredBy = field.NewInt64(tableName, "triggered_by")
	_jobRun.TriggerSource = field.NewString(tableName, "trigger_source")
	_jobRun.Message = field.NewString(tableName, "message")
	_jobRun.RowsAffected = field.NewInt64(tableName, "rows_affected")
	_jobRun.ErrorCode = field.NewString(tableName, "error_code")
	_jobRun.ErrorDetails = field.NewString(tableName, "error_details")
	_jobRun.Summary = field.NewField(tableName, "summary")

	_jobRun.fillFieldMap()

	return _jobRun
}

type jobRun struct {
	jobRunDo

	ALL                 field.Asterisk
	ID                  field.Int64
	RunUID              field.String
	JobID               field.Int64
	JobName             field.String
	ConnectionID        field.Int64
	ActionID            field.Int64
	ConnectionKind      field.String
	ShellConnectionID   field.Int64
	WebtaskConnectionID field.Int64
	QueuedAt            field.Time
	StartedAt           field.Time
	FinishedAt          field.Time
	Status              field.String
	TriggeredBy         field.Int64
	TriggerSource       field.String
	Message             field.String
	RowsAffected        field.Int64
	ErrorCode           field.String
	ErrorDetails        field.String
	Summary             field.Field

	fieldMap map[string]field.Expr
}

func (j jobRun) Table(newTableName string) *jobRun {
	j.jobRunDo.UseTable(newTableName)
	return j.updateTableName(newTableName)
}

func (j jobRun) As(alias string) *jobRun {
	j.jobRunDo.DO = *(j.jobRunDo.As(alias).(*gen.DO))
	return j.updateTableName(alias)
}

func (j *jobRun) updateTableName(table string) *jobRun {
	j.ALL = field.NewAsterisk(table)
	j.ID = field.NewInt64(table, "id")
	j.RunUID = field.NewString(table, "run_uid")
	j.JobID = field.NewInt64(table, "job_id")
	j.JobName = field.NewString(table, "job_name")
	j.ConnectionID = field.NewInt64(table, "connection_id")
	j.ActionID = field.NewInt64(table, "action_id")
	j.ConnectionKind = field.NewString(table, "connection_kind")
	j.ShellConnectionID = field.NewInt64(table, "shell_connection_id")
	j.WebtaskConnectionID = field.NewInt64(table, "webtask_connection_id")
	j.QueuedAt = field.NewTime(table, "queued_at")
	j.StartedAt = field.NewTime(table, "started_at")
	j.FinishedAt = field.NewTime(table, "finished_at")
	j.Status = field.NewString(table, "status")
	j.TriggeredBy = field.NewInt64(table, "triggered_by")
	j.TriggerSource = field.NewString(table, "trigger_source")
	j.Message = field.NewString(table, "message")
	j.RowsAffected = field.NewInt64(table, "rows_affected")
	j.ErrorCode = field.NewString(table, "error_code")
	j.ErrorDetails = field.NewString(table, "error_details")
	j.Summary = field.NewField(table, "summary")

	j.fillFieldMap()

	return j
}

func (j *jobRun) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := j.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (j *jobRun) fillFieldMap() {
	j.fieldMap = make(map[string]field.Expr, 20)
	j.fieldMap["id"] = j.ID
	j.fieldMap["run_uid"] = j.RunUID
	j.fieldMap["job_id"] = j.JobID
	j.fieldMap["job_name"] = j.JobName
	j.fieldMap["connection_id"] = j.ConnectionID
	j.fieldMap["action_id"] = j.ActionID
	j.fieldMap["connection_kind"] = j.ConnectionKind
	j.fieldMap["shell_connection_id"] = j.ShellConnectionID
	j.fieldMap["webtask_connection_id"] = j.WebtaskConnectionID
	j.fieldMap["queued_at"] = j.QueuedAt
	j.fieldMap["started_at"] = j.StartedAt
	j.fieldMap["finished_at"] = j.FinishedAt
	j.fieldMap["status"] = j.Status
	j.fieldMap["triggered_by"] = j.TriggeredBy
	j.fieldMap["trigger_source"] = j.TriggerSource
	j.fieldMap["message"] = j.Message
	j.fieldMap["rows_affected"] = j.RowsAffected
	j.fieldMap["error_code"] = j.ErrorCode
	j.fieldMap["error_details"] = j.ErrorDetails
	j.fieldMap["summary"] = j.Summary
}

func (j jobRun) clone(db *gorm.DB) jobRun {
	j.jobRunDo.ReplaceConnPool(db.Statement.ConnPool)
	return j
}

func (j jobRun) replaceDB(db *gorm.DB) jobRun {
	j.jobRunDo.ReplaceDB(db)
	return j
}

type jobRunDo struct{ gen.DO }

type IJobRunDo interface {
	gen.SubQuery
	Debug() IJobRunDo
	WithContext(ctx context.Context) IJobRunDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() IJobRunDo
	WriteDB() IJobRunDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) IJobRunDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) IJobRunDo
	Not(conds ...gen.Condition) IJobRunDo
	Or(conds ...gen.Condition) IJobRunDo
	Select(conds ...field.Expr) IJobRunDo
	Where(conds ...gen.Condition) IJobRunDo
	Order(conds ...field.Expr) IJobRunDo
	Distinct(cols ...field.Expr) IJobRunDo
	Omit(cols ...field.Expr) IJobRunDo
	Join(table schema.Tabler, on ...field.Expr) IJobRunDo
	LeftJoin(table schema.Tabler, on ...field.Expr) IJobRunDo
	RightJoin(table schema.Tabler, on ...field.Expr) IJobRunDo
	Group(cols ...field.Expr) IJobRunDo
	Having(conds ...gen.Condition) IJobRunDo
	Limit(limit int) IJobRunDo
	Offset(offset int) IJobRunDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) IJobRunDo
	Unscoped() IJobRunDo
	Create(values ...*models.JobRun) error
	CreateInBatches(values []*models.JobRun, batchSize int) error
	Save(values ...*models.JobRun) error
	First() (*models.JobRun, error)
	Take() (*models.JobRun, error)
	Last() (*models.JobRun, error)
	Find() ([]*models.JobRun, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*models.JobRun, err error)
	FindInBatches(result *[]*models.JobRun, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*models.JobRun) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) IJobRunDo
	Assign(attrs ...field.AssignExpr) IJobRunDo
	Joins(fields ...field.RelationField) IJobRunDo
	Preload(fields ...field.RelationField) IJobRunDo
	FirstOrInit() (*models.JobRun, error)
	FirstOrCreate() (*models.JobRun, error)
	FindByPage(offset int, limit int) (result []*models.JobRun, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Rows() (*sql.Rows, error)
	Row() *sql.Row
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) IJobRunDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (j jobRunDo) Debug() IJobRunDo {
	return j.withDO(j.DO.Debug())
}

func (j jobRunDo) WithContext(ctx context.Context) IJobRunDo {
	return j.withDO(j.DO.WithContext(ctx))
}

func (j jobRunDo) ReadDB() IJobRunDo {
	return j.Clauses(dbresolver.Read)
}

func (j jobRunDo) WriteDB() IJobRunDo {
	return j.Clauses(dbresolver.Write)
}

func (j jobRunDo) Session(config *gorm.Session) IJobRunDo {
	return j.withDO(j.DO.Session(config))
}

func (j jobRunDo) Clauses(conds ...clause.Expression) IJobRunDo {
	return j.withDO(j.DO.Clauses(conds...))
}

func (j jobRunDo) Returning(value interface{}, columns ...string) IJobRunDo {
	return j.withDO(j.DO.Returning(value, columns...))
}

func (j jobRunDo) Not(conds ...gen.Condition) IJobRunDo {
	return j.withDO(j.DO.Not(conds...))
}

func (j jobRunDo) Or(conds ...gen.Condition) IJobRunDo {
	return j.withDO(j.DO.Or(conds...))
}

func (j jobRunDo) Select(conds ...field.Expr) IJobRunDo {
	return j.withDO(j.DO.Select(conds...))
}

func (j jobRunDo) Where(conds ...gen.Condition) IJobRunDo {
	return j.withDO(j.DO.Where(conds...))
}

func (j jobRunDo) Order(conds ...field.Expr) IJobRunDo {
	return j.withDO(j.DO.Order(conds...))
}

func (j jobRunDo) Distinct(cols ...field.Expr) IJobRunDo {
	return j.withDO(j.DO.Distinct(cols...))
}

func (j jobRunDo) Omit(cols ...field.Expr) IJobRunDo {
	return j.withDO(j.DO.Omit(cols...))
}

func (j jobRunDo) Join(table schema.Tabler, on ...field.Expr) IJobRunDo {
	return j.withDO(j.DO.Join(table, on...))
}

func (j jobRunDo) LeftJoin(table schema.Tabler, on ...field.Expr) IJobRunDo {
	return j.withDO(j.DO.LeftJoin(table, on...))
}

func (j jobRunDo) RightJoin(table schema.Tabler, on ...field.Expr) IJobRunDo {
	return j.withDO(j.DO.RightJoin(table, on...))
}

func (j jobRunDo) Group(cols ...field.Expr) IJobRunDo {
	return j.withDO(j.DO.Group(cols...))
}

func (j jobRunDo) Having(conds ...gen.Condition) IJobRunDo {
	return j.withDO(j.DO.Having(conds...))
}

func (j jobRunDo) Limit(limit int) IJobRunDo {
	return j.withDO(j.DO.Limit(limit))
}

func (j jobRunDo) Offset(offset int) IJobRunDo {
	return j.withDO(j.DO.Offset(offset))
}

func (j jobRunDo) Scopes(funcs ...func(gen.Dao) gen.Dao) IJobRunDo {
	return j.withDO(j.DO.Scopes(funcs...))
}

func (j jobRunDo) Unscoped() IJobRunDo {
	return j.withDO(j.DO.Unscoped())
}

func (j jobRunDo) Create(values ...*models.JobRun) error {
	if len(values) == 0 {
		return nil
	}
	return j.DO.Create(values)
}

func (j jobRunDo) CreateInBatches(values []*models.JobRun, batchSize int) error {
	return j.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (j jobRunDo) Save(values ...*models.JobRun) error {
	if len(values) == 0 {
		return nil
	}
	return j.DO.Save(values)
}

func (j jobRunDo) First() (*models.JobRun, error) {
	if result, err := j.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*models.JobRun), nil
	}
}

func (j jobRunDo) Take() (*models.JobRun, error) {
	if result, err := j.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*models.JobRun), nil
	}
}

func (j jobRunDo) Last() (*models.JobRun, error) {
	if result, err := j.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*models.JobRun), nil
	}
}

func (j jobRunDo) Find() ([]*models.JobRun, error) {
	result, err := j.DO.Find()
	return result.([]*models.JobRun), err
}

func (j jobRunDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*models.JobRun, err error) {
	buf := make([]*models.JobRun, 0, batchSize)
	err = j.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (j jobRunDo) FindInBatches(result *[]*models.JobRun, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return j.DO.FindInBatches(result, batchSize, fc)
}

func (j jobRunDo) Attrs(attrs ...field.AssignExpr) IJobRunDo {
	return j.withDO(j.DO.Attrs(attrs...))
}

func (j jobRunDo) Assign(attrs ...field.AssignExpr) IJobRunDo {
	return j.withDO(j.DO.Assign(attrs...))
}

func (j jobRunDo) Joins(fields ...field.RelationField) IJobRunDo {
	for _, _f := range fields {
		j = *j.withDO(j.DO.Joins(_f))
	}
	return &j
}

func (j jobRunDo) Preload(fields ...field.RelationField) IJobRunDo {
	for _, _f := range fields {
		j = *j.withDO(j.DO.Preload(_f))
	}
	return &j
}

func (j jobRunDo) FirstOrInit() (*models.JobRun, error) {
	if result, err := j.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*models.JobRun), nil
	}
}

func (j jobRunDo) FirstOrCreate() (*models.JobRun, error) {
	if result, err := j.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*models.JobRun), nil
	}
}

func (j jobRunDo) FindByPage(offset int, limit int) (result []*models.JobRun, count int64, err error) {
	result, err = j.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = j.Offset(-1).Limit(-1).Count()
	return
}

func (j jobRunDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = j.Count()
	if err != nil {
		return
	}

	err = j.Offset(offset).Limit(limit).Scan(result)
	return
}

func (j jobRunDo) Scan(result interface{}) (err error) {
	return j.DO.Scan(result)
}

func (j jobRunDo) Delete(models ...*models.JobRun) (result gen.ResultInfo, err error) {
	return j.DO.Delete(models)
}

func (j *jobRunDo) withDO(do gen.Dao) *jobRunDo {
	j.DO = *do.(*gen.DO)
	return j
}
