// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package db

import (
	"context"
	"database/sql"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"chronix/internal/db/models"
)

func newJobRunWebtaskIo(db *gorm.DB, opts ...gen.DOOption) jobRunWebtaskIo {
	_jobRunWebtaskIo := jobRunWebtaskIo{}

	_jobRunWebtaskIo.jobRunWebtaskIoDo.UseDB(db, opts...)
	_jobRunWebtaskIo.jobRunWebtaskIoDo.UseModel(&models.JobRunWebtaskIo{})

	tableName := _jobRunWebtaskIo.jobRunWebtaskIoDo.TableName()
	_jobRunWebtaskIo.ALL = field.NewAsterisk(tableName)
	_jobRunWebtaskIo.ID = field.NewInt64(tableName, "id")
	_jobRunWebtaskIo.StepID = field.NewInt64(tableName, "step_id")
	_jobRunWebtaskIo.RequestURL = field.NewString(tableName, "request_url")
	_jobRunWebtaskIo.RequestMethod = field.NewString(tableName, "request_method")
	_jobRunWebtaskIo.RequestHeaders = field.NewField(tableName, "request_headers")
	_jobRunWebtaskIo.RequestBody = field.NewString(tableName, "request_body")
	_jobRunWebtaskIo.ResponseStatus = field.NewInt64(tableName, "response_status")
	_jobRunWebtaskIo.ResponseHeaders = field.NewField(tableName, "response_headers")
	_jobRunWebtaskIo.ResponseBody = field.NewString(tableName, "response_body")
	_jobRunWebtaskIo.LatencyMs = field.NewInt64(tableName, "latency_ms")

	_jobRunWebtaskIo.fillFieldMap()

	return _jobRunWebtaskIo
}

type jobRunWebtaskIo struct {
	jobRunWebtaskIoDo

	ALL             field.Asterisk
	ID              field.Int64
	StepID          field.Int64
	RequestURL      field.String
	RequestMethod   field.String
	RequestHeaders  field.Field
	RequestBody     field.String
	ResponseStatus  field.Int64
	ResponseHeaders field.Field
	ResponseBody    field.String
	LatencyMs       field.Int64

	fieldMap map[string]field.Expr
}

func (j jobRunWebtaskIo) Table(newTableName string) *jobRunWebtaskIo {
	j.jobRunWebtaskIoDo.UseTable(newTableName)
	return j.updateTableName(newTableName)
}

func (j jobRunWebtaskIo) As(alias string) *jobRunWebtaskIo {
	j.jobRunWebtaskIoDo.DO = *(j.jobRunWebtaskIoDo.As(alias).(*gen.DO))
	return j.updateTableName(alias)
}

func (j *jobRunWebtaskIo) updateTableName(table string) *jobRunWebtaskIo {
	j.ALL = field.NewAsterisk(table)
	j.ID = field.NewInt64(table, "id")
	j.StepID = field.NewInt64(table, "step_id")
	j.RequestURL = field.NewString(table, "request_url")
	j.RequestMethod = field.NewString(table, "request_method")
	j.RequestHeaders = field.NewField(table, "request_headers")
	j.RequestBody = field.NewString(table, "request_body")
	j.ResponseStatus = field.NewInt64(table, "response_status")
	j.ResponseHeaders = field.NewField(table, "response_headers")
	j.ResponseBody = field.NewString(table, "response_body")
	j.LatencyMs = field.NewInt64(table, "latency_ms")

	j.fillFieldMap()

	return j
}

func (j *jobRunWebtaskIo) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := j.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (j *jobRunWebtaskIo) fillFieldMap() {
	j.fieldMap = make(map[string]field.Expr, 10)
	j.fieldMap["id"] = j.ID
	j.fieldMap["step_id"] = j.StepID
	j.fieldMap["request_url"] = j.RequestURL
	j.fieldMap["request_method"] = j.RequestMethod
	j.fieldMap["request_headers"] = j.RequestHeaders
	j.fieldMap["request_body"] = j.RequestBody
	j.fieldMap["response_status"] = j.ResponseStatus
	j.fieldMap["response_headers"] = j.ResponseHeaders
	j.fieldMap["response_body"] = j.ResponseBody
	j.fieldMap["latency_ms"] = j.LatencyMs
}

func (j jobRunWebtaskIo) clone(db *gorm.DB) jobRunWebtaskIo {
	j.jobRunWebtaskIoDo.ReplaceConnPool(db.Statement.ConnPool)
	return j
}

func (j jobRunWebtaskIo) replaceDB(db *gorm.DB) jobRunWebtaskIo {
	j.jobRunWebtaskIoDo.ReplaceDB(db)
	return j
}

type jobRunWebtaskIoDo struct{ gen.DO }

type IJobRunWebtaskIoDo interface {
	gen.SubQuery
	Debug() IJobRunWebtaskIoDo
	WithContext(ctx context.Context) IJobRunWebtaskIoDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() IJobRunWebtaskIoDo
	WriteDB() IJobRunWebtaskIoDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) IJobRunWebtaskIoDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) IJobRunWebtaskIoDo
	Not(conds ...gen.Condition) IJobRunWebtaskIoDo
	Or(conds ...gen.Condition) IJobRunWebtaskIoDo
	Select(conds ...field.Expr) IJobRunWebtaskIoDo
	Where(conds ...gen.Condition) IJobRunWebtaskIoDo
	Order(conds ...field.Expr) IJobRunWebtaskIoDo
	Distinct(cols ...field.Expr) IJobRunWebtaskIoDo
	Omit(cols ...field.Expr) IJobRunWebtaskIoDo
	Join(table schema.Tabler, on ...field.Expr) IJobRunWebtaskIoDo
	LeftJoin(table schema.Tabler, on ...field.Expr) IJobRunWebtaskIoDo
	RightJoin(table schema.Tabler, on ...field.Expr) IJobRunWebtaskIoDo
	Group(cols ...field.Expr) IJobRunWebtaskIoDo
	Having(conds ...gen.Condition) IJobRunWebtaskIoDo
	Limit(limit int) IJobRunWebtaskIoDo
	Offset(offset int) IJobRunWebtaskIoDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) IJobRunWebtaskIoDo
	Unscoped() IJobRunWebtaskIoDo
	Create(values ...*models.JobRunWebtaskIo) error
	CreateInBatches(values []*models.JobRunWebtaskIo, batchSize int) error
	Save(values ...*models.JobRunWebtaskIo) error
	First() (*models.JobRunWebtaskIo, error)
	Take() (*models.JobRunWebtaskIo, error)
	Last() (*models.JobRunWebtaskIo, error)
	Find() ([]*models.JobRunWebtaskIo, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*models.JobRunWebtaskIo, err error)
	FindInBatches(result *[]*models.JobRunWebtaskIo, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*models.JobRunWebtaskIo) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) IJobRunWebtaskIoDo
	Assign(attrs ...field.AssignExpr) IJobRunWebtaskIoDo
	Joins(fields ...field.RelationField) IJobRunWebtaskIoDo
	Preload(fields ...field.RelationField) IJobRunWebtaskIoDo
	FirstOrInit() (*models.JobRunWebtaskIo, error)
	FirstOrCreate() (*models.JobRunWebtaskIo, error)
	FindByPage(offset int, limit int) (result []*models.JobRunWebtaskIo, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Rows() (*sql.Rows, error)
	Row() *sql.Row
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) IJobRunWebtaskIoDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (j jobRunWebtaskIoDo) Debug() IJobRunWebtaskIoDo {
	return j.withDO(j.DO.Debug())
}

func (j jobRunWebtaskIoDo) WithContext(ctx context.Context) IJobRunWebtaskIoDo {
	return j.withDO(j.DO.WithContext(ctx))
}

func (j jobRunWebtaskIoDo) ReadDB() IJobRunWebtaskIoDo {
	return j.Clauses(dbresolver.Read)
}

func (j jobRunWebtaskIoDo) WriteDB() IJobRunWebtaskIoDo {
	return j.Clauses(dbresolver.Write)
}

func (j jobRunWebtaskIoDo) Session(config *gorm.Session) IJobRunWebtaskIoDo {
	return j.withDO(j.DO.Session(config))
}

func (j jobRunWebtaskIoDo) Clauses(conds ...clause.Expression) IJobRunWebtaskIoDo {
	return j.withDO(j.DO.Clauses(conds...))
}

func (j jobRunWebtaskIoDo) Returning(value interface{}, columns ...string) IJobRunWebtaskIoDo {
	return j.withDO(j.DO.Returning(value, columns...))
}

func (j jobRunWebtaskIoDo) Not(conds ...gen.Condition) IJobRunWebtaskIoDo {
	return j.withDO(j.DO.Not(conds...))
}

func (j jobRunWebtaskIoDo) Or(conds ...gen.Condition) IJobRunWebtaskIoDo {
	return j.withDO(j.DO.Or(conds...))
}

func (j jobRunWebtaskIoDo) Select(conds ...field.Expr) IJobRunWebtaskIoDo {
	return j.withDO(j.DO.Select(conds...))
}

func (j jobRunWebtaskIoDo) Where(conds ...gen.Condition) IJobRunWebtaskIoDo {
	return j.withDO(j.DO.Where(conds...))
}

func (j jobRunWebtaskIoDo) Order(conds ...field.Expr) IJobRunWebtaskIoDo {
	return j.withDO(j.DO.Order(conds...))
}

func (j jobRunWebtaskIoDo) Distinct(cols ...field.Expr) IJobRunWebtaskIoDo {
	return j.withDO(j.DO.Distinct(cols...))
}

func (j jobRunWebtaskIoDo) Omit(cols ...field.Expr) IJobRunWebtaskIoDo {
	return j.withDO(j.DO.Omit(cols...))
}

func (j jobRunWebtaskIoDo) Join(table schema.Tabler, on ...field.Expr) IJobRunWebtaskIoDo {
	return j.withDO(j.DO.Join(table, on...))
}

func (j jobRunWebtaskIoDo) LeftJoin(table schema.Tabler, on ...field.Expr) IJobRunWebtaskIoDo {
	return j.withDO(j.DO.LeftJoin(table, on...))
}

func (j jobRunWebtaskIoDo) RightJoin(table schema.Tabler, on ...field.Expr) IJobRunWebtaskIoDo {
	return j.withDO(j.DO.RightJoin(table, on...))
}

func (j jobRunWebtaskIoDo) Group(cols ...field.Expr) IJobRunWebtaskIoDo {
	return j.withDO(j.DO.Group(cols...))
}

func (j jobRunWebtaskIoDo) Having(conds ...gen.Condition) IJobRunWebtaskIoDo {
	return j.withDO(j.DO.Having(conds...))
}

func (j jobRunWebtaskIoDo) Limit(limit int) IJobRunWebtaskIoDo {
	return j.withDO(j.DO.Limit(limit))
}

func (j jobRunWebtaskIoDo) Offset(offset int) IJobRunWebtaskIoDo {
	return j.withDO(j.DO.Offset(offset))
}

func (j jobRunWebtaskIoDo) Scopes(funcs ...func(gen.Dao) gen.Dao) IJobRunWebtaskIoDo {
	return j.withDO(j.DO.Scopes(funcs...))
}

func (j jobRunWebtaskIoDo) Unscoped() IJobRunWebtaskIoDo {
	return j.withDO(j.DO.Unscoped())
}

func (j jobRunWebtaskIoDo) Create(values ...*models.JobRunWebtaskIo) error {
	if len(values) == 0 {
		return nil
	}
	return j.DO.Create(values)
}

func (j jobRunWebtaskIoDo) CreateInBatches(values []*models.JobRunWebtaskIo, batchSize int) error {
	return j.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (j jobRunWebtaskIoDo) Save(values ...*models.JobRunWebtaskIo) error {
	if len(values) == 0 {
		return nil
	}
	return j.DO.Save(values)
}

func (j jobRunWebtaskIoDo) First() (*models.JobRunWebtaskIo, error) {
	if result, err := j.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*models.JobRunWebtaskIo), nil
	}
}

func (j jobRunWebtaskIoDo) Take() (*models.JobRunWebtaskIo, error) {
	if result, err := j.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*models.JobRunWebtaskIo), nil
	}
}

func (j jobRunWebtaskIoDo) Last() (*models.JobRunWebtaskIo, error) {
	if result, err := j.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*models.JobRunWebtaskIo), nil
	}
}

func (j jobRunWebtaskIoDo) Find() ([]*models.JobRunWebtaskIo, error) {
	result, err := j.DO.Find()
	return result.([]*models.JobRunWebtaskIo), err
}

func (j jobRunWebtaskIoDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*models.JobRunWebtaskIo, err error) {
	buf := make([]*models.JobRunWebtaskIo, 0, batchSize)
	err = j.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (j jobRunWebtaskIoDo) FindInBatches(result *[]*models.JobRunWebtaskIo, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return j.DO.FindInBatches(result, batchSize, fc)
}

func (j jobRunWebtaskIoDo) Attrs(attrs ...field.AssignExpr) IJobRunWebtaskIoDo {
	return j.withDO(j.DO.Attrs(attrs...))
}

func (j jobRunWebtaskIoDo) Assign(attrs ...field.AssignExpr) IJobRunWebtaskIoDo {
	return j.withDO(j.DO.Assign(attrs...))
}

func (j jobRunWebtaskIoDo) Joins(fields ...field.RelationField) IJobRunWebtaskIoDo {
	for _, _f := range fields {
		j = *j.withDO(j.DO.Joins(_f))
	}
	return &j
}

func (j jobRunWebtaskIoDo) Preload(fields ...field.RelationField) IJobRunWebtaskIoDo {
	for _, _f := range fields {
		j = *j.withDO(j.DO.Preload(_f))
	}
	return &j
}

func (j jobRunWebtaskIoDo) FirstOrInit() (*models.JobRunWebtaskIo, error) {
	if result, err := j.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*models.JobRunWebtaskIo), nil
	}
}

func (j jobRunWebtaskIoDo) FirstOrCreate() (*models.JobRunWebtaskIo, error) {
	if result, err := j.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*models.JobRunWebtaskIo), nil
	}
}

func (j jobRunWebtaskIoDo) FindByPage(offset int, limit int) (result []*models.JobRunWebtaskIo, count int64, err error) {
	result, err = j.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = j.Offset(-1).Limit(-1).Count()
	return
}

func (j jobRunWebtaskIoDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = j.Count()
	if err != nil {
		return
	}

	err = j.Offset(offset).Limit(limit).Scan(result)
	return
}

func (j jobRunWebtaskIoDo) Scan(result interface{}) (err error) {
	return j.DO.Scan(result)
}

func (j jobRunWebtaskIoDo) Delete(models ...*models.JobRunWebtaskIo) (result gen.ResultInfo, err error) {
	return j.DO.Delete(models)
}

func (j *jobRunWebtaskIoDo) withDO(do gen.Dao) *jobRunWebtaskIoDo {
	j.DO = *do.(*gen.DO)
	return j
}
