// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package db

import (
	"context"
	"database/sql"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"chronix/internal/db/models"
)

func newJobRunEvent(db *gorm.DB, opts ...gen.DOOption) jobRunEvent {
	_jobRunEvent := jobRunEvent{}

	_jobRunEvent.jobRunEventDo.UseDB(db, opts...)
	_jobRunEvent.jobRunEventDo.UseModel(&models.JobRunEvent{})

	tableName := _jobRunEvent.jobRunEventDo.TableName()
	_jobRunEvent.ALL = field.NewAsterisk(tableName)
	_jobRunEvent.ID = field.NewInt64(tableName, "id")
	_jobRunEvent.RunID = field.NewInt64(tableName, "run_id")
	_jobRunEvent.StepID = field.NewInt64(tableName, "step_id")
	_jobRunEvent.CreatedAt = field.NewTime(tableName, "created_at")
	_jobRunEvent.Kind = field.NewString(tableName, "kind")
	_jobRunEvent.Message = field.NewString(tableName, "message")
	_jobRunEvent.Data = field.NewField(tableName, "data")

	_jobRunEvent.fillFieldMap()

	return _jobRunEvent
}

type jobRunEvent struct {
	jobRunEventDo

	ALL       field.Asterisk
	ID        field.Int64
	RunID     field.Int64
	StepID    field.Int64
	CreatedAt field.Time
	Kind      field.String
	Message   field.String
	Data      field.Field

	fieldMap map[string]field.Expr
}

func (j jobRunEvent) Table(newTableName string) *jobRunEvent {
	j.jobRunEventDo.UseTable(newTableName)
	return j.updateTableName(newTableName)
}

func (j jobRunEvent) As(alias string) *jobRunEvent {
	j.jobRunEventDo.DO = *(j.jobRunEventDo.As(alias).(*gen.DO))
	return j.updateTableName(alias)
}

func (j *jobRunEvent) updateTableName(table string) *jobRunEvent {
	j.ALL = field.NewAsterisk(table)
	j.ID = field.NewInt64(table, "id")
	j.RunID = field.NewInt64(table, "run_id")
	j.StepID = field.NewInt64(table, "step_id")
	j.CreatedAt = field.NewTime(table, "created_at")
	j.Kind = field.NewString(table, "kind")
	j.Message = field.NewString(table, "message")
	j.Data = field.NewField(table, "data")

	j.fillFieldMap()

	return j
}

func (j *jobRunEvent) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := j.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (j *jobRunEvent) fillFieldMap() {
	j.fieldMap = make(map[string]field.Expr, 7)
	j.fieldMap["id"] = j.ID
	j.fieldMap["run_id"] = j.RunID
	j.fieldMap["step_id"] = j.StepID
	j.fieldMap["created_at"] = j.CreatedAt
	j.fieldMap["kind"] = j.Kind
	j.fieldMap["message"] = j.Message
	j.fieldMap["data"] = j.Data
}

func (j jobRunEvent) clone(db *gorm.DB) jobRunEvent {
	j.jobRunEventDo.ReplaceConnPool(db.Statement.ConnPool)
	return j
}

func (j jobRunEvent) replaceDB(db *gorm.DB) jobRunEvent {
	j.jobRunEventDo.ReplaceDB(db)
	return j
}

type jobRunEventDo struct{ gen.DO }

type IJobRunEventDo interface {
	gen.SubQuery
	Debug() IJobRunEventDo
	WithContext(ctx context.Context) IJobRunEventDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() IJobRunEventDo
	WriteDB() IJobRunEventDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) IJobRunEventDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) IJobRunEventDo
	Not(conds ...gen.Condition) IJobRunEventDo
	Or(conds ...gen.Condition) IJobRunEventDo
	Select(conds ...field.Expr) IJobRunEventDo
	Where(conds ...gen.Condition) IJobRunEventDo
	Order(conds ...field.Expr) IJobRunEventDo
	Distinct(cols ...field.Expr) IJobRunEventDo
	Omit(cols ...field.Expr) IJobRunEventDo
	Join(table schema.Tabler, on ...field.Expr) IJobRunEventDo
	LeftJoin(table schema.Tabler, on ...field.Expr) IJobRunEventDo
	RightJoin(table schema.Tabler, on ...field.Expr) IJobRunEventDo
	Group(cols ...field.Expr) IJobRunEventDo
	Having(conds ...gen.Condition) IJobRunEventDo
	Limit(limit int) IJobRunEventDo
	Offset(offset int) IJobRunEventDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) IJobRunEventDo
	Unscoped() IJobRunEventDo
	Create(values ...*models.JobRunEvent) error
	CreateInBatches(values []*models.JobRunEvent, batchSize int) error
	Save(values ...*models.JobRunEvent) error
	First() (*models.JobRunEvent, error)
	Take() (*models.JobRunEvent, error)
	Last() (*models.JobRunEvent, error)
	Find() ([]*models.JobRunEvent, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*models.JobRunEvent, err error)
	FindInBatches(result *[]*models.JobRunEvent, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*models.JobRunEvent) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) IJobRunEventDo
	Assign(attrs ...field.AssignExpr) IJobRunEventDo
	Joins(fields ...field.RelationField) IJobRunEventDo
	Preload(fields ...field.RelationField) IJobRunEventDo
	FirstOrInit() (*models.JobRunEvent, error)
	FirstOrCreate() (*models.JobRunEvent, error)
	FindByPage(offset int, limit int) (result []*models.JobRunEvent, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Rows() (*sql.Rows, error)
	Row() *sql.Row
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) IJobRunEventDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (j jobRunEventDo) Debug() IJobRunEventDo {
	return j.withDO(j.DO.Debug())
}

func (j jobRunEventDo) WithContext(ctx context.Context) IJobRunEventDo {
	return j.withDO(j.DO.WithContext(ctx))
}

func (j jobRunEventDo) ReadDB() IJobRunEventDo {
	return j.Clauses(dbresolver.Read)
}

func (j jobRunEventDo) WriteDB() IJobRunEventDo {
	return j.Clauses(dbresolver.Write)
}

func (j jobRunEventDo) Session(config *gorm.Session) IJobRunEventDo {
	return j.withDO(j.DO.Session(config))
}

func (j jobRunEventDo) Clauses(conds ...clause.Expression) IJobRunEventDo {
	return j.withDO(j.DO.Clauses(conds...))
}

func (j jobRunEventDo) Returning(value interface{}, columns ...string) IJobRunEventDo {
	return j.withDO(j.DO.Returning(value, columns...))
}

func (j jobRunEventDo) Not(conds ...gen.Condition) IJobRunEventDo {
	return j.withDO(j.DO.Not(conds...))
}

func (j jobRunEventDo) Or(conds ...gen.Condition) IJobRunEventDo {
	return j.withDO(j.DO.Or(conds...))
}

func (j jobRunEventDo) Select(conds ...field.Expr) IJobRunEventDo {
	return j.withDO(j.DO.Select(conds...))
}

func (j jobRunEventDo) Where(conds ...gen.Condition) IJobRunEventDo {
	return j.withDO(j.DO.Where(conds...))
}

func (j jobRunEventDo) Order(conds ...field.Expr) IJobRunEventDo {
	return j.withDO(j.DO.Order(conds...))
}

func (j jobRunEventDo) Distinct(cols ...field.Expr) IJobRunEventDo {
	return j.withDO(j.DO.Distinct(cols...))
}

func (j jobRunEventDo) Omit(cols ...field.Expr) IJobRunEventDo {
	return j.withDO(j.DO.Omit(cols...))
}

func (j jobRunEventDo) Join(table schema.Tabler, on ...field.Expr) IJobRunEventDo {
	return j.withDO(j.DO.Join(table, on...))
}

func (j jobRunEventDo) LeftJoin(table schema.Tabler, on ...field.Expr) IJobRunEventDo {
	return j.withDO(j.DO.LeftJoin(table, on...))
}

func (j jobRunEventDo) RightJoin(table schema.Tabler, on ...field.Expr) IJobRunEventDo {
	return j.withDO(j.DO.RightJoin(table, on...))
}

func (j jobRunEventDo) Group(cols ...field.Expr) IJobRunEventDo {
	return j.withDO(j.DO.Group(cols...))
}

func (j jobRunEventDo) Having(conds ...gen.Condition) IJobRunEventDo {
	return j.withDO(j.DO.Having(conds...))
}

func (j jobRunEventDo) Limit(limit int) IJobRunEventDo {
	return j.withDO(j.DO.Limit(limit))
}

func (j jobRunEventDo) Offset(offset int) IJobRunEventDo {
	return j.withDO(j.DO.Offset(offset))
}

func (j jobRunEventDo) Scopes(funcs ...func(gen.Dao) gen.Dao) IJobRunEventDo {
	return j.withDO(j.DO.Scopes(funcs...))
}

func (j jobRunEventDo) Unscoped() IJobRunEventDo {
	return j.withDO(j.DO.Unscoped())
}

func (j jobRunEventDo) Create(values ...*models.JobRunEvent) error {
	if len(values) == 0 {
		return nil
	}
	return j.DO.Create(values)
}

func (j jobRunEventDo) CreateInBatches(values []*models.JobRunEvent, batchSize int) error {
	return j.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (j jobRunEventDo) Save(values ...*models.JobRunEvent) error {
	if len(values) == 0 {
		return nil
	}
	return j.DO.Save(values)
}

func (j jobRunEventDo) First() (*models.JobRunEvent, error) {
	if result, err := j.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*models.JobRunEvent), nil
	}
}

func (j jobRunEventDo) Take() (*models.JobRunEvent, error) {
	if result, err := j.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*models.JobRunEvent), nil
	}
}

func (j jobRunEventDo) Last() (*models.JobRunEvent, error) {
	if result, err := j.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*models.JobRunEvent), nil
	}
}

func (j jobRunEventDo) Find() ([]*models.JobRunEvent, error) {
	result, err := j.DO.Find()
	return result.([]*models.JobRunEvent), err
}

func (j jobRunEventDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*models.JobRunEvent, err error) {
	buf := make([]*models.JobRunEvent, 0, batchSize)
	err = j.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (j jobRunEventDo) FindInBatches(result *[]*models.JobRunEvent, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return j.DO.FindInBatches(result, batchSize, fc)
}

func (j jobRunEventDo) Attrs(attrs ...field.AssignExpr) IJobRunEventDo {
	return j.withDO(j.DO.Attrs(attrs...))
}

func (j jobRunEventDo) Assign(attrs ...field.AssignExpr) IJobRunEventDo {
	return j.withDO(j.DO.Assign(attrs...))
}

func (j jobRunEventDo) Joins(fields ...field.RelationField) IJobRunEventDo {
	for _, _f := range fields {
		j = *j.withDO(j.DO.Joins(_f))
	}
	return &j
}

func (j jobRunEventDo) Preload(fields ...field.RelationField) IJobRunEventDo {
	for _, _f := range fields {
		j = *j.withDO(j.DO.Preload(_f))
	}
	return &j
}

func (j jobRunEventDo) FirstOrInit() (*models.JobRunEvent, error) {
	if result, err := j.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*models.JobRunEvent), nil
	}
}

func (j jobRunEventDo) FirstOrCreate() (*models.JobRunEvent, error) {
	if result, err := j.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*models.JobRunEvent), nil
	}
}

func (j jobRunEventDo) FindByPage(offset int, limit int) (result []*models.JobRunEvent, count int64, err error) {
	result, err = j.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = j.Offset(-1).Limit(-1).Count()
	return
}

func (j jobRunEventDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = j.Count()
	if err != nil {
		return
	}

	err = j.Offset(offset).Limit(limit).Scan(result)
	return
}

func (j jobRunEventDo) Scan(result interface{}) (err error) {
	return j.DO.Scan(result)
}

func (j jobRunEventDo) Delete(models ...*models.JobRunEvent) (result gen.ResultInfo, err error) {
	return j.DO.Delete(models)
}

func (j *jobRunEventDo) withDO(do gen.Dao) *jobRunEventDo {
	j.DO = *do.(*gen.DO)
	return j
}
