// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package db

import (
	"context"
	"database/sql"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"chronix/internal/db/models"
)

func newJobRunStep(db *gorm.DB, opts ...gen.DOOption) jobRunStep {
	_jobRunStep := jobRunStep{}

	_jobRunStep.jobRunStepDo.UseDB(db, opts...)
	_jobRunStep.jobRunStepDo.UseModel(&models.JobRunStep{})

	tableName := _jobRunStep.jobRunStepDo.TableName()
	_jobRunStep.ALL = field.NewAsterisk(tableName)
	_jobRunStep.ID = field.NewInt64(tableName, "id")
	_jobRunStep.RunID = field.NewInt64(tableName, "run_id")
	_jobRunStep.StepOrder = field.NewInt64(tableName, "step_order")
	_jobRunStep.StepName = field.NewString(tableName, "step_name")
	_jobRunStep.StartedAt = field.NewTime(tableName, "started_at")
	_jobRunStep.FinishedAt = field.NewTime(tableName, "finished_at")
	_jobRunStep.Status = field.NewString(tableName, "status")
	_jobRunStep.SqlText = field.NewString(tableName, "sql_text")
	_jobRunStep.TimeoutSeconds = field.NewInt64(tableName, "timeout_seconds")
	_jobRunStep.CommandText = field.NewString(tableName, "command_text")
	_jobRunStep.ScriptText = field.NewString(tableName, "script_text")
	_jobRunStep.ShellPath = field.NewString(tableName, "shell_path")
	_jobRunStep.WorkingDir = field.NewString(tableName, "working_dir")
	_jobRunStep.ExitCode = field.NewInt64(tableName, "exit_code")
	_jobRunStep.RowsCount = field.NewInt64(tableName, "rows_count")
	_jobRunStep.RowsAffected = field.NewInt64(tableName, "rows_affected")
	_jobRunStep.Expectation = field.NewField(tableName, "expectation")
	_jobRunStep.ExpectOk = field.NewBool(tableName, "expect_ok")
	_jobRunStep.ExpectMessage = field.NewString(tableName, "expect_message")
	_jobRunStep.ErrorCode = field.NewString(tableName, "error_code")
	_jobRunStep.ErrorMessage = field.NewString(tableName, "error_message")
	_jobRunStep.Details = field.NewField(tableName, "details")

	_jobRunStep.fillFieldMap()

	return _jobRunStep
}

type jobRunStep struct {
	jobRunStepDo

	ALL            field.Asterisk
	ID             field.Int64
	RunID          field.Int64
	StepOrder      field.Int64
	StepName       field.String
	StartedAt      field.Time
	FinishedAt     field.Time
	Status         field.String
	SqlText        field.String
	TimeoutSeconds field.Int64
	CommandText    field.String
	ScriptText     field.String
	ShellPath      field.String
	WorkingDir     field.String
	ExitCode       field.Int64
	RowsCount      field.Int64
	RowsAffected   field.Int64
	Expectation    field.Field
	ExpectOk       field.Bool
	ExpectMessage  field.String
	ErrorCode      field.String
	ErrorMessage   field.String
	Details        field.Field

	fieldMap map[string]field.Expr
}

func (j jobRunStep) Table(newTableName string) *jobRunStep {
	j.jobRunStepDo.UseTable(newTableName)
	return j.updateTableName(newTableName)
}

func (j jobRunStep) As(alias string) *jobRunStep {
	j.jobRunStepDo.DO = *(j.jobRunStepDo.As(alias).(*gen.DO))
	return j.updateTableName(alias)
}

func (j *jobRunStep) updateTableName(table string) *jobRunStep {
	j.ALL = field.NewAsterisk(table)
	j.ID = field.NewInt64(table, "id")
	j.RunID = field.NewInt64(table, "run_id")
	j.StepOrder = field.NewInt64(table, "step_order")
	j.StepName = field.NewString(table, "step_name")
	j.StartedAt = field.NewTime(table, "started_at")
	j.FinishedAt = field.NewTime(table, "finished_at")
	j.Status = field.NewString(table, "status")
	j.SqlText = field.NewString(table, "sql_text")
	j.TimeoutSeconds = field.NewInt64(table, "timeout_seconds")
	j.CommandText = field.NewString(table, "command_text")
	j.ScriptText = field.NewString(table, "script_text")
	j.ShellPath = field.NewString(table, "shell_path")
	j.WorkingDir = field.NewString(table, "working_dir")
	j.ExitCode = field.NewInt64(table, "exit_code")
	j.RowsCount = field.NewInt64(table, "rows_count")
	j.RowsAffected = field.NewInt64(table, "rows_affected")
	j.Expectation = field.NewField(table, "expectation")
	j.ExpectOk = field.NewBool(table, "expect_ok")
	j.ExpectMessage = field.NewString(table, "expect_message")
	j.ErrorCode = field.NewString(table, "error_code")
	j.ErrorMessage = field.NewString(table, "error_message")
	j.Details = field.NewField(table, "details")

	j.fillFieldMap()

	return j
}

func (j *jobRunStep) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := j.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (j *jobRunStep) fillFieldMap() {
	j.fieldMap = make(map[string]field.Expr, 22)
	j.fieldMap["id"] = j.ID
	j.fieldMap["run_id"] = j.RunID
	j.fieldMap["step_order"] = j.StepOrder
	j.fieldMap["step_name"] = j.StepName
	j.fieldMap["started_at"] = j.StartedAt
	j.fieldMap["finished_at"] = j.FinishedAt
	j.fieldMap["status"] = j.Status
	j.fieldMap["sql_text"] = j.SqlText
	j.fieldMap["timeout_seconds"] = j.TimeoutSeconds
	j.fieldMap["command_text"] = j.CommandText
	j.fieldMap["script_text"] = j.ScriptText
	j.fieldMap["shell_path"] = j.ShellPath
	j.fieldMap["working_dir"] = j.WorkingDir
	j.fieldMap["exit_code"] = j.ExitCode
	j.fieldMap["rows_count"] = j.RowsCount
	j.fieldMap["rows_affected"] = j.RowsAffected
	j.fieldMap["expectation"] = j.Expectation
	j.fieldMap["expect_ok"] = j.ExpectOk
	j.fieldMap["expect_message"] = j.ExpectMessage
	j.fieldMap["error_code"] = j.ErrorCode
	j.fieldMap["error_message"] = j.ErrorMessage
	j.fieldMap["details"] = j.Details
}

func (j jobRunStep) clone(db *gorm.DB) jobRunStep {
	j.jobRunStepDo.ReplaceConnPool(db.Statement.ConnPool)
	return j
}

func (j jobRunStep) replaceDB(db *gorm.DB) jobRunStep {
	j.jobRunStepDo.ReplaceDB(db)
	return j
}

type jobRunStepDo struct{ gen.DO }

type IJobRunStepDo interface {
	gen.SubQuery
	Debug() IJobRunStepDo
	WithContext(ctx context.Context) IJobRunStepDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() IJobRunStepDo
	WriteDB() IJobRunStepDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) IJobRunStepDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) IJobRunStepDo
	Not(conds ...gen.Condition) IJobRunStepDo
	Or(conds ...gen.Condition) IJobRunStepDo
	Select(conds ...field.Expr) IJobRunStepDo
	Where(conds ...gen.Condition) IJobRunStepDo
	Order(conds ...field.Expr) IJobRunStepDo
	Distinct(cols ...field.Expr) IJobRunStepDo
	Omit(cols ...field.Expr) IJobRunStepDo
	Join(table schema.Tabler, on ...field.Expr) IJobRunStepDo
	LeftJoin(table schema.Tabler, on ...field.Expr) IJobRunStepDo
	RightJoin(table schema.Tabler, on ...field.Expr) IJobRunStepDo
	Group(cols ...field.Expr) IJobRunStepDo
	Having(conds ...gen.Condition) IJobRunStepDo
	Limit(limit int) IJobRunStepDo
	Offset(offset int) IJobRunStepDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) IJobRunStepDo
	Unscoped() IJobRunStepDo
	Create(values ...*models.JobRunStep) error
	CreateInBatches(values []*models.JobRunStep, batchSize int) error
	Save(values ...*models.JobRunStep) error
	First() (*models.JobRunStep, error)
	Take() (*models.JobRunStep, error)
	Last() (*models.JobRunStep, error)
	Find() ([]*models.JobRunStep, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*models.JobRunStep, err error)
	FindInBatches(result *[]*models.JobRunStep, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*models.JobRunStep) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) IJobRunStepDo
	Assign(attrs ...field.AssignExpr) IJobRunStepDo
	Joins(fields ...field.RelationField) IJobRunStepDo
	Preload(fields ...field.RelationField) IJobRunStepDo
	FirstOrInit() (*models.JobRunStep, error)
	FirstOrCreate() (*models.JobRunStep, error)
	FindByPage(offset int, limit int) (result []*models.JobRunStep, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Rows() (*sql.Rows, error)
	Row() *sql.Row
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) IJobRunStepDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (j jobRunStepDo) Debug() IJobRunStepDo {
	return j.withDO(j.DO.Debug())
}

func (j jobRunStepDo) WithContext(ctx context.Context) IJobRunStepDo {
	return j.withDO(j.DO.WithContext(ctx))
}

func (j jobRunStepDo) ReadDB() IJobRunStepDo {
	return j.Clauses(dbresolver.Read)
}

func (j jobRunStepDo) WriteDB() IJobRunStepDo {
	return j.Clauses(dbresolver.Write)
}

func (j jobRunStepDo) Session(config *gorm.Session) IJobRunStepDo {
	return j.withDO(j.DO.Session(config))
}

func (j jobRunStepDo) Clauses(conds ...clause.Expression) IJobRunStepDo {
	return j.withDO(j.DO.Clauses(conds...))
}

func (j jobRunStepDo) Returning(value interface{}, columns ...string) IJobRunStepDo {
	return j.withDO(j.DO.Returning(value, columns...))
}

func (j jobRunStepDo) Not(conds ...gen.Condition) IJobRunStepDo {
	return j.withDO(j.DO.Not(conds...))
}

func (j jobRunStepDo) Or(conds ...gen.Condition) IJobRunStepDo {
	return j.withDO(j.DO.Or(conds...))
}

func (j jobRunStepDo) Select(conds ...field.Expr) IJobRunStepDo {
	return j.withDO(j.DO.Select(conds...))
}

func (j jobRunStepDo) Where(conds ...gen.Condition) IJobRunStepDo {
	return j.withDO(j.DO.Where(conds...))
}

func (j jobRunStepDo) Order(conds ...field.Expr) IJobRunStepDo {
	return j.withDO(j.DO.Order(conds...))
}

func (j jobRunStepDo) Distinct(cols ...field.Expr) IJobRunStepDo {
	return j.withDO(j.DO.Distinct(cols...))
}

func (j jobRunStepDo) Omit(cols ...field.Expr) IJobRunStepDo {
	return j.withDO(j.DO.Omit(cols...))
}

func (j jobRunStepDo) Join(table schema.Tabler, on ...field.Expr) IJobRunStepDo {
	return j.withDO(j.DO.Join(table, on...))
}

func (j jobRunStepDo) LeftJoin(table schema.Tabler, on ...field.Expr) IJobRunStepDo {
	return j.withDO(j.DO.LeftJoin(table, on...))
}

func (j jobRunStepDo) RightJoin(table schema.Tabler, on ...field.Expr) IJobRunStepDo {
	return j.withDO(j.DO.RightJoin(table, on...))
}

func (j jobRunStepDo) Group(cols ...field.Expr) IJobRunStepDo {
	return j.withDO(j.DO.Group(cols...))
}

func (j jobRunStepDo) Having(conds ...gen.Condition) IJobRunStepDo {
	return j.withDO(j.DO.Having(conds...))
}

func (j jobRunStepDo) Limit(limit int) IJobRunStepDo {
	return j.withDO(j.DO.Limit(limit))
}

func (j jobRunStepDo) Offset(offset int) IJobRunStepDo {
	return j.withDO(j.DO.Offset(offset))
}

func (j jobRunStepDo) Scopes(funcs ...func(gen.Dao) gen.Dao) IJobRunStepDo {
	return j.withDO(j.DO.Scopes(funcs...))
}

func (j jobRunStepDo) Unscoped() IJobRunStepDo {
	return j.withDO(j.DO.Unscoped())
}

func (j jobRunStepDo) Create(values ...*models.JobRunStep) error {
	if len(values) == 0 {
		return nil
	}
	return j.DO.Create(values)
}

func (j jobRunStepDo) CreateInBatches(values []*models.JobRunStep, batchSize int) error {
	return j.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (j jobRunStepDo) Save(values ...*models.JobRunStep) error {
	if len(values) == 0 {
		return nil
	}
	return j.DO.Save(values)
}

func (j jobRunStepDo) First() (*models.JobRunStep, error) {
	if result, err := j.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*models.JobRunStep), nil
	}
}

func (j jobRunStepDo) Take() (*models.JobRunStep, error) {
	if result, err := j.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*models.JobRunStep), nil
	}
}

func (j jobRunStepDo) Last() (*models.JobRunStep, error) {
	if result, err := j.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*models.JobRunStep), nil
	}
}

func (j jobRunStepDo) Find() ([]*models.JobRunStep, error) {
	result, err := j.DO.Find()
	return result.([]*models.JobRunStep), err
}

func (j jobRunStepDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*models.JobRunStep, err error) {
	buf := make([]*models.JobRunStep, 0, batchSize)
	err = j.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (j jobRunStepDo) FindInBatches(result *[]*models.JobRunStep, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return j.DO.FindInBatches(result, batchSize, fc)
}

func (j jobRunStepDo) Attrs(attrs ...field.AssignExpr) IJobRunStepDo {
	return j.withDO(j.DO.Attrs(attrs...))
}

func (j jobRunStepDo) Assign(attrs ...field.AssignExpr) IJobRunStepDo {
	return j.withDO(j.DO.Assign(attrs...))
}

func (j jobRunStepDo) Joins(fields ...field.RelationField) IJobRunStepDo {
	for _, _f := range fields {
		j = *j.withDO(j.DO.Joins(_f))
	}
	return &j
}

func (j jobRunStepDo) Preload(fields ...field.RelationField) IJobRunStepDo {
	for _, _f := range fields {
		j = *j.withDO(j.DO.Preload(_f))
	}
	return &j
}

func (j jobRunStepDo) FirstOrInit() (*models.JobRunStep, error) {
	if result, err := j.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*models.JobRunStep), nil
	}
}

func (j jobRunStepDo) FirstOrCreate() (*models.JobRunStep, error) {
	if result, err := j.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*models.JobRunStep), nil
	}
}

func (j jobRunStepDo) FindByPage(offset int, limit int) (result []*models.JobRunStep, count int64, err error) {
	result, err = j.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = j.Offset(-1).Limit(-1).Count()
	return
}

func (j jobRunStepDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = j.Count()
	if err != nil {
		return
	}

	err = j.Offset(offset).Limit(limit).Scan(result)
	return
}

func (j jobRunStepDo) Scan(result interface{}) (err error) {
	return j.DO.Scan(result)
}

func (j jobRunStepDo) Delete(models ...*models.JobRunStep) (result gen.ResultInfo, err error) {
	return j.DO.Delete(models)
}

func (j *jobRunStepDo) withDO(do gen.Dao) *jobRunStepDo {
	j.DO = *do.(*gen.DO)
	return j
}
