// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package db

import (
	"context"
	"database/sql"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"chronix/internal/db/models"
)

func newJobVariable(db *gorm.DB, opts ...gen.DOOption) jobVariable {
	_jobVariable := jobVariable{}

	_jobVariable.jobVariableDo.UseDB(db, opts...)
	_jobVariable.jobVariableDo.UseModel(&models.JobVariable{})

	tableName := _jobVariable.jobVariableDo.TableName()
	_jobVariable.ALL = field.NewAsterisk(tableName)
	_jobVariable.ID = field.NewInt64(tableName, "id")
	_jobVariable.JobID = field.NewInt64(tableName, "job_id")
	_jobVariable.Name = field.NewString(tableName, "name")
	_jobVariable.Value = field.NewString(tableName, "value")

	_jobVariable.fillFieldMap()

	return _jobVariable
}

type jobVariable struct {
	jobVariableDo

	ALL   field.Asterisk
	ID    field.Int64
	JobID field.Int64
	Name  field.String
	Value field.String

	fieldMap map[string]field.Expr
}

func (j jobVariable) Table(newTableName string) *jobVariable {
	j.jobVariableDo.UseTable(newTableName)
	return j.updateTableName(newTableName)
}

func (j jobVariable) As(alias string) *jobVariable {
	j.jobVariableDo.DO = *(j.jobVariableDo.As(alias).(*gen.DO))
	return j.updateTableName(alias)
}

func (j *jobVariable) updateTableName(table string) *jobVariable {
	j.ALL = field.NewAsterisk(table)
	j.ID = field.NewInt64(table, "id")
	j.JobID = field.NewInt64(table, "job_id")
	j.Name = field.NewString(table, "name")
	j.Value = field.NewString(table, "value")

	j.fillFieldMap()

	return j
}

func (j *jobVariable) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := j.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (j *jobVariable) fillFieldMap() {
	j.fieldMap = make(map[string]field.Expr, 4)
	j.fieldMap["id"] = j.ID
	j.fieldMap["job_id"] = j.JobID
	j.fieldMap["name"] = j.Name
	j.fieldMap["value"] = j.Value
}

func (j jobVariable) clone(db *gorm.DB) jobVariable {
	j.jobVariableDo.ReplaceConnPool(db.Statement.ConnPool)
	return j
}

func (j jobVariable) replaceDB(db *gorm.DB) jobVariable {
	j.jobVariableDo.ReplaceDB(db)
	return j
}

type jobVariableDo struct{ gen.DO }

type IJobVariableDo interface {
	gen.SubQuery
	Debug() IJobVariableDo
	WithContext(ctx context.Context) IJobVariableDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() IJobVariableDo
	WriteDB() IJobVariableDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) IJobVariableDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) IJobVariableDo
	Not(conds ...gen.Condition) IJobVariableDo
	Or(conds ...gen.Condition) IJobVariableDo
	Select(conds ...field.Expr) IJobVariableDo
	Where(conds ...gen.Condition) IJobVariableDo
	Order(conds ...field.Expr) IJobVariableDo
	Distinct(cols ...field.Expr) IJobVariableDo
	Omit(cols ...field.Expr) IJobVariableDo
	Join(table schema.Tabler, on ...field.Expr) IJobVariableDo
	LeftJoin(table schema.Tabler, on ...field.Expr) IJobVariableDo
	RightJoin(table schema.Tabler, on ...field.Expr) IJobVariableDo
	Group(cols ...field.Expr) IJobVariableDo
	Having(conds ...gen.Condition) IJobVariableDo
	Limit(limit int) IJobVariableDo
	Offset(offset int) IJobVariableDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) IJobVariableDo
	Unscoped() IJobVariableDo
	Create(values ...*models.JobVariable) error
	CreateInBatches(values []*models.JobVariable, batchSize int) error
	Save(values ...*models.JobVariable) error
	First() (*models.JobVariable, error)
	Take() (*models.JobVariable, error)
	Last() (*models.JobVariable, error)
	Find() ([]*models.JobVariable, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*models.JobVariable, err error)
	FindInBatches(result *[]*models.JobVariable, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*models.JobVariable) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) IJobVariableDo
	Assign(attrs ...field.AssignExpr) IJobVariableDo
	Joins(fields ...field.RelationField) IJobVariableDo
	Preload(fields ...field.RelationField) IJobVariableDo
	FirstOrInit() (*models.JobVariable, error)
	FirstOrCreate() (*models.JobVariable, error)
	FindByPage(offset int, limit int) (result []*models.JobVariable, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Rows() (*sql.Rows, error)
	Row() *sql.Row
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) IJobVariableDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (j jobVariableDo) Debug() IJobVariableDo {
	return j.withDO(j.DO.Debug())
}

func (j jobVariableDo) WithContext(ctx context.Context) IJobVariableDo {
	return j.withDO(j.DO.WithContext(ctx))
}

func (j jobVariableDo) ReadDB() IJobVariableDo {
	return j.Clauses(dbresolver.Read)
}

func (j jobVariableDo) WriteDB() IJobVariableDo {
	return j.Clauses(dbresolver.Write)
}

func (j jobVariableDo) Session(config *gorm.Session) IJobVariableDo {
	return j.withDO(j.DO.Session(config))
}

func (j jobVariableDo) Clauses(conds ...clause.Expression) IJobVariableDo {
	return j.withDO(j.DO.Clauses(conds...))
}

func (j jobVariableDo) Returning(value interface{}, columns ...string) IJobVariableDo {
	return j.withDO(j.DO.Returning(value, columns...))
}

func (j jobVariableDo) Not(conds ...gen.Condition) IJobVariableDo {
	return j.withDO(j.DO.Not(conds...))
}

func (j jobVariableDo) Or(conds ...gen.Condition) IJobVariableDo {
	return j.withDO(j.DO.Or(conds...))
}

func (j jobVariableDo) Select(conds ...field.Expr) IJobVariableDo {
	return j.withDO(j.DO.Select(conds...))
}

func (j jobVariableDo) Where(conds ...gen.Condition) IJobVariableDo {
	return j.withDO(j.DO.Where(conds...))
}

func (j jobVariableDo) Order(conds ...field.Expr) IJobVariableDo {
	return j.withDO(j.DO.Order(conds...))
}

func (j jobVariableDo) Distinct(cols ...field.Expr) IJobVariableDo {
	return j.withDO(j.DO.Distinct(cols...))
}

func (j jobVariableDo) Omit(cols ...field.Expr) IJobVariableDo {
	return j.withDO(j.DO.Omit(cols...))
}

func (j jobVariableDo) Join(table schema.Tabler, on ...field.Expr) IJobVariableDo {
	return j.withDO(j.DO.Join(table, on...))
}

func (j jobVariableDo) LeftJoin(table schema.Tabler, on ...field.Expr) IJobVariableDo {
	return j.withDO(j.DO.LeftJoin(table, on...))
}

func (j jobVariableDo) RightJoin(table schema.Tabler, on ...field.Expr) IJobVariableDo {
	return j.withDO(j.DO.RightJoin(table, on...))
}

func (j jobVariableDo) Group(cols ...field.Expr) IJobVariableDo {
	return j.withDO(j.DO.Group(cols...))
}

func (j jobVariableDo) Having(conds ...gen.Condition) IJobVariableDo {
	return j.withDO(j.DO.Having(conds...))
}

func (j jobVariableDo) Limit(limit int) IJobVariableDo {
	return j.withDO(j.DO.Limit(limit))
}

func (j jobVariableDo) Offset(offset int) IJobVariableDo {
	return j.withDO(j.DO.Offset(offset))
}

func (j jobVariableDo) Scopes(funcs ...func(gen.Dao) gen.Dao) IJobVariableDo {
	return j.withDO(j.DO.Scopes(funcs...))
}

func (j jobVariableDo) Unscoped() IJobVariableDo {
	return j.withDO(j.DO.Unscoped())
}

func (j jobVariableDo) Create(values ...*models.JobVariable) error {
	if len(values) == 0 {
		return nil
	}
	return j.DO.Create(values)
}

func (j jobVariableDo) CreateInBatches(values []*models.JobVariable, batchSize int) error {
	return j.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (j jobVariableDo) Save(values ...*models.JobVariable) error {
	if len(values) == 0 {
		return nil
	}
	return j.DO.Save(values)
}

func (j jobVariableDo) First() (*models.JobVariable, error) {
	if result, err := j.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*models.JobVariable), nil
	}
}

func (j jobVariableDo) Take() (*models.JobVariable, error) {
	if result, err := j.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*models.JobVariable), nil
	}
}

func (j jobVariableDo) Last() (*models.JobVariable, error) {
	if result, err := j.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*models.JobVariable), nil
	}
}

func (j jobVariableDo) Find() ([]*models.JobVariable, error) {
	result, err := j.DO.Find()
	return result.([]*models.JobVariable), err
}

func (j jobVariableDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*models.JobVariable, err error) {
	buf := make([]*models.JobVariable, 0, batchSize)
	err = j.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (j jobVariableDo) FindInBatches(result *[]*models.JobVariable, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return j.DO.FindInBatches(result, batchSize, fc)
}

func (j jobVariableDo) Attrs(attrs ...field.AssignExpr) IJobVariableDo {
	return j.withDO(j.DO.Attrs(attrs...))
}

func (j jobVariableDo) Assign(attrs ...field.AssignExpr) IJobVariableDo {
	return j.withDO(j.DO.Assign(attrs...))
}

func (j jobVariableDo) Joins(fields ...field.RelationField) IJobVariableDo {
	for _, _f := range fields {
		j = *j.withDO(j.DO.Joins(_f))
	}
	return &j
}

func (j jobVariableDo) Preload(fields ...field.RelationField) IJobVariableDo {
	for _, _f := range fields {
		j = *j.withDO(j.DO.Preload(_f))
	}
	return &j
}

func (j jobVariableDo) FirstOrInit() (*models.JobVariable, error) {
	if result, err := j.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*models.JobVariable), nil
	}
}

func (j jobVariableDo) FirstOrCreate() (*models.JobVariable, error) {
	if result, err := j.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*models.JobVariable), nil
	}
}

func (j jobVariableDo) FindByPage(offset int, limit int) (result []*models.JobVariable, count int64, err error) {
	result, err = j.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = j.Offset(-1).Limit(-1).Count()
	return
}

func (j jobVariableDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = j.Count()
	if err != nil {
		return
	}

	err = j.Offset(offset).Limit(limit).Scan(result)
	return
}

func (j jobVariableDo) Scan(result interface{}) (err error) {
	return j.DO.Scan(result)
}

func (j jobVariableDo) Delete(models ...*models.JobVariable) (result gen.ResultInfo, err error) {
	return j.DO.Delete(models)
}

func (j *jobVariableDo) withDO(do gen.Dao) *jobVariableDo {
	j.DO = *do.(*gen.DO)
	return j
}
