// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package db

import (
	"context"
	"database/sql"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"chronix/internal/db/models"
)

func newNotificationRecipient(db *gorm.DB, opts ...gen.DOOption) notificationRecipient {
	_notificationRecipient := notificationRecipient{}

	_notificationRecipient.notificationRecipientDo.UseDB(db, opts...)
	_notificationRecipient.notificationRecipientDo.UseModel(&models.NotificationRecipient{})

	tableName := _notificationRecipient.notificationRecipientDo.TableName()
	_notificationRecipient.ALL = field.NewAsterisk(tableName)
	_notificationRecipient.NotificationID = field.NewInt64(tableName, "notification_id")
	_notificationRecipient.UserID = field.NewInt64(tableName, "user_id")
	_notificationRecipient.Seen = field.NewBool(tableName, "seen")
	_notificationRecipient.SeenAt = field.NewTime(tableName, "seen_at")
	_notificationRecipient.RemovedAt = field.NewTime(tableName, "removed_at")
	_notificationRecipient.DeliveredAt = field.NewTime(tableName, "delivered_at")

	_notificationRecipient.fillFieldMap()

	return _notificationRecipient
}

type notificationRecipient struct {
	notificationRecipientDo

	ALL            field.Asterisk
	NotificationID field.Int64
	UserID         field.Int64
	Seen           field.Bool
	SeenAt         field.Time
	RemovedAt      field.Time
	DeliveredAt    field.Time

	fieldMap map[string]field.Expr
}

func (n notificationRecipient) Table(newTableName string) *notificationRecipient {
	n.notificationRecipientDo.UseTable(newTableName)
	return n.updateTableName(newTableName)
}

func (n notificationRecipient) As(alias string) *notificationRecipient {
	n.notificationRecipientDo.DO = *(n.notificationRecipientDo.As(alias).(*gen.DO))
	return n.updateTableName(alias)
}

func (n *notificationRecipient) updateTableName(table string) *notificationRecipient {
	n.ALL = field.NewAsterisk(table)
	n.NotificationID = field.NewInt64(table, "notification_id")
	n.UserID = field.NewInt64(table, "user_id")
	n.Seen = field.NewBool(table, "seen")
	n.SeenAt = field.NewTime(table, "seen_at")
	n.RemovedAt = field.NewTime(table, "removed_at")
	n.DeliveredAt = field.NewTime(table, "delivered_at")

	n.fillFieldMap()

	return n
}

func (n *notificationRecipient) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := n.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (n *notificationRecipient) fillFieldMap() {
	n.fieldMap = make(map[string]field.Expr, 6)
	n.fieldMap["notification_id"] = n.NotificationID
	n.fieldMap["user_id"] = n.UserID
	n.fieldMap["seen"] = n.Seen
	n.fieldMap["seen_at"] = n.SeenAt
	n.fieldMap["removed_at"] = n.RemovedAt
	n.fieldMap["delivered_at"] = n.DeliveredAt
}

func (n notificationRecipient) clone(db *gorm.DB) notificationRecipient {
	n.notificationRecipientDo.ReplaceConnPool(db.Statement.ConnPool)
	return n
}

func (n notificationRecipient) replaceDB(db *gorm.DB) notificationRecipient {
	n.notificationRecipientDo.ReplaceDB(db)
	return n
}

type notificationRecipientDo struct{ gen.DO }

type INotificationRecipientDo interface {
	gen.SubQuery
	Debug() INotificationRecipientDo
	WithContext(ctx context.Context) INotificationRecipientDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() INotificationRecipientDo
	WriteDB() INotificationRecipientDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) INotificationRecipientDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) INotificationRecipientDo
	Not(conds ...gen.Condition) INotificationRecipientDo
	Or(conds ...gen.Condition) INotificationRecipientDo
	Select(conds ...field.Expr) INotificationRecipientDo
	Where(conds ...gen.Condition) INotificationRecipientDo
	Order(conds ...field.Expr) INotificationRecipientDo
	Distinct(cols ...field.Expr) INotificationRecipientDo
	Omit(cols ...field.Expr) INotificationRecipientDo
	Join(table schema.Tabler, on ...field.Expr) INotificationRecipientDo
	LeftJoin(table schema.Tabler, on ...field.Expr) INotificationRecipientDo
	RightJoin(table schema.Tabler, on ...field.Expr) INotificationRecipientDo
	Group(cols ...field.Expr) INotificationRecipientDo
	Having(conds ...gen.Condition) INotificationRecipientDo
	Limit(limit int) INotificationRecipientDo
	Offset(offset int) INotificationRecipientDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) INotificationRecipientDo
	Unscoped() INotificationRecipientDo
	Create(values ...*models.NotificationRecipient) error
	CreateInBatches(values []*models.NotificationRecipient, batchSize int) error
	Save(values ...*models.NotificationRecipient) error
	First() (*models.NotificationRecipient, error)
	Take() (*models.NotificationRecipient, error)
	Last() (*models.NotificationRecipient, error)
	Find() ([]*models.NotificationRecipient, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*models.NotificationRecipient, err error)
	FindInBatches(result *[]*models.NotificationRecipient, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*models.NotificationRecipient) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) INotificationRecipientDo
	Assign(attrs ...field.AssignExpr) INotificationRecipientDo
	Joins(fields ...field.RelationField) INotificationRecipientDo
	Preload(fields ...field.RelationField) INotificationRecipientDo
	FirstOrInit() (*models.NotificationRecipient, error)
	FirstOrCreate() (*models.NotificationRecipient, error)
	FindByPage(offset int, limit int) (result []*models.NotificationRecipient, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Rows() (*sql.Rows, error)
	Row() *sql.Row
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) INotificationRecipientDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (n notificationRecipientDo) Debug() INotificationRecipientDo {
	return n.withDO(n.DO.Debug())
}

func (n notificationRecipientDo) WithContext(ctx context.Context) INotificationRecipientDo {
	return n.withDO(n.DO.WithContext(ctx))
}

func (n notificationRecipientDo) ReadDB() INotificationRecipientDo {
	return n.Clauses(dbresolver.Read)
}

func (n notificationRecipientDo) WriteDB() INotificationRecipientDo {
	return n.Clauses(dbresolver.Write)
}

func (n notificationRecipientDo) Session(config *gorm.Session) INotificationRecipientDo {
	return n.withDO(n.DO.Session(config))
}

func (n notificationRecipientDo) Clauses(conds ...clause.Expression) INotificationRecipientDo {
	return n.withDO(n.DO.Clauses(conds...))
}

func (n notificationRecipientDo) Returning(value interface{}, columns ...string) INotificationRecipientDo {
	return n.withDO(n.DO.Returning(value, columns...))
}

func (n notificationRecipientDo) Not(conds ...gen.Condition) INotificationRecipientDo {
	return n.withDO(n.DO.Not(conds...))
}

func (n notificationRecipientDo) Or(conds ...gen.Condition) INotificationRecipientDo {
	return n.withDO(n.DO.Or(conds...))
}

func (n notificationRecipientDo) Select(conds ...field.Expr) INotificationRecipientDo {
	return n.withDO(n.DO.Select(conds...))
}

func (n notificationRecipientDo) Where(conds ...gen.Condition) INotificationRecipientDo {
	return n.withDO(n.DO.Where(conds...))
}

func (n notificationRecipientDo) Order(conds ...field.Expr) INotificationRecipientDo {
	return n.withDO(n.DO.Order(conds...))
}

func (n notificationRecipientDo) Distinct(cols ...field.Expr) INotificationRecipientDo {
	return n.withDO(n.DO.Distinct(cols...))
}

func (n notificationRecipientDo) Omit(cols ...field.Expr) INotificationRecipientDo {
	return n.withDO(n.DO.Omit(cols...))
}

func (n notificationRecipientDo) Join(table schema.Tabler, on ...field.Expr) INotificationRecipientDo {
	return n.withDO(n.DO.Join(table, on...))
}

func (n notificationRecipientDo) LeftJoin(table schema.Tabler, on ...field.Expr) INotificationRecipientDo {
	return n.withDO(n.DO.LeftJoin(table, on...))
}

func (n notificationRecipientDo) RightJoin(table schema.Tabler, on ...field.Expr) INotificationRecipientDo {
	return n.withDO(n.DO.RightJoin(table, on...))
}

func (n notificationRecipientDo) Group(cols ...field.Expr) INotificationRecipientDo {
	return n.withDO(n.DO.Group(cols...))
}

func (n notificationRecipientDo) Having(conds ...gen.Condition) INotificationRecipientDo {
	return n.withDO(n.DO.Having(conds...))
}

func (n notificationRecipientDo) Limit(limit int) INotificationRecipientDo {
	return n.withDO(n.DO.Limit(limit))
}

func (n notificationRecipientDo) Offset(offset int) INotificationRecipientDo {
	return n.withDO(n.DO.Offset(offset))
}

func (n notificationRecipientDo) Scopes(funcs ...func(gen.Dao) gen.Dao) INotificationRecipientDo {
	return n.withDO(n.DO.Scopes(funcs...))
}

func (n notificationRecipientDo) Unscoped() INotificationRecipientDo {
	return n.withDO(n.DO.Unscoped())
}

func (n notificationRecipientDo) Create(values ...*models.NotificationRecipient) error {
	if len(values) == 0 {
		return nil
	}
	return n.DO.Create(values)
}

func (n notificationRecipientDo) CreateInBatches(values []*models.NotificationRecipient, batchSize int) error {
	return n.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (n notificationRecipientDo) Save(values ...*models.NotificationRecipient) error {
	if len(values) == 0 {
		return nil
	}
	return n.DO.Save(values)
}

func (n notificationRecipientDo) First() (*models.NotificationRecipient, error) {
	if result, err := n.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*models.NotificationRecipient), nil
	}
}

func (n notificationRecipientDo) Take() (*models.NotificationRecipient, error) {
	if result, err := n.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*models.NotificationRecipient), nil
	}
}

func (n notificationRecipientDo) Last() (*models.NotificationRecipient, error) {
	if result, err := n.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*models.NotificationRecipient), nil
	}
}

func (n notificationRecipientDo) Find() ([]*models.NotificationRecipient, error) {
	result, err := n.DO.Find()
	return result.([]*models.NotificationRecipient), err
}

func (n notificationRecipientDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*models.NotificationRecipient, err error) {
	buf := make([]*models.NotificationRecipient, 0, batchSize)
	err = n.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (n notificationRecipientDo) FindInBatches(result *[]*models.NotificationRecipient, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return n.DO.FindInBatches(result, batchSize, fc)
}

func (n notificationRecipientDo) Attrs(attrs ...field.AssignExpr) INotificationRecipientDo {
	return n.withDO(n.DO.Attrs(attrs...))
}

func (n notificationRecipientDo) Assign(attrs ...field.AssignExpr) INotificationRecipientDo {
	return n.withDO(n.DO.Assign(attrs...))
}

func (n notificationRecipientDo) Joins(fields ...field.RelationField) INotificationRecipientDo {
	for _, _f := range fields {
		n = *n.withDO(n.DO.Joins(_f))
	}
	return &n
}

func (n notificationRecipientDo) Preload(fields ...field.RelationField) INotificationRecipientDo {
	for _, _f := range fields {
		n = *n.withDO(n.DO.Preload(_f))
	}
	return &n
}

func (n notificationRecipientDo) FirstOrInit() (*models.NotificationRecipient, error) {
	if result, err := n.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*models.NotificationRecipient), nil
	}
}

func (n notificationRecipientDo) FirstOrCreate() (*models.NotificationRecipient, error) {
	if result, err := n.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*models.NotificationRecipient), nil
	}
}

func (n notificationRecipientDo) FindByPage(offset int, limit int) (result []*models.NotificationRecipient, count int64, err error) {
	result, err = n.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = n.Offset(-1).Limit(-1).Count()
	return
}

func (n notificationRecipientDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = n.Count()
	if err != nil {
		return
	}

	err = n.Offset(offset).Limit(limit).Scan(result)
	return
}

func (n notificationRecipientDo) Scan(result interface{}) (err error) {
	return n.DO.Scan(result)
}

func (n notificationRecipientDo) Delete(models ...*models.NotificationRecipient) (result gen.ResultInfo, err error) {
	return n.DO.Delete(models)
}

func (n *notificationRecipientDo) withDO(do gen.Dao) *notificationRecipientDo {
	n.DO = *do.(*gen.DO)
	return n
}
