// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package db

import (
	"context"
	"database/sql"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"chronix/internal/db/models"
)

func newShellActionStep(db *gorm.DB, opts ...gen.DOOption) shellActionStep {
	_shellActionStep := shellActionStep{}

	_shellActionStep.shellActionStepDo.UseDB(db, opts...)
	_shellActionStep.shellActionStepDo.UseModel(&models.ShellActionStep{})

	tableName := _shellActionStep.shellActionStepDo.TableName()
	_shellActionStep.ALL = field.NewAsterisk(tableName)
	_shellActionStep.ID = field.NewInt64(tableName, "id")
	_shellActionStep.ActionID = field.NewInt64(tableName, "action_id")
	_shellActionStep.StepOrder = field.NewInt64(tableName, "step_order")
	_shellActionStep.Name = field.NewString(tableName, "name")
	_shellActionStep.RunMode = field.NewString(tableName, "run_mode")
	_shellActionStep.Command = field.NewString(tableName, "command")
	_shellActionStep.ScriptText = field.NewString(tableName, "script_text")
	_shellActionStep.ShellPath = field.NewString(tableName, "shell_path")
	_shellActionStep.WorkingDir = field.NewString(tableName, "working_dir")
	_shellActionStep.TimeoutSeconds = field.NewInt64(tableName, "timeout_seconds")
	_shellActionStep.EnvJSON = field.NewField(tableName, "env_json")
	_shellActionStep.OutputCaptureMaxBytes = field.NewInt64(tableName, "output_capture_max_bytes")
	_shellActionStep.OutputTruncation = field.NewString(tableName, "output_truncation")
	_shellActionStep.Expectation = field.NewField(tableName, "expectation")
	_shellActionStep.OutputCapture = field.NewField(tableName, "output_capture")
	_shellActionStep.OnFailure = field.NewString(tableName, "on_failure")

	_shellActionStep.fillFieldMap()

	return _shellActionStep
}

type shellActionStep struct {
	shellActionStepDo

	ALL                   field.Asterisk
	ID                    field.Int64
	ActionID              field.Int64
	StepOrder             field.Int64
	Name                  field.String
	RunMode               field.String
	Command               field.String
	ScriptText            field.String
	ShellPath             field.String
	WorkingDir            field.String
	TimeoutSeconds        field.Int64
	EnvJSON               field.Field
	OutputCaptureMaxBytes field.Int64
	OutputTruncation      field.String
	Expectation           field.Field
	OutputCapture         field.Field
	OnFailure             field.String

	fieldMap map[string]field.Expr
}

func (s shellActionStep) Table(newTableName string) *shellActionStep {
	s.shellActionStepDo.UseTable(newTableName)
	return s.updateTableName(newTableName)
}

func (s shellActionStep) As(alias string) *shellActionStep {
	s.shellActionStepDo.DO = *(s.shellActionStepDo.As(alias).(*gen.DO))
	return s.updateTableName(alias)
}

func (s *shellActionStep) updateTableName(table string) *shellActionStep {
	s.ALL = field.NewAsterisk(table)
	s.ID = field.NewInt64(table, "id")
	s.ActionID = field.NewInt64(table, "action_id")
	s.StepOrder = field.NewInt64(table, "step_order")
	s.Name = field.NewString(table, "name")
	s.RunMode = field.NewString(table, "run_mode")
	s.Command = field.NewString(table, "command")
	s.ScriptText = field.NewString(table, "script_text")
	s.ShellPath = field.NewString(table, "shell_path")
	s.WorkingDir = field.NewString(table, "working_dir")
	s.TimeoutSeconds = field.NewInt64(table, "timeout_seconds")
	s.EnvJSON = field.NewField(table, "env_json")
	s.OutputCaptureMaxBytes = field.NewInt64(table, "output_capture_max_bytes")
	s.OutputTruncation = field.NewString(table, "output_truncation")
	s.Expectation = field.NewField(table, "expectation")
	s.OutputCapture = field.NewField(table, "output_capture")
	s.OnFailure = field.NewString(table, "on_failure")

	s.fillFieldMap()

	return s
}

func (s *shellActionStep) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := s.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (s *shellActionStep) fillFieldMap() {
	s.fieldMap = make(map[string]field.Expr, 16)
	s.fieldMap["id"] = s.ID
	s.fieldMap["action_id"] = s.ActionID
	s.fieldMap["step_order"] = s.StepOrder
	s.fieldMap["name"] = s.Name
	s.fieldMap["run_mode"] = s.RunMode
	s.fieldMap["command"] = s.Command
	s.fieldMap["script_text"] = s.ScriptText
	s.fieldMap["shell_path"] = s.ShellPath
	s.fieldMap["working_dir"] = s.WorkingDir
	s.fieldMap["timeout_seconds"] = s.TimeoutSeconds
	s.fieldMap["env_json"] = s.EnvJSON
	s.fieldMap["output_capture_max_bytes"] = s.OutputCaptureMaxBytes
	s.fieldMap["output_truncation"] = s.OutputTruncation
	s.fieldMap["expectation"] = s.Expectation
	s.fieldMap["output_capture"] = s.OutputCapture
	s.fieldMap["on_failure"] = s.OnFailure
}

func (s shellActionStep) clone(db *gorm.DB) shellActionStep {
	s.shellActionStepDo.ReplaceConnPool(db.Statement.ConnPool)
	return s
}

func (s shellActionStep) replaceDB(db *gorm.DB) shellActionStep {
	s.shellActionStepDo.ReplaceDB(db)
	return s
}

type shellActionStepDo struct{ gen.DO }

type IShellActionStepDo interface {
	gen.SubQuery
	Debug() IShellActionStepDo
	WithContext(ctx context.Context) IShellActionStepDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() IShellActionStepDo
	WriteDB() IShellActionStepDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) IShellActionStepDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) IShellActionStepDo
	Not(conds ...gen.Condition) IShellActionStepDo
	Or(conds ...gen.Condition) IShellActionStepDo
	Select(conds ...field.Expr) IShellActionStepDo
	Where(conds ...gen.Condition) IShellActionStepDo
	Order(conds ...field.Expr) IShellActionStepDo
	Distinct(cols ...field.Expr) IShellActionStepDo
	Omit(cols ...field.Expr) IShellActionStepDo
	Join(table schema.Tabler, on ...field.Expr) IShellActionStepDo
	LeftJoin(table schema.Tabler, on ...field.Expr) IShellActionStepDo
	RightJoin(table schema.Tabler, on ...field.Expr) IShellActionStepDo
	Group(cols ...field.Expr) IShellActionStepDo
	Having(conds ...gen.Condition) IShellActionStepDo
	Limit(limit int) IShellActionStepDo
	Offset(offset int) IShellActionStepDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) IShellActionStepDo
	Unscoped() IShellActionStepDo
	Create(values ...*models.ShellActionStep) error
	CreateInBatches(values []*models.ShellActionStep, batchSize int) error
	Save(values ...*models.ShellActionStep) error
	First() (*models.ShellActionStep, error)
	Take() (*models.ShellActionStep, error)
	Last() (*models.ShellActionStep, error)
	Find() ([]*models.ShellActionStep, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*models.ShellActionStep, err error)
	FindInBatches(result *[]*models.ShellActionStep, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*models.ShellActionStep) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) IShellActionStepDo
	Assign(attrs ...field.AssignExpr) IShellActionStepDo
	Joins(fields ...field.RelationField) IShellActionStepDo
	Preload(fields ...field.RelationField) IShellActionStepDo
	FirstOrInit() (*models.ShellActionStep, error)
	FirstOrCreate() (*models.ShellActionStep, error)
	FindByPage(offset int, limit int) (result []*models.ShellActionStep, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Rows() (*sql.Rows, error)
	Row() *sql.Row
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) IShellActionStepDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (s shellActionStepDo) Debug() IShellActionStepDo {
	return s.withDO(s.DO.Debug())
}

func (s shellActionStepDo) WithContext(ctx context.Context) IShellActionStepDo {
	return s.withDO(s.DO.WithContext(ctx))
}

func (s shellActionStepDo) ReadDB() IShellActionStepDo {
	return s.Clauses(dbresolver.Read)
}

func (s shellActionStepDo) WriteDB() IShellActionStepDo {
	return s.Clauses(dbresolver.Write)
}

func (s shellActionStepDo) Session(config *gorm.Session) IShellActionStepDo {
	return s.withDO(s.DO.Session(config))
}

func (s shellActionStepDo) Clauses(conds ...clause.Expression) IShellActionStepDo {
	return s.withDO(s.DO.Clauses(conds...))
}

func (s shellActionStepDo) Returning(value interface{}, columns ...string) IShellActionStepDo {
	return s.withDO(s.DO.Returning(value, columns...))
}

func (s shellActionStepDo) Not(conds ...gen.Condition) IShellActionStepDo {
	return s.withDO(s.DO.Not(conds...))
}

func (s shellActionStepDo) Or(conds ...gen.Condition) IShellActionStepDo {
	return s.withDO(s.DO.Or(conds...))
}

func (s shellActionStepDo) Select(conds ...field.Expr) IShellActionStepDo {
	return s.withDO(s.DO.Select(conds...))
}

func (s shellActionStepDo) Where(conds ...gen.Condition) IShellActionStepDo {
	return s.withDO(s.DO.Where(conds...))
}

func (s shellActionStepDo) Order(conds ...field.Expr) IShellActionStepDo {
	return s.withDO(s.DO.Order(conds...))
}

func (s shellActionStepDo) Distinct(cols ...field.Expr) IShellActionStepDo {
	return s.withDO(s.DO.Distinct(cols...))
}

func (s shellActionStepDo) Omit(cols ...field.Expr) IShellActionStepDo {
	return s.withDO(s.DO.Omit(cols...))
}

func (s shellActionStepDo) Join(table schema.Tabler, on ...field.Expr) IShellActionStepDo {
	return s.withDO(s.DO.Join(table, on...))
}

func (s shellActionStepDo) LeftJoin(table schema.Tabler, on ...field.Expr) IShellActionStepDo {
	return s.withDO(s.DO.LeftJoin(table, on...))
}

func (s shellActionStepDo) RightJoin(table schema.Tabler, on ...field.Expr) IShellActionStepDo {
	return s.withDO(s.DO.RightJoin(table, on...))
}

func (s shellActionStepDo) Group(cols ...field.Expr) IShellActionStepDo {
	return s.withDO(s.DO.Group(cols...))
}

func (s shellActionStepDo) Having(conds ...gen.Condition) IShellActionStepDo {
	return s.withDO(s.DO.Having(conds...))
}

func (s shellActionStepDo) Limit(limit int) IShellActionStepDo {
	return s.withDO(s.DO.Limit(limit))
}

func (s shellActionStepDo) Offset(offset int) IShellActionStepDo {
	return s.withDO(s.DO.Offset(offset))
}

func (s shellActionStepDo) Scopes(funcs ...func(gen.Dao) gen.Dao) IShellActionStepDo {
	return s.withDO(s.DO.Scopes(funcs...))
}

func (s shellActionStepDo) Unscoped() IShellActionStepDo {
	return s.withDO(s.DO.Unscoped())
}

func (s shellActionStepDo) Create(values ...*models.ShellActionStep) error {
	if len(values) == 0 {
		return nil
	}
	return s.DO.Create(values)
}

func (s shellActionStepDo) CreateInBatches(values []*models.ShellActionStep, batchSize int) error {
	return s.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (s shellActionStepDo) Save(values ...*models.ShellActionStep) error {
	if len(values) == 0 {
		return nil
	}
	return s.DO.Save(values)
}

func (s shellActionStepDo) First() (*models.ShellActionStep, error) {
	if result, err := s.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*models.ShellActionStep), nil
	}
}

func (s shellActionStepDo) Take() (*models.ShellActionStep, error) {
	if result, err := s.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*models.ShellActionStep), nil
	}
}

func (s shellActionStepDo) Last() (*models.ShellActionStep, error) {
	if result, err := s.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*models.ShellActionStep), nil
	}
}

func (s shellActionStepDo) Find() ([]*models.ShellActionStep, error) {
	result, err := s.DO.Find()
	return result.([]*models.ShellActionStep), err
}

func (s shellActionStepDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*models.ShellActionStep, err error) {
	buf := make([]*models.ShellActionStep, 0, batchSize)
	err = s.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (s shellActionStepDo) FindInBatches(result *[]*models.ShellActionStep, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return s.DO.FindInBatches(result, batchSize, fc)
}

func (s shellActionStepDo) Attrs(attrs ...field.AssignExpr) IShellActionStepDo {
	return s.withDO(s.DO.Attrs(attrs...))
}

func (s shellActionStepDo) Assign(attrs ...field.AssignExpr) IShellActionStepDo {
	return s.withDO(s.DO.Assign(attrs...))
}

func (s shellActionStepDo) Joins(fields ...field.RelationField) IShellActionStepDo {
	for _, _f := range fields {
		s = *s.withDO(s.DO.Joins(_f))
	}
	return &s
}

func (s shellActionStepDo) Preload(fields ...field.RelationField) IShellActionStepDo {
	for _, _f := range fields {
		s = *s.withDO(s.DO.Preload(_f))
	}
	return &s
}

func (s shellActionStepDo) FirstOrInit() (*models.ShellActionStep, error) {
	if result, err := s.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*models.ShellActionStep), nil
	}
}

func (s shellActionStepDo) FirstOrCreate() (*models.ShellActionStep, error) {
	if result, err := s.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*models.ShellActionStep), nil
	}
}

func (s shellActionStepDo) FindByPage(offset int, limit int) (result []*models.ShellActionStep, count int64, err error) {
	result, err = s.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = s.Offset(-1).Limit(-1).Count()
	return
}

func (s shellActionStepDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = s.Count()
	if err != nil {
		return
	}

	err = s.Offset(offset).Limit(limit).Scan(result)
	return
}

func (s shellActionStepDo) Scan(result interface{}) (err error) {
	return s.DO.Scan(result)
}

func (s shellActionStepDo) Delete(models ...*models.ShellActionStep) (result gen.ResultInfo, err error) {
	return s.DO.Delete(models)
}

func (s *shellActionStepDo) withDO(do gen.Dao) *shellActionStepDo {
	s.DO = *do.(*gen.DO)
	return s
}
