// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package db

import (
	"context"
	"database/sql"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"chronix/internal/db/models"
)

func newShellConnection(db *gorm.DB, opts ...gen.DOOption) shellConnection {
	_shellConnection := shellConnection{}

	_shellConnection.shellConnectionDo.UseDB(db, opts...)
	_shellConnection.shellConnectionDo.UseModel(&models.ShellConnection{})

	tableName := _shellConnection.shellConnectionDo.TableName()
	_shellConnection.ALL = field.NewAsterisk(tableName)
	_shellConnection.ID = field.NewInt64(tableName, "id")
	_shellConnection.Name = field.NewString(tableName, "name")
	_shellConnection.Description = field.NewString(tableName, "description")
	_shellConnection.AgentUUID = field.NewString(tableName, "agent_uuid")
	_shellConnection.Mode = field.NewString(tableName, "mode")
	_shellConnection.RunAsUser = field.NewString(tableName, "run_as_user")
	_shellConnection.Sudo = field.NewBool(tableName, "sudo")
	_shellConnection.Host = field.NewString(tableName, "host")
	_shellConnection.Port = field.NewInt64(tableName, "port")
	_shellConnection.SSHUsername = field.NewString(tableName, "ssh_username")
	_shellConnection.AuthMethod = field.NewString(tableName, "auth_method")
	_shellConnection.SSHPassword = field.NewString(tableName, "ssh_password")
	_shellConnection.SSHPrivateKey = field.NewString(tableName, "ssh_private_key")
	_shellConnection.SSHKeyPass = field.NewString(tableName, "ssh_key_pass")
	_shellConnection.SudoPassword = field.NewString(tableName, "sudo_password")
	_shellConnection.AutoCheckEnabled = field.NewInt64(tableName, "auto_check_enabled")
	_shellConnection.AutoCheckIntervalSeconds = field.NewInt64(tableName, "auto_check_interval_seconds")
	_shellConnection.CreatedAt = field.NewTime(tableName, "created_at")
	_shellConnection.UpdatedAt = field.NewTime(tableName, "updated_at")
	_shellConnection.LastStatus = field.NewString(tableName, "last_status")
	_shellConnection.LastError = field.NewString(tableName, "last_error")
	_shellConnection.LastCheckedAt = field.NewTime(tableName, "last_checked_at")
	_shellConnection.AlertEmails = field.NewString(tableName, "alert_emails")
	_shellConnection.AlertPhones = field.NewString(tableName, "alert_phones")
	_shellConnection.NotifyOnFailure = field.NewBool(tableName, "notify_on_failure")
	_shellConnection.Enabled = field.NewBool(tableName, "enabled")
	_shellConnection.Suspended = field.NewBool(tableName, "suspended")

	_shellConnection.fillFieldMap()

	return _shellConnection
}

type shellConnection struct {
	shellConnectionDo

	ALL                      field.Asterisk
	ID                       field.Int64
	Name                     field.String
	Description              field.String
	AgentUUID                field.String
	Mode                     field.String
	RunAsUser                field.String
	Sudo                     field.Bool
	Host                     field.String
	Port                     field.Int64
	SSHUsername              field.String
	AuthMethod               field.String
	SSHPassword              field.String
	SSHPrivateKey            field.String
	SSHKeyPass               field.String
	SudoPassword             field.String
	AutoCheckEnabled         field.Int64
	AutoCheckIntervalSeconds field.Int64
	CreatedAt                field.Time
	UpdatedAt                field.Time
	LastStatus               field.String
	LastError                field.String
	LastCheckedAt            field.Time
	AlertEmails              field.String
	AlertPhones              field.String
	NotifyOnFailure          field.Bool
	Enabled                  field.Bool
	Suspended                field.Bool

	fieldMap map[string]field.Expr
}

func (s shellConnection) Table(newTableName string) *shellConnection {
	s.shellConnectionDo.UseTable(newTableName)
	return s.updateTableName(newTableName)
}

func (s shellConnection) As(alias string) *shellConnection {
	s.shellConnectionDo.DO = *(s.shellConnectionDo.As(alias).(*gen.DO))
	return s.updateTableName(alias)
}

func (s *shellConnection) updateTableName(table string) *shellConnection {
	s.ALL = field.NewAsterisk(table)
	s.ID = field.NewInt64(table, "id")
	s.Name = field.NewString(table, "name")
	s.Description = field.NewString(table, "description")
	s.AgentUUID = field.NewString(table, "agent_uuid")
	s.Mode = field.NewString(table, "mode")
	s.RunAsUser = field.NewString(table, "run_as_user")
	s.Sudo = field.NewBool(table, "sudo")
	s.Host = field.NewString(table, "host")
	s.Port = field.NewInt64(table, "port")
	s.SSHUsername = field.NewString(table, "ssh_username")
	s.AuthMethod = field.NewString(table, "auth_method")
	s.SSHPassword = field.NewString(table, "ssh_password")
	s.SSHPrivateKey = field.NewString(table, "ssh_private_key")
	s.SSHKeyPass = field.NewString(table, "ssh_key_pass")
	s.SudoPassword = field.NewString(table, "sudo_password")
	s.AutoCheckEnabled = field.NewInt64(table, "auto_check_enabled")
	s.AutoCheckIntervalSeconds = field.NewInt64(table, "auto_check_interval_seconds")
	s.CreatedAt = field.NewTime(table, "created_at")
	s.UpdatedAt = field.NewTime(table, "updated_at")
	s.LastStatus = field.NewString(table, "last_status")
	s.LastError = field.NewString(table, "last_error")
	s.LastCheckedAt = field.NewTime(table, "last_checked_at")
	s.AlertEmails = field.NewString(table, "alert_emails")
	s.AlertPhones = field.NewString(table, "alert_phones")
	s.NotifyOnFailure = field.NewBool(table, "notify_on_failure")
	s.Enabled = field.NewBool(table, "enabled")
	s.Suspended = field.NewBool(table, "suspended")

	s.fillFieldMap()

	return s
}

func (s *shellConnection) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := s.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (s *shellConnection) fillFieldMap() {
	s.fieldMap = make(map[string]field.Expr, 27)
	s.fieldMap["id"] = s.ID
	s.fieldMap["name"] = s.Name
	s.fieldMap["description"] = s.Description
	s.fieldMap["agent_uuid"] = s.AgentUUID
	s.fieldMap["mode"] = s.Mode
	s.fieldMap["run_as_user"] = s.RunAsUser
	s.fieldMap["sudo"] = s.Sudo
	s.fieldMap["host"] = s.Host
	s.fieldMap["port"] = s.Port
	s.fieldMap["ssh_username"] = s.SSHUsername
	s.fieldMap["auth_method"] = s.AuthMethod
	s.fieldMap["ssh_password"] = s.SSHPassword
	s.fieldMap["ssh_private_key"] = s.SSHPrivateKey
	s.fieldMap["ssh_key_pass"] = s.SSHKeyPass
	s.fieldMap["sudo_password"] = s.SudoPassword
	s.fieldMap["auto_check_enabled"] = s.AutoCheckEnabled
	s.fieldMap["auto_check_interval_seconds"] = s.AutoCheckIntervalSeconds
	s.fieldMap["created_at"] = s.CreatedAt
	s.fieldMap["updated_at"] = s.UpdatedAt
	s.fieldMap["last_status"] = s.LastStatus
	s.fieldMap["last_error"] = s.LastError
	s.fieldMap["last_checked_at"] = s.LastCheckedAt
	s.fieldMap["alert_emails"] = s.AlertEmails
	s.fieldMap["alert_phones"] = s.AlertPhones
	s.fieldMap["notify_on_failure"] = s.NotifyOnFailure
	s.fieldMap["enabled"] = s.Enabled
	s.fieldMap["suspended"] = s.Suspended
}

func (s shellConnection) clone(db *gorm.DB) shellConnection {
	s.shellConnectionDo.ReplaceConnPool(db.Statement.ConnPool)
	return s
}

func (s shellConnection) replaceDB(db *gorm.DB) shellConnection {
	s.shellConnectionDo.ReplaceDB(db)
	return s
}

type shellConnectionDo struct{ gen.DO }

type IShellConnectionDo interface {
	gen.SubQuery
	Debug() IShellConnectionDo
	WithContext(ctx context.Context) IShellConnectionDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() IShellConnectionDo
	WriteDB() IShellConnectionDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) IShellConnectionDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) IShellConnectionDo
	Not(conds ...gen.Condition) IShellConnectionDo
	Or(conds ...gen.Condition) IShellConnectionDo
	Select(conds ...field.Expr) IShellConnectionDo
	Where(conds ...gen.Condition) IShellConnectionDo
	Order(conds ...field.Expr) IShellConnectionDo
	Distinct(cols ...field.Expr) IShellConnectionDo
	Omit(cols ...field.Expr) IShellConnectionDo
	Join(table schema.Tabler, on ...field.Expr) IShellConnectionDo
	LeftJoin(table schema.Tabler, on ...field.Expr) IShellConnectionDo
	RightJoin(table schema.Tabler, on ...field.Expr) IShellConnectionDo
	Group(cols ...field.Expr) IShellConnectionDo
	Having(conds ...gen.Condition) IShellConnectionDo
	Limit(limit int) IShellConnectionDo
	Offset(offset int) IShellConnectionDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) IShellConnectionDo
	Unscoped() IShellConnectionDo
	Create(values ...*models.ShellConnection) error
	CreateInBatches(values []*models.ShellConnection, batchSize int) error
	Save(values ...*models.ShellConnection) error
	First() (*models.ShellConnection, error)
	Take() (*models.ShellConnection, error)
	Last() (*models.ShellConnection, error)
	Find() ([]*models.ShellConnection, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*models.ShellConnection, err error)
	FindInBatches(result *[]*models.ShellConnection, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*models.ShellConnection) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) IShellConnectionDo
	Assign(attrs ...field.AssignExpr) IShellConnectionDo
	Joins(fields ...field.RelationField) IShellConnectionDo
	Preload(fields ...field.RelationField) IShellConnectionDo
	FirstOrInit() (*models.ShellConnection, error)
	FirstOrCreate() (*models.ShellConnection, error)
	FindByPage(offset int, limit int) (result []*models.ShellConnection, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Rows() (*sql.Rows, error)
	Row() *sql.Row
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) IShellConnectionDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (s shellConnectionDo) Debug() IShellConnectionDo {
	return s.withDO(s.DO.Debug())
}

func (s shellConnectionDo) WithContext(ctx context.Context) IShellConnectionDo {
	return s.withDO(s.DO.WithContext(ctx))
}

func (s shellConnectionDo) ReadDB() IShellConnectionDo {
	return s.Clauses(dbresolver.Read)
}

func (s shellConnectionDo) WriteDB() IShellConnectionDo {
	return s.Clauses(dbresolver.Write)
}

func (s shellConnectionDo) Session(config *gorm.Session) IShellConnectionDo {
	return s.withDO(s.DO.Session(config))
}

func (s shellConnectionDo) Clauses(conds ...clause.Expression) IShellConnectionDo {
	return s.withDO(s.DO.Clauses(conds...))
}

func (s shellConnectionDo) Returning(value interface{}, columns ...string) IShellConnectionDo {
	return s.withDO(s.DO.Returning(value, columns...))
}

func (s shellConnectionDo) Not(conds ...gen.Condition) IShellConnectionDo {
	return s.withDO(s.DO.Not(conds...))
}

func (s shellConnectionDo) Or(conds ...gen.Condition) IShellConnectionDo {
	return s.withDO(s.DO.Or(conds...))
}

func (s shellConnectionDo) Select(conds ...field.Expr) IShellConnectionDo {
	return s.withDO(s.DO.Select(conds...))
}

func (s shellConnectionDo) Where(conds ...gen.Condition) IShellConnectionDo {
	return s.withDO(s.DO.Where(conds...))
}

func (s shellConnectionDo) Order(conds ...field.Expr) IShellConnectionDo {
	return s.withDO(s.DO.Order(conds...))
}

func (s shellConnectionDo) Distinct(cols ...field.Expr) IShellConnectionDo {
	return s.withDO(s.DO.Distinct(cols...))
}

func (s shellConnectionDo) Omit(cols ...field.Expr) IShellConnectionDo {
	return s.withDO(s.DO.Omit(cols...))
}

func (s shellConnectionDo) Join(table schema.Tabler, on ...field.Expr) IShellConnectionDo {
	return s.withDO(s.DO.Join(table, on...))
}

func (s shellConnectionDo) LeftJoin(table schema.Tabler, on ...field.Expr) IShellConnectionDo {
	return s.withDO(s.DO.LeftJoin(table, on...))
}

func (s shellConnectionDo) RightJoin(table schema.Tabler, on ...field.Expr) IShellConnectionDo {
	return s.withDO(s.DO.RightJoin(table, on...))
}

func (s shellConnectionDo) Group(cols ...field.Expr) IShellConnectionDo {
	return s.withDO(s.DO.Group(cols...))
}

func (s shellConnectionDo) Having(conds ...gen.Condition) IShellConnectionDo {
	return s.withDO(s.DO.Having(conds...))
}

func (s shellConnectionDo) Limit(limit int) IShellConnectionDo {
	return s.withDO(s.DO.Limit(limit))
}

func (s shellConnectionDo) Offset(offset int) IShellConnectionDo {
	return s.withDO(s.DO.Offset(offset))
}

func (s shellConnectionDo) Scopes(funcs ...func(gen.Dao) gen.Dao) IShellConnectionDo {
	return s.withDO(s.DO.Scopes(funcs...))
}

func (s shellConnectionDo) Unscoped() IShellConnectionDo {
	return s.withDO(s.DO.Unscoped())
}

func (s shellConnectionDo) Create(values ...*models.ShellConnection) error {
	if len(values) == 0 {
		return nil
	}
	return s.DO.Create(values)
}

func (s shellConnectionDo) CreateInBatches(values []*models.ShellConnection, batchSize int) error {
	return s.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (s shellConnectionDo) Save(values ...*models.ShellConnection) error {
	if len(values) == 0 {
		return nil
	}
	return s.DO.Save(values)
}

func (s shellConnectionDo) First() (*models.ShellConnection, error) {
	if result, err := s.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*models.ShellConnection), nil
	}
}

func (s shellConnectionDo) Take() (*models.ShellConnection, error) {
	if result, err := s.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*models.ShellConnection), nil
	}
}

func (s shellConnectionDo) Last() (*models.ShellConnection, error) {
	if result, err := s.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*models.ShellConnection), nil
	}
}

func (s shellConnectionDo) Find() ([]*models.ShellConnection, error) {
	result, err := s.DO.Find()
	return result.([]*models.ShellConnection), err
}

func (s shellConnectionDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*models.ShellConnection, err error) {
	buf := make([]*models.ShellConnection, 0, batchSize)
	err = s.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (s shellConnectionDo) FindInBatches(result *[]*models.ShellConnection, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return s.DO.FindInBatches(result, batchSize, fc)
}

func (s shellConnectionDo) Attrs(attrs ...field.AssignExpr) IShellConnectionDo {
	return s.withDO(s.DO.Attrs(attrs...))
}

func (s shellConnectionDo) Assign(attrs ...field.AssignExpr) IShellConnectionDo {
	return s.withDO(s.DO.Assign(attrs...))
}

func (s shellConnectionDo) Joins(fields ...field.RelationField) IShellConnectionDo {
	for _, _f := range fields {
		s = *s.withDO(s.DO.Joins(_f))
	}
	return &s
}

func (s shellConnectionDo) Preload(fields ...field.RelationField) IShellConnectionDo {
	for _, _f := range fields {
		s = *s.withDO(s.DO.Preload(_f))
	}
	return &s
}

func (s shellConnectionDo) FirstOrInit() (*models.ShellConnection, error) {
	if result, err := s.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*models.ShellConnection), nil
	}
}

func (s shellConnectionDo) FirstOrCreate() (*models.ShellConnection, error) {
	if result, err := s.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*models.ShellConnection), nil
	}
}

func (s shellConnectionDo) FindByPage(offset int, limit int) (result []*models.ShellConnection, count int64, err error) {
	result, err = s.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = s.Offset(-1).Limit(-1).Count()
	return
}

func (s shellConnectionDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = s.Count()
	if err != nil {
		return
	}

	err = s.Offset(offset).Limit(limit).Scan(result)
	return
}

func (s shellConnectionDo) Scan(result interface{}) (err error) {
	return s.DO.Scan(result)
}

func (s shellConnectionDo) Delete(models ...*models.ShellConnection) (result gen.ResultInfo, err error) {
	return s.DO.Delete(models)
}

func (s *shellConnectionDo) withDO(do gen.Dao) *shellConnectionDo {
	s.DO = *do.(*gen.DO)
	return s
}
