// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package db

import (
	"context"
	"database/sql"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"chronix/internal/db/models"
)

func newWebtaskConnection(db *gorm.DB, opts ...gen.DOOption) webtaskConnection {
	_webtaskConnection := webtaskConnection{}

	_webtaskConnection.webtaskConnectionDo.UseDB(db, opts...)
	_webtaskConnection.webtaskConnectionDo.UseModel(&models.WebtaskConnection{})

	tableName := _webtaskConnection.webtaskConnectionDo.TableName()
	_webtaskConnection.ALL = field.NewAsterisk(tableName)
	_webtaskConnection.ID = field.NewInt64(tableName, "id")
	_webtaskConnection.Name = field.NewString(tableName, "name")
	_webtaskConnection.Description = field.NewString(tableName, "description")
	_webtaskConnection.BaseURL = field.NewString(tableName, "base_url")
	_webtaskConnection.AuthType = field.NewString(tableName, "auth_type")
	_webtaskConnection.AuthConfig = field.NewField(tableName, "auth_config")
	_webtaskConnection.AgentUUID = field.NewString(tableName, "agent_uuid")
	_webtaskConnection.AutoCheckEnabled = field.NewInt64(tableName, "auto_check_enabled")
	_webtaskConnection.AutoCheckIntervalSeconds = field.NewInt64(tableName, "auto_check_interval_seconds")
	_webtaskConnection.CreatedAt = field.NewTime(tableName, "created_at")
	_webtaskConnection.UpdatedAt = field.NewTime(tableName, "updated_at")
	_webtaskConnection.LastStatus = field.NewString(tableName, "last_status")
	_webtaskConnection.LastError = field.NewString(tableName, "last_error")
	_webtaskConnection.LastCheckedAt = field.NewTime(tableName, "last_checked_at")
	_webtaskConnection.AlertEmails = field.NewString(tableName, "alert_emails")
	_webtaskConnection.AlertPhones = field.NewString(tableName, "alert_phones")
	_webtaskConnection.NotifyOnFailure = field.NewBool(tableName, "notify_on_failure")
	_webtaskConnection.Enabled = field.NewBool(tableName, "enabled")
	_webtaskConnection.Suspended = field.NewBool(tableName, "suspended")

	_webtaskConnection.fillFieldMap()

	return _webtaskConnection
}

type webtaskConnection struct {
	webtaskConnectionDo

	ALL                      field.Asterisk
	ID                       field.Int64
	Name                     field.String
	Description              field.String
	BaseURL                  field.String
	AuthType                 field.String
	AuthConfig               field.Field
	AgentUUID                field.String
	AutoCheckEnabled         field.Int64
	AutoCheckIntervalSeconds field.Int64
	CreatedAt                field.Time
	UpdatedAt                field.Time
	LastStatus               field.String
	LastError                field.String
	LastCheckedAt            field.Time
	AlertEmails              field.String
	AlertPhones              field.String
	NotifyOnFailure          field.Bool
	Enabled                  field.Bool
	Suspended                field.Bool

	fieldMap map[string]field.Expr
}

func (w webtaskConnection) Table(newTableName string) *webtaskConnection {
	w.webtaskConnectionDo.UseTable(newTableName)
	return w.updateTableName(newTableName)
}

func (w webtaskConnection) As(alias string) *webtaskConnection {
	w.webtaskConnectionDo.DO = *(w.webtaskConnectionDo.As(alias).(*gen.DO))
	return w.updateTableName(alias)
}

func (w *webtaskConnection) updateTableName(table string) *webtaskConnection {
	w.ALL = field.NewAsterisk(table)
	w.ID = field.NewInt64(table, "id")
	w.Name = field.NewString(table, "name")
	w.Description = field.NewString(table, "description")
	w.BaseURL = field.NewString(table, "base_url")
	w.AuthType = field.NewString(table, "auth_type")
	w.AuthConfig = field.NewField(table, "auth_config")
	w.AgentUUID = field.NewString(table, "agent_uuid")
	w.AutoCheckEnabled = field.NewInt64(table, "auto_check_enabled")
	w.AutoCheckIntervalSeconds = field.NewInt64(table, "auto_check_interval_seconds")
	w.CreatedAt = field.NewTime(table, "created_at")
	w.UpdatedAt = field.NewTime(table, "updated_at")
	w.LastStatus = field.NewString(table, "last_status")
	w.LastError = field.NewString(table, "last_error")
	w.LastCheckedAt = field.NewTime(table, "last_checked_at")
	w.AlertEmails = field.NewString(table, "alert_emails")
	w.AlertPhones = field.NewString(table, "alert_phones")
	w.NotifyOnFailure = field.NewBool(table, "notify_on_failure")
	w.Enabled = field.NewBool(table, "enabled")
	w.Suspended = field.NewBool(table, "suspended")

	w.fillFieldMap()

	return w
}

func (w *webtaskConnection) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := w.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (w *webtaskConnection) fillFieldMap() {
	w.fieldMap = make(map[string]field.Expr, 19)
	w.fieldMap["id"] = w.ID
	w.fieldMap["name"] = w.Name
	w.fieldMap["description"] = w.Description
	w.fieldMap["base_url"] = w.BaseURL
	w.fieldMap["auth_type"] = w.AuthType
	w.fieldMap["auth_config"] = w.AuthConfig
	w.fieldMap["agent_uuid"] = w.AgentUUID
	w.fieldMap["auto_check_enabled"] = w.AutoCheckEnabled
	w.fieldMap["auto_check_interval_seconds"] = w.AutoCheckIntervalSeconds
	w.fieldMap["created_at"] = w.CreatedAt
	w.fieldMap["updated_at"] = w.UpdatedAt
	w.fieldMap["last_status"] = w.LastStatus
	w.fieldMap["last_error"] = w.LastError
	w.fieldMap["last_checked_at"] = w.LastCheckedAt
	w.fieldMap["alert_emails"] = w.AlertEmails
	w.fieldMap["alert_phones"] = w.AlertPhones
	w.fieldMap["notify_on_failure"] = w.NotifyOnFailure
	w.fieldMap["enabled"] = w.Enabled
	w.fieldMap["suspended"] = w.Suspended
}

func (w webtaskConnection) clone(db *gorm.DB) webtaskConnection {
	w.webtaskConnectionDo.ReplaceConnPool(db.Statement.ConnPool)
	return w
}

func (w webtaskConnection) replaceDB(db *gorm.DB) webtaskConnection {
	w.webtaskConnectionDo.ReplaceDB(db)
	return w
}

type webtaskConnectionDo struct{ gen.DO }

type IWebtaskConnectionDo interface {
	gen.SubQuery
	Debug() IWebtaskConnectionDo
	WithContext(ctx context.Context) IWebtaskConnectionDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() IWebtaskConnectionDo
	WriteDB() IWebtaskConnectionDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) IWebtaskConnectionDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) IWebtaskConnectionDo
	Not(conds ...gen.Condition) IWebtaskConnectionDo
	Or(conds ...gen.Condition) IWebtaskConnectionDo
	Select(conds ...field.Expr) IWebtaskConnectionDo
	Where(conds ...gen.Condition) IWebtaskConnectionDo
	Order(conds ...field.Expr) IWebtaskConnectionDo
	Distinct(cols ...field.Expr) IWebtaskConnectionDo
	Omit(cols ...field.Expr) IWebtaskConnectionDo
	Join(table schema.Tabler, on ...field.Expr) IWebtaskConnectionDo
	LeftJoin(table schema.Tabler, on ...field.Expr) IWebtaskConnectionDo
	RightJoin(table schema.Tabler, on ...field.Expr) IWebtaskConnectionDo
	Group(cols ...field.Expr) IWebtaskConnectionDo
	Having(conds ...gen.Condition) IWebtaskConnectionDo
	Limit(limit int) IWebtaskConnectionDo
	Offset(offset int) IWebtaskConnectionDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) IWebtaskConnectionDo
	Unscoped() IWebtaskConnectionDo
	Create(values ...*models.WebtaskConnection) error
	CreateInBatches(values []*models.WebtaskConnection, batchSize int) error
	Save(values ...*models.WebtaskConnection) error
	First() (*models.WebtaskConnection, error)
	Take() (*models.WebtaskConnection, error)
	Last() (*models.WebtaskConnection, error)
	Find() ([]*models.WebtaskConnection, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*models.WebtaskConnection, err error)
	FindInBatches(result *[]*models.WebtaskConnection, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*models.WebtaskConnection) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) IWebtaskConnectionDo
	Assign(attrs ...field.AssignExpr) IWebtaskConnectionDo
	Joins(fields ...field.RelationField) IWebtaskConnectionDo
	Preload(fields ...field.RelationField) IWebtaskConnectionDo
	FirstOrInit() (*models.WebtaskConnection, error)
	FirstOrCreate() (*models.WebtaskConnection, error)
	FindByPage(offset int, limit int) (result []*models.WebtaskConnection, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Rows() (*sql.Rows, error)
	Row() *sql.Row
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) IWebtaskConnectionDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (w webtaskConnectionDo) Debug() IWebtaskConnectionDo {
	return w.withDO(w.DO.Debug())
}

func (w webtaskConnectionDo) WithContext(ctx context.Context) IWebtaskConnectionDo {
	return w.withDO(w.DO.WithContext(ctx))
}

func (w webtaskConnectionDo) ReadDB() IWebtaskConnectionDo {
	return w.Clauses(dbresolver.Read)
}

func (w webtaskConnectionDo) WriteDB() IWebtaskConnectionDo {
	return w.Clauses(dbresolver.Write)
}

func (w webtaskConnectionDo) Session(config *gorm.Session) IWebtaskConnectionDo {
	return w.withDO(w.DO.Session(config))
}

func (w webtaskConnectionDo) Clauses(conds ...clause.Expression) IWebtaskConnectionDo {
	return w.withDO(w.DO.Clauses(conds...))
}

func (w webtaskConnectionDo) Returning(value interface{}, columns ...string) IWebtaskConnectionDo {
	return w.withDO(w.DO.Returning(value, columns...))
}

func (w webtaskConnectionDo) Not(conds ...gen.Condition) IWebtaskConnectionDo {
	return w.withDO(w.DO.Not(conds...))
}

func (w webtaskConnectionDo) Or(conds ...gen.Condition) IWebtaskConnectionDo {
	return w.withDO(w.DO.Or(conds...))
}

func (w webtaskConnectionDo) Select(conds ...field.Expr) IWebtaskConnectionDo {
	return w.withDO(w.DO.Select(conds...))
}

func (w webtaskConnectionDo) Where(conds ...gen.Condition) IWebtaskConnectionDo {
	return w.withDO(w.DO.Where(conds...))
}

func (w webtaskConnectionDo) Order(conds ...field.Expr) IWebtaskConnectionDo {
	return w.withDO(w.DO.Order(conds...))
}

func (w webtaskConnectionDo) Distinct(cols ...field.Expr) IWebtaskConnectionDo {
	return w.withDO(w.DO.Distinct(cols...))
}

func (w webtaskConnectionDo) Omit(cols ...field.Expr) IWebtaskConnectionDo {
	return w.withDO(w.DO.Omit(cols...))
}

func (w webtaskConnectionDo) Join(table schema.Tabler, on ...field.Expr) IWebtaskConnectionDo {
	return w.withDO(w.DO.Join(table, on...))
}

func (w webtaskConnectionDo) LeftJoin(table schema.Tabler, on ...field.Expr) IWebtaskConnectionDo {
	return w.withDO(w.DO.LeftJoin(table, on...))
}

func (w webtaskConnectionDo) RightJoin(table schema.Tabler, on ...field.Expr) IWebtaskConnectionDo {
	return w.withDO(w.DO.RightJoin(table, on...))
}

func (w webtaskConnectionDo) Group(cols ...field.Expr) IWebtaskConnectionDo {
	return w.withDO(w.DO.Group(cols...))
}

func (w webtaskConnectionDo) Having(conds ...gen.Condition) IWebtaskConnectionDo {
	return w.withDO(w.DO.Having(conds...))
}

func (w webtaskConnectionDo) Limit(limit int) IWebtaskConnectionDo {
	return w.withDO(w.DO.Limit(limit))
}

func (w webtaskConnectionDo) Offset(offset int) IWebtaskConnectionDo {
	return w.withDO(w.DO.Offset(offset))
}

func (w webtaskConnectionDo) Scopes(funcs ...func(gen.Dao) gen.Dao) IWebtaskConnectionDo {
	return w.withDO(w.DO.Scopes(funcs...))
}

func (w webtaskConnectionDo) Unscoped() IWebtaskConnectionDo {
	return w.withDO(w.DO.Unscoped())
}

func (w webtaskConnectionDo) Create(values ...*models.WebtaskConnection) error {
	if len(values) == 0 {
		return nil
	}
	return w.DO.Create(values)
}

func (w webtaskConnectionDo) CreateInBatches(values []*models.WebtaskConnection, batchSize int) error {
	return w.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (w webtaskConnectionDo) Save(values ...*models.WebtaskConnection) error {
	if len(values) == 0 {
		return nil
	}
	return w.DO.Save(values)
}

func (w webtaskConnectionDo) First() (*models.WebtaskConnection, error) {
	if result, err := w.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*models.WebtaskConnection), nil
	}
}

func (w webtaskConnectionDo) Take() (*models.WebtaskConnection, error) {
	if result, err := w.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*models.WebtaskConnection), nil
	}
}

func (w webtaskConnectionDo) Last() (*models.WebtaskConnection, error) {
	if result, err := w.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*models.WebtaskConnection), nil
	}
}

func (w webtaskConnectionDo) Find() ([]*models.WebtaskConnection, error) {
	result, err := w.DO.Find()
	return result.([]*models.WebtaskConnection), err
}

func (w webtaskConnectionDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*models.WebtaskConnection, err error) {
	buf := make([]*models.WebtaskConnection, 0, batchSize)
	err = w.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (w webtaskConnectionDo) FindInBatches(result *[]*models.WebtaskConnection, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return w.DO.FindInBatches(result, batchSize, fc)
}

func (w webtaskConnectionDo) Attrs(attrs ...field.AssignExpr) IWebtaskConnectionDo {
	return w.withDO(w.DO.Attrs(attrs...))
}

func (w webtaskConnectionDo) Assign(attrs ...field.AssignExpr) IWebtaskConnectionDo {
	return w.withDO(w.DO.Assign(attrs...))
}

func (w webtaskConnectionDo) Joins(fields ...field.RelationField) IWebtaskConnectionDo {
	for _, _f := range fields {
		w = *w.withDO(w.DO.Joins(_f))
	}
	return &w
}

func (w webtaskConnectionDo) Preload(fields ...field.RelationField) IWebtaskConnectionDo {
	for _, _f := range fields {
		w = *w.withDO(w.DO.Preload(_f))
	}
	return &w
}

func (w webtaskConnectionDo) FirstOrInit() (*models.WebtaskConnection, error) {
	if result, err := w.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*models.WebtaskConnection), nil
	}
}

func (w webtaskConnectionDo) FirstOrCreate() (*models.WebtaskConnection, error) {
	if result, err := w.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*models.WebtaskConnection), nil
	}
}

func (w webtaskConnectionDo) FindByPage(offset int, limit int) (result []*models.WebtaskConnection, count int64, err error) {
	result, err = w.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = w.Offset(-1).Limit(-1).Count()
	return
}

func (w webtaskConnectionDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = w.Count()
	if err != nil {
		return
	}

	err = w.Offset(offset).Limit(limit).Scan(result)
	return
}

func (w webtaskConnectionDo) Scan(result interface{}) (err error) {
	return w.DO.Scan(result)
}

func (w webtaskConnectionDo) Delete(models ...*models.WebtaskConnection) (result gen.ResultInfo, err error) {
	return w.DO.Delete(models)
}

func (w *webtaskConnectionDo) withDO(do gen.Dao) *webtaskConnectionDo {
	w.DO = *do.(*gen.DO)
	return w
}
