// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package db

import (
	"context"
	"database/sql"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"chronix/internal/db/models"
)

func newWebtaskActionStep(db *gorm.DB, opts ...gen.DOOption) webtaskActionStep {
	_webtaskActionStep := webtaskActionStep{}

	_webtaskActionStep.webtaskActionStepDo.UseDB(db, opts...)
	_webtaskActionStep.webtaskActionStepDo.UseModel(&models.WebtaskActionStep{})

	tableName := _webtaskActionStep.webtaskActionStepDo.TableName()
	_webtaskActionStep.ALL = field.NewAsterisk(tableName)
	_webtaskActionStep.ID = field.NewInt64(tableName, "id")
	_webtaskActionStep.ActionID = field.NewInt64(tableName, "action_id")
	_webtaskActionStep.StepOrder = field.NewInt64(tableName, "step_order")
	_webtaskActionStep.Name = field.NewString(tableName, "name")
	_webtaskActionStep.Method = field.NewString(tableName, "method")
	_webtaskActionStep.URL = field.NewString(tableName, "url")
	_webtaskActionStep.Headers = field.NewField(tableName, "headers")
	_webtaskActionStep.Body = field.NewString(tableName, "body")
	_webtaskActionStep.TimeoutSeconds = field.NewInt64(tableName, "timeout_seconds")
	_webtaskActionStep.Expectation = field.NewField(tableName, "expectation")
	_webtaskActionStep.ResponseCapture = field.NewField(tableName, "response_capture")
	_webtaskActionStep.OnFailure = field.NewString(tableName, "on_failure")

	_webtaskActionStep.fillFieldMap()

	return _webtaskActionStep
}

type webtaskActionStep struct {
	webtaskActionStepDo

	ALL             field.Asterisk
	ID              field.Int64
	ActionID        field.Int64
	StepOrder       field.Int64
	Name            field.String
	Method          field.String
	URL             field.String
	Headers         field.Field
	Body            field.String
	TimeoutSeconds  field.Int64
	Expectation     field.Field
	ResponseCapture field.Field
	OnFailure       field.String

	fieldMap map[string]field.Expr
}

func (w webtaskActionStep) Table(newTableName string) *webtaskActionStep {
	w.webtaskActionStepDo.UseTable(newTableName)
	return w.updateTableName(newTableName)
}

func (w webtaskActionStep) As(alias string) *webtaskActionStep {
	w.webtaskActionStepDo.DO = *(w.webtaskActionStepDo.As(alias).(*gen.DO))
	return w.updateTableName(alias)
}

func (w *webtaskActionStep) updateTableName(table string) *webtaskActionStep {
	w.ALL = field.NewAsterisk(table)
	w.ID = field.NewInt64(table, "id")
	w.ActionID = field.NewInt64(table, "action_id")
	w.StepOrder = field.NewInt64(table, "step_order")
	w.Name = field.NewString(table, "name")
	w.Method = field.NewString(table, "method")
	w.URL = field.NewString(table, "url")
	w.Headers = field.NewField(table, "headers")
	w.Body = field.NewString(table, "body")
	w.TimeoutSeconds = field.NewInt64(table, "timeout_seconds")
	w.Expectation = field.NewField(table, "expectation")
	w.ResponseCapture = field.NewField(table, "response_capture")
	w.OnFailure = field.NewString(table, "on_failure")

	w.fillFieldMap()

	return w
}

func (w *webtaskActionStep) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := w.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (w *webtaskActionStep) fillFieldMap() {
	w.fieldMap = make(map[string]field.Expr, 12)
	w.fieldMap["id"] = w.ID
	w.fieldMap["action_id"] = w.ActionID
	w.fieldMap["step_order"] = w.StepOrder
	w.fieldMap["name"] = w.Name
	w.fieldMap["method"] = w.Method
	w.fieldMap["url"] = w.URL
	w.fieldMap["headers"] = w.Headers
	w.fieldMap["body"] = w.Body
	w.fieldMap["timeout_seconds"] = w.TimeoutSeconds
	w.fieldMap["expectation"] = w.Expectation
	w.fieldMap["response_capture"] = w.ResponseCapture
	w.fieldMap["on_failure"] = w.OnFailure
}

func (w webtaskActionStep) clone(db *gorm.DB) webtaskActionStep {
	w.webtaskActionStepDo.ReplaceConnPool(db.Statement.ConnPool)
	return w
}

func (w webtaskActionStep) replaceDB(db *gorm.DB) webtaskActionStep {
	w.webtaskActionStepDo.ReplaceDB(db)
	return w
}

type webtaskActionStepDo struct{ gen.DO }

type IWebtaskActionStepDo interface {
	gen.SubQuery
	Debug() IWebtaskActionStepDo
	WithContext(ctx context.Context) IWebtaskActionStepDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() IWebtaskActionStepDo
	WriteDB() IWebtaskActionStepDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) IWebtaskActionStepDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) IWebtaskActionStepDo
	Not(conds ...gen.Condition) IWebtaskActionStepDo
	Or(conds ...gen.Condition) IWebtaskActionStepDo
	Select(conds ...field.Expr) IWebtaskActionStepDo
	Where(conds ...gen.Condition) IWebtaskActionStepDo
	Order(conds ...field.Expr) IWebtaskActionStepDo
	Distinct(cols ...field.Expr) IWebtaskActionStepDo
	Omit(cols ...field.Expr) IWebtaskActionStepDo
	Join(table schema.Tabler, on ...field.Expr) IWebtaskActionStepDo
	LeftJoin(table schema.Tabler, on ...field.Expr) IWebtaskActionStepDo
	RightJoin(table schema.Tabler, on ...field.Expr) IWebtaskActionStepDo
	Group(cols ...field.Expr) IWebtaskActionStepDo
	Having(conds ...gen.Condition) IWebtaskActionStepDo
	Limit(limit int) IWebtaskActionStepDo
	Offset(offset int) IWebtaskActionStepDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) IWebtaskActionStepDo
	Unscoped() IWebtaskActionStepDo
	Create(values ...*models.WebtaskActionStep) error
	CreateInBatches(values []*models.WebtaskActionStep, batchSize int) error
	Save(values ...*models.WebtaskActionStep) error
	First() (*models.WebtaskActionStep, error)
	Take() (*models.WebtaskActionStep, error)
	Last() (*models.WebtaskActionStep, error)
	Find() ([]*models.WebtaskActionStep, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*models.WebtaskActionStep, err error)
	FindInBatches(result *[]*models.WebtaskActionStep, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*models.WebtaskActionStep) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) IWebtaskActionStepDo
	Assign(attrs ...field.AssignExpr) IWebtaskActionStepDo
	Joins(fields ...field.RelationField) IWebtaskActionStepDo
	Preload(fields ...field.RelationField) IWebtaskActionStepDo
	FirstOrInit() (*models.WebtaskActionStep, error)
	FirstOrCreate() (*models.WebtaskActionStep, error)
	FindByPage(offset int, limit int) (result []*models.WebtaskActionStep, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Rows() (*sql.Rows, error)
	Row() *sql.Row
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) IWebtaskActionStepDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (w webtaskActionStepDo) Debug() IWebtaskActionStepDo {
	return w.withDO(w.DO.Debug())
}

func (w webtaskActionStepDo) WithContext(ctx context.Context) IWebtaskActionStepDo {
	return w.withDO(w.DO.WithContext(ctx))
}

func (w webtaskActionStepDo) ReadDB() IWebtaskActionStepDo {
	return w.Clauses(dbresolver.Read)
}

func (w webtaskActionStepDo) WriteDB() IWebtaskActionStepDo {
	return w.Clauses(dbresolver.Write)
}

func (w webtaskActionStepDo) Session(config *gorm.Session) IWebtaskActionStepDo {
	return w.withDO(w.DO.Session(config))
}

func (w webtaskActionStepDo) Clauses(conds ...clause.Expression) IWebtaskActionStepDo {
	return w.withDO(w.DO.Clauses(conds...))
}

func (w webtaskActionStepDo) Returning(value interface{}, columns ...string) IWebtaskActionStepDo {
	return w.withDO(w.DO.Returning(value, columns...))
}

func (w webtaskActionStepDo) Not(conds ...gen.Condition) IWebtaskActionStepDo {
	return w.withDO(w.DO.Not(conds...))
}

func (w webtaskActionStepDo) Or(conds ...gen.Condition) IWebtaskActionStepDo {
	return w.withDO(w.DO.Or(conds...))
}

func (w webtaskActionStepDo) Select(conds ...field.Expr) IWebtaskActionStepDo {
	return w.withDO(w.DO.Select(conds...))
}

func (w webtaskActionStepDo) Where(conds ...gen.Condition) IWebtaskActionStepDo {
	return w.withDO(w.DO.Where(conds...))
}

func (w webtaskActionStepDo) Order(conds ...field.Expr) IWebtaskActionStepDo {
	return w.withDO(w.DO.Order(conds...))
}

func (w webtaskActionStepDo) Distinct(cols ...field.Expr) IWebtaskActionStepDo {
	return w.withDO(w.DO.Distinct(cols...))
}

func (w webtaskActionStepDo) Omit(cols ...field.Expr) IWebtaskActionStepDo {
	return w.withDO(w.DO.Omit(cols...))
}

func (w webtaskActionStepDo) Join(table schema.Tabler, on ...field.Expr) IWebtaskActionStepDo {
	return w.withDO(w.DO.Join(table, on...))
}

func (w webtaskActionStepDo) LeftJoin(table schema.Tabler, on ...field.Expr) IWebtaskActionStepDo {
	return w.withDO(w.DO.LeftJoin(table, on...))
}

func (w webtaskActionStepDo) RightJoin(table schema.Tabler, on ...field.Expr) IWebtaskActionStepDo {
	return w.withDO(w.DO.RightJoin(table, on...))
}

func (w webtaskActionStepDo) Group(cols ...field.Expr) IWebtaskActionStepDo {
	return w.withDO(w.DO.Group(cols...))
}

func (w webtaskActionStepDo) Having(conds ...gen.Condition) IWebtaskActionStepDo {
	return w.withDO(w.DO.Having(conds...))
}

func (w webtaskActionStepDo) Limit(limit int) IWebtaskActionStepDo {
	return w.withDO(w.DO.Limit(limit))
}

func (w webtaskActionStepDo) Offset(offset int) IWebtaskActionStepDo {
	return w.withDO(w.DO.Offset(offset))
}

func (w webtaskActionStepDo) Scopes(funcs ...func(gen.Dao) gen.Dao) IWebtaskActionStepDo {
	return w.withDO(w.DO.Scopes(funcs...))
}

func (w webtaskActionStepDo) Unscoped() IWebtaskActionStepDo {
	return w.withDO(w.DO.Unscoped())
}

func (w webtaskActionStepDo) Create(values ...*models.WebtaskActionStep) error {
	if len(values) == 0 {
		return nil
	}
	return w.DO.Create(values)
}

func (w webtaskActionStepDo) CreateInBatches(values []*models.WebtaskActionStep, batchSize int) error {
	return w.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (w webtaskActionStepDo) Save(values ...*models.WebtaskActionStep) error {
	if len(values) == 0 {
		return nil
	}
	return w.DO.Save(values)
}

func (w webtaskActionStepDo) First() (*models.WebtaskActionStep, error) {
	if result, err := w.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*models.WebtaskActionStep), nil
	}
}

func (w webtaskActionStepDo) Take() (*models.WebtaskActionStep, error) {
	if result, err := w.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*models.WebtaskActionStep), nil
	}
}

func (w webtaskActionStepDo) Last() (*models.WebtaskActionStep, error) {
	if result, err := w.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*models.WebtaskActionStep), nil
	}
}

func (w webtaskActionStepDo) Find() ([]*models.WebtaskActionStep, error) {
	result, err := w.DO.Find()
	return result.([]*models.WebtaskActionStep), err
}

func (w webtaskActionStepDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*models.WebtaskActionStep, err error) {
	buf := make([]*models.WebtaskActionStep, 0, batchSize)
	err = w.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (w webtaskActionStepDo) FindInBatches(result *[]*models.WebtaskActionStep, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return w.DO.FindInBatches(result, batchSize, fc)
}

func (w webtaskActionStepDo) Attrs(attrs ...field.AssignExpr) IWebtaskActionStepDo {
	return w.withDO(w.DO.Attrs(attrs...))
}

func (w webtaskActionStepDo) Assign(attrs ...field.AssignExpr) IWebtaskActionStepDo {
	return w.withDO(w.DO.Assign(attrs...))
}

func (w webtaskActionStepDo) Joins(fields ...field.RelationField) IWebtaskActionStepDo {
	for _, _f := range fields {
		w = *w.withDO(w.DO.Joins(_f))
	}
	return &w
}

func (w webtaskActionStepDo) Preload(fields ...field.RelationField) IWebtaskActionStepDo {
	for _, _f := range fields {
		w = *w.withDO(w.DO.Preload(_f))
	}
	return &w
}

func (w webtaskActionStepDo) FirstOrInit() (*models.WebtaskActionStep, error) {
	if result, err := w.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*models.WebtaskActionStep), nil
	}
}

func (w webtaskActionStepDo) FirstOrCreate() (*models.WebtaskActionStep, error) {
	if result, err := w.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*models.WebtaskActionStep), nil
	}
}

func (w webtaskActionStepDo) FindByPage(offset int, limit int) (result []*models.WebtaskActionStep, count int64, err error) {
	result, err = w.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = w.Offset(-1).Limit(-1).Count()
	return
}

func (w webtaskActionStepDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = w.Count()
	if err != nil {
		return
	}

	err = w.Offset(offset).Limit(limit).Scan(result)
	return
}

func (w webtaskActionStepDo) Scan(result interface{}) (err error) {
	return w.DO.Scan(result)
}

func (w webtaskActionStepDo) Delete(models ...*models.WebtaskActionStep) (result gen.ResultInfo, err error) {
	return w.DO.Delete(models)
}

func (w *webtaskActionStepDo) withDO(do gen.Dao) *webtaskActionStepDo {
	w.DO = *do.(*gen.DO)
	return w
}
